/**
 * automationTemplates.ts — Pre-built automation templates
 *
 * Users can pick a template to quickly create common automations.
 * Each template pre-fills the creation form.
 */

export interface AutomationTemplate {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: 'accountability' | 'reporting' | 'engagement' | 'ops';
  trigger_type: 'schedule' | 'event' | 'manual';
  cron_expression?: string;
  event_config?: { table?: string; event: string; provider?: string };
  agent: string;
  model: string;
  output_target: 'activity' | 'chat' | 'webhook' | 'silent';
  prompt: string;
  include_context: Record<string, boolean>;
  /** Show in the Suggested section of the dashboard */
  suggested?: boolean;
  /** Icon background color for the suggested grid card */
  suggestedIconBg?: string;
}

export const AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  {
    id: 'daily-standup-summary',
    name: 'Daily Standup Summary',
    icon: '📋',
    description: "Summarize today's check-ins and tasks, highlight who's on track",
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Review today's check-ins and recent task completions for {{circle_name}}. Summarize what each member accomplished, call out who hasn't checked in, and highlight any streaks at risk. Keep it under 200 words. Be direct.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: false },
  },
  {
    id: 'weekly-progress-report',
    name: 'Weekly Progress Report',
    icon: '📊',
    description: 'End-of-week analytics with wins, concerns, and recommendations',
    category: 'reporting',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: 'Generate a weekly progress report for {{circle_name}}. Include: total check-ins this week, tasks completed vs created, streak changes, most active member, MVP nomination. End with one actionable recommendation for next week.',
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
  },
  {
    id: 'streak-risk-alert',
    name: 'Streak Risk Alert',
    icon: '🔥',
    description: "Alert when members with 3+ day streaks haven't checked in",
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Check which members of {{circle_name}} have 3+ day streaks but haven't checked in today. For each at-risk member, write a brief personalized nudge. Don't be annoying — be direct and caring. If everyone has checked in, say so briefly.",
    include_context: { members: true, check_ins: true, streaks: true },
  },
  {
    id: 'new-member-welcome',
    name: 'New Member Welcome',
    icon: '👋',
    description: 'Automatically welcome new members with circle context',
    category: 'engagement',
    trigger_type: 'event',
    event_config: { table: 'circle_members', event: 'INSERT' },
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: 'A new member just joined {{circle_name}}. Welcome them warmly. Share: what this circle is about, the top 3 members by streak, and one tip for getting started. Keep it personal and energetic.',
    include_context: { members: true, check_ins: false, tasks: false, streaks: true },
  },
  {
    id: 'checkin-celebration',
    name: 'Check-in Celebration',
    icon: '🎉',
    description: 'Celebrate milestone check-ins (7, 14, 30, 50, 100 days)',
    category: 'engagement',
    trigger_type: 'event',
    event_config: { table: 'check_ins', event: 'INSERT' },
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "A member just checked in. Check their streak data. If their current streak is a milestone (7, 14, 21, 30, 50, 100 days), write a short celebration message with their name. If it's NOT a milestone, respond with just SKIP (the system will ignore it). Event data: {{event}}",
    include_context: { members: true, streaks: true },
  },
  {
    id: 'task-completion-digest',
    name: 'Task Completion Digest',
    icon: '✅',
    description: 'Daily digest of completed tasks with impact summary',
    category: 'reporting',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'activity',
    prompt: "List all tasks completed today in {{circle_name}}. For each, note who completed it. End with the circle's overall open vs done task ratio. If no tasks were completed, say so briefly.",
    include_context: { members: true, tasks: true },
  },
  {
    id: 'monday-motivation',
    name: 'Monday Motivation',
    icon: '💪',
    description: 'Weekly motivational kickoff with last week highlights',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "It's Monday. Write a motivational kickoff for {{circle_name}}. Reference last week's wins (tasks done, streaks maintained). Set the tone for the week. Be real, not generic. Quote a real entrepreneur or builder — not the usual suspects. Keep it under 150 words.",
    include_context: { members: true, tasks: true, streaks: true, analytics: true },
  },
  {
    id: 'inactivity-detector',
    name: 'Inactivity Detector',
    icon: '👀',
    description: 'Flag members inactive for 3+ days',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'activity',
    prompt: "Check {{circle_name}} for members who haven't checked in or completed tasks in 3+ days. List them with their last streak count. Suggest one re-engagement action. If everyone is active, say so briefly.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true },
  },
  {
    id: 'challenge-progress-update',
    name: 'Challenge Progress Update',
    icon: '🏆',
    description: 'Daily leaderboard for active challenges',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: 'Summarize active challenges in {{circle_name}}. Show who is leading and who is falling behind. Add a competitive nudge. Keep it under 150 words.',
    include_context: { members: true, check_ins: true, tasks: true },
  },
  {
    id: 'monthly-retrospective',
    name: 'Monthly Retrospective',
    icon: '📝',
    description: 'End-of-month review with trends and insights',
    category: 'reporting',
    trigger_type: 'schedule',
    cron_expression: 'monthly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: 'Generate a monthly retrospective for {{circle_name}}. Analyze: participation trends, streak patterns, task velocity, most improved member, biggest challenge. Provide 3 data-driven recommendations for next month. Format with headers and bullet points.',
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
  },
  // ─── New templates ────────────────────────────────────────
  {
    id: 'task-assigned-alert',
    name: 'Task Assigned Alert',
    icon: '📌',
    description: 'Notify when a task is completed with a short summary',
    category: 'engagement',
    trigger_type: 'event',
    event_config: { table: 'tasks', event: 'UPDATE' },
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "A task was just completed in {{circle_name}}. Event data: {{event}}. Write a brief congrats message mentioning who completed it and the task title. Keep it to 1-2 sentences. If the data is unclear, say SKIP.",
    include_context: { members: true, tasks: true },
  },
  {
    id: 'daily-goal-tracker',
    name: 'Daily Goal Tracker',
    icon: '🎯',
    description: 'Track progress toward goals with daily check-in analysis',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Analyze today's progress for {{circle_name}}. Look at check-ins for mentions of goals, milestones, or blockers. Identify who is making progress and who might need help. Give 1 specific suggestion per struggling member. Be direct, under 200 words.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true },
  },
  {
    id: 'weekend-recap',
    name: 'Weekend Recap',
    icon: '🎬',
    description: 'Fun weekend summary with stats and highlights',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "It's the weekend! Write a fun recap of {{circle_name}}'s week. Include: MVP (most tasks done or best streak), funniest/most interesting check-in, a random award (e.g. 'Most Likely to Deploy on Friday'), and a challenge for next week. Keep the tone playful. Under 200 words.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true },
  },
  {
    id: 'cost-alert',
    name: 'AI Cost Alert',
    icon: '💰',
    description: 'Alert when AI agent spending exceeds daily threshold',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'every_6h',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'activity',
    prompt: "Check AI agent spending for {{circle_name}}. Review token usage and cost data. If total daily cost exceeds $5, flag it with a warning and recommend switching expensive tasks to Haiku. If costs are normal, say SKIP.",
    include_context: { members: true, analytics: true },
  },
  {
    id: 'smart-nudge',
    name: 'Smart Nudge',
    icon: '🧠',
    description: 'AI picks the most impactful nudge based on who needs it most',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'twice_daily',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Analyze {{circle_name}} and identify the ONE member who would benefit most from a nudge right now. Consider: haven't checked in, streak at risk, tasks overdue, or declining activity. Write a personalized, caring but direct message to that specific person. Use their name. One person only, under 100 words. If everyone is crushing it, give a short group shoutout instead.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true },
  },
  {
    id: 'proactive-checkin',
    name: 'Proactive Check-in',
    icon: '💓',
    description: 'Twice-daily heartbeat that reviews who needs attention and sends personalized nudges',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'twice_daily',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Run a proactive check-in for {{circle_name}}. Review: 1) Who hasn't checked in today? 2) Who has tasks overdue by 2+ days? 3) Who has declining streak momentum? For each person who needs attention, write a brief, personalized nudge (use their name, reference their specific situation). For members who are on track, give a quick one-line acknowledgment. End with one team-level observation. Be a coach, not a bot. Under 300 words.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
  },
  // ─── Boss Agent (Jon Snow) Automations ──────────────────────────────────────
  {
    id: 'boss-task-promoter',
    name: 'Boss: Auto-Promote Reviewed Tasks',
    icon: '🐺',
    description: 'Jon Snow checks peer-reviewed tasks every 10 min — auto-promotes to final review when all peers have approved',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: '*/10 * * * *',
    agent: 'Jon Snow',
    model: 'claude-haiku',
    output_target: 'activity',
    prompt: "You are Jon Snow, the Boss agent. Check all tasks in 'peer_review' status for {{circle_name}}. For each task, check if all assigned peer reviewers (from the task's goal) have approved. If ALL peers approved, promote the task to 'review' status and post a comment: '[AUTO_PROMOTED] Jon Snow promoted this task after all peer reviewers approved.' If some peers haven't reviewed yet, note which ones are pending. Report what you promoted and what's still waiting. Tasks in peer_review: {{tasks_in_peer_review}}",
    include_context: { tasks: true },
    suggested: false,
  },
  {
    id: 'boss-task-generator',
    name: 'Boss: Daily Task Generation',
    icon: '🐺',
    description: 'Jon Snow generates tasks daily based on active goals with auto-task settings',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'Jon Snow',
    model: 'claude-sonnet',
    output_target: 'activity',
    prompt: "You are Jon Snow, the Boss agent for {{circle_name}}. Review each active goal that has auto_task_count > 0. For each goal, analyze how many tasks exist vs the target count. If more tasks are needed, generate new task titles and descriptions that advance the goal. Assign them round-robin to the goal's assigned agents. Output as JSON array: [{title, description, priority, assigned_agent_id, goal_id}]. Goals: {{goals}} Recent tasks: {{recent_tasks}}",
    include_context: { tasks: true, members: true },
    suggested: false,
  },
  {
    id: 'boss-stuck-detector',
    name: 'Boss: Detect Stuck Tasks',
    icon: '🐺',
    description: 'Jon Snow flags tasks stuck in the same status for 24+ hours and escalates via Telegram',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'every_6h',
    agent: 'Jon Snow',
    model: 'claude-haiku',
    output_target: 'activity',
    prompt: "You are Jon Snow, the Boss agent for {{circle_name}}. Find tasks that have been stuck in 'in_progress', 'peer_review', or 'review' for more than 24 hours. For each stuck task: identify the assignee, how long it's been stuck, and suggest an action (reassign, break into subtasks, or escalate). If any task is stuck >48h, flag it as URGENT. Stuck tasks: {{stuck_tasks}}",
    include_context: { tasks: true, members: true },
    suggested: false,
  },
  {
    id: 'telegram-task-alert',
    name: 'Telegram: Task Review Alert',
    icon: '📱',
    description: 'Send Telegram notification when a task needs your review or gets stuck',
    category: 'ops',
    trigger_type: 'event',
    event_config: { table: 'tasks', event: 'UPDATE' },
    agent: 'System',
    model: 'claude-haiku',
    output_target: 'webhook',
    prompt: "A task status changed in {{circle_name}}. Event data: {{event}}. If the task moved to 'review' or 'approved', send a notification: '📋 [TASK_NAME] is ready for your review.' If the task has been stuck >24h, send: '⚠️ [TASK_NAME] has been stuck for [TIME]. Consider taking action.' If neither condition applies, respond with SKIP.",
    include_context: { tasks: true },
    suggested: false,
  },

  // ── Productivity & Growth ──────────────────────────────────────────────────

  {
    id: 'focus-time-guardian',
    name: 'Focus Time Guardian',
    icon: '🧘',
    description: 'Post a daily deep work window reminder and protect focus blocks from distractions',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "It's focus time for {{circle_name}}. Review each member's active tasks and pick the single highest-priority item they should deep work on right now. Post a concise focus block: member name → task → suggested time block (25m, 50m, or 90m based on complexity). End with a reminder: phones off, notifications silenced. Go.",
    include_context: { members: true, tasks: true },
  },
  {
    id: 'accountability-partner-match',
    name: 'Accountability Partner Match',
    icon: '🤝',
    description: 'Weekly pairing of members as accountability partners based on shared goals',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Match members of {{circle_name}} into accountability pairs for this week. Pair people with complementary goals or similar struggles — someone strong in consistency with someone building that habit. For each pair: explain why they're matched, suggest one thing they should check in on daily, and set a micro-challenge they can do together. Rotate from last week's pairings.",
    include_context: { members: true, check_ins: true, streaks: true, tasks: true },
  },
  {
    id: 'morning-intentions',
    name: 'Morning Intentions',
    icon: '🌅',
    description: 'Prompt members to set their top 3 intentions for the day each morning',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Good morning {{circle_name}}. Review yesterday's results — who completed their tasks, who fell short. Then post a fresh daily intentions prompt. Ask each member to reply with their TOP 3 for today (not 5, not 10 — three). Include a quick energy check: 🔋 How charged are you 1-10? Tailor the tone based on yesterday's momentum — celebratory if the group crushed it, urgent if they slacked.",
    include_context: { members: true, check_ins: true, tasks: true },
  },
  {
    id: 'evening-reflection',
    name: 'Evening Reflection',
    icon: '🌙',
    description: 'End-of-day reflection prompt with wins, lessons, and tomorrow preview',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "It's reflection time for {{circle_name}}. Review today's task completions and check-ins. Post an evening wrap: 🏆 Top win of the day (the single best thing someone accomplished), 📉 Biggest miss (diplomatically — what didn't get done), 💡 Lesson of the day (pattern you noticed), 👀 Tomorrow preview (what's on deck). Keep the vibe honest but encouraging.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true },
  },
  {
    id: 'habit-streak-leaderboard',
    name: 'Habit Streak Leaderboard',
    icon: '🏅',
    description: 'Daily leaderboard ranking members by streak length with trash talk',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Post the daily streak leaderboard for {{circle_name}}. Rank all members by current streak length (longest first). Use medals: 🥇🥈🥉 for top 3. Add light competitive trash talk — hype the leader, call out anyone who just lost their streak (RIP 💀), and give a shoutout to anyone who just hit a milestone (7, 14, 30, 60, 90, 365 days). Keep it fun, not mean.",
    include_context: { members: true, streaks: true },
  },
  {
    id: 'weekly-goal-review',
    name: 'Weekly Goal Review',
    icon: '🎯',
    description: 'Score each goal 0-100% and recommend adjustments for the coming week',
    category: 'reporting',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Run a weekly goal review for {{circle_name}}. For each active goal: calculate a completion score (0-100%) based on tasks done vs total, assess momentum (accelerating/steady/stalling/stalled), and recommend ONE specific adjustment for next week. If any goal is >2 weeks old with <20% completion, flag it as at-risk and suggest either breaking it down or pivoting. End with the group's overall goal health score.",
    include_context: { members: true, tasks: true, streaks: true, analytics: true },
  },
  {
    id: 'procrastination-buster',
    name: 'Procrastination Buster',
    icon: '⚡',
    description: 'Detect tasks that have been sitting untouched and challenge members to start them',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Find tasks in {{circle_name}} that have been in 'todo' or 'backlog' for 3+ days without any activity. For each procrastinated task: tag the assignee, estimate how long the task actually takes (be honest — most things take 15-45 min), and issue a direct challenge: 'This takes ~20 min. Can you start it in the next 2 hours? Reply ✅ to commit.' If someone has 3+ stale tasks, call it out as a pattern.",
    include_context: { members: true, tasks: true },
  },
  {
    id: 'win-of-the-week',
    name: 'Win of the Week',
    icon: '🏆',
    description: 'Celebrate the biggest individual and team wins from the past week',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "It's Win of the Week time for {{circle_name}}! Review the past 7 days — tasks completed, streaks maintained, goals advanced, check-ins submitted. Award: 🏆 MVP (most impactful contributor), 🔥 Iron Will (longest active streak), 🚀 Momentum Award (biggest week-over-week improvement), 💪 Comeback Award (recovered from a broken streak or setback). Write a 2-sentence hype paragraph for each winner. This should feel like a celebration.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
  },
  {
    id: 'sunday-planning-session',
    name: 'Sunday Planning Session',
    icon: '📅',
    description: 'Guided weekly planning — review last week, set priorities for the week ahead',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "It's Sunday planning for {{circle_name}}. Run a structured planning session: 1) LAST WEEK SCORECARD — tasks completed/total, streak health, goal progress %. 2) UNFINISHED BUSINESS — list every carry-over task and ask: keep, kill, or delegate? 3) THIS WEEK'S BIG 3 — for each member, suggest 3 high-impact tasks based on their goals. 4) POTENTIAL BLOCKERS — flag anything that could derail the week. 5) COMMITMENT — ask each member to reply with their #1 non-negotiable for the week.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
  },
  {
    id: 'energy-check',
    name: 'Midday Energy Check',
    icon: '🔋',
    description: 'Quick pulse check on the group energy and momentum at midday',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Midday energy check for {{circle_name}}. Look at today's activity so far — who's checked in, who hasn't, tasks moved, messages sent. Give a group energy reading: 🟢 Crushing it / 🟡 Steady / 🟠 Slow start / 🔴 Ghost town. If energy is low, post a specific micro-challenge anyone can do in 5 minutes to build momentum. If energy is high, amplify it with a quick shoutout.",
    include_context: { members: true, check_ins: true, tasks: true },
  },
  {
    id: 'skill-share-prompt',
    name: 'Skill Share Prompt',
    icon: '🧠',
    description: 'Weekly prompt for a member to share a skill, tip, or lesson with the group',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "It's skill-share time in {{circle_name}}. Pick a different member each week (rotate through the roster). Based on their recent activity and completed tasks, suggest a topic they could share a 2-minute tip on. Post: '@[member] — you crushed [specific thing] this week. Drop a quick tip for the group: how do you [related skill]?' Also suggest 2 backup topics in case they want to pick a different one.",
    include_context: { members: true, tasks: true, check_ins: true },
  },
  {
    id: 'deadline-countdown',
    name: 'Deadline Countdown',
    icon: '⏰',
    description: 'Alert when tasks or goals are approaching their deadlines',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Check all tasks and goals in {{circle_name}} that have due dates. Flag anything due in the next 48 hours: ⏰ [TASK] due in [TIME] — assigned to [MEMBER] — status: [STATUS]. If something is overdue, flag it as 🚨 OVERDUE. If a task due today hasn't been started, escalate: 'This is due TODAY and still in [status]. What's the plan?' Group by urgency: overdue → due today → due tomorrow.",
    include_context: { members: true, tasks: true },
  },
];

export const TEMPLATE_CATEGORIES = [
  { key: 'accountability' as const, label: 'Accountability', icon: '🎯' },
  { key: 'reporting' as const, label: 'Reporting', icon: '📊' },
  { key: 'engagement' as const, label: 'Engagement', icon: '🎉' },
  { key: 'ops' as const, label: 'Operations', icon: '⚙️' },
];

// ─── Suggested Templates (shown in the Suggested grid) ───────────────────────

export const SUGGESTED_TEMPLATES: AutomationTemplate[] = [
  // ── First 4 (always visible) ──────────────────────────────────────────────
  {
    id: 'suggest-find-vulnerabilities',
    name: 'Find vulnerabilities',
    icon: '🛡️',
    description: 'Review PRs for security vulnerabilities and flag exploitable weaknesses before merge',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'github', event: 'pull_request_opened' },
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: 'Review this PR for security vulnerabilities. Check for: SQL injection, XSS, auth bypasses, exposed secrets, unsafe dependencies, insecure direct object references. For each issue found, provide the file, line range, severity (critical/high/medium), and a recommended fix. PR context: {{event}}',
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#0d2a1a',
  },
  {
    id: 'suggest-assign-pr-reviewers',
    name: 'Assign PR reviewers',
    icon: '🔀',
    description: 'Assign reviewers based on code changes and auto-approve low-risk PRs',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'github', event: 'pull_request_opened' },
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: 'Analyze this PR and recommend the best reviewers from {{circle_name}} based on who has worked on the changed files. If the PR is low-risk (only docs, tests, or style changes), auto-approve it. Otherwise list top 2 reviewers with rationale. PR context: {{event}}',
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#0d1a2a',
  },
  {
    id: 'suggest-summarize-changes-daily',
    name: 'Summarize changes daily',
    icon: '📧',
    description: 'Post a daily digest summarizing notable repository changes and risks from the previous day',
    category: 'reporting',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Generate a daily changelog digest for {{circle_name}}. Summarize yesterday's commits: what shipped, what changed, any risky changes, open PRs needing review. Flag anything that could break prod. Keep it under 250 words.",
    include_context: { members: true, tasks: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#1a1a1a',
  },
  {
    id: 'suggest-fix-bugs-in-slack',
    name: 'Fix bugs reported in Slack',
    icon: '🔧',
    description: 'Monitor a Slack channel for bug reports, investigate the codebase, and fix with a PR',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'slack', event: 'message' },
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: 'A message was posted in the bug-reports Slack channel for {{circle_name}}. Message: {{event}}. If this is a bug report, analyze the error, investigate likely root causes, and propose a fix with specific file + line changes. If not a bug report, respond with SKIP.',
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#1a0d2a',
  },
  // ── More (collapsed by default) ───────────────────────────────────────────
  {
    id: 'suggest-add-test-coverage',
    name: 'Add test coverage',
    icon: '🧪',
    description: 'Review recent changes and add tests for high-risk logic that lacks adequate coverage',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Review {{circle_name}}'s recent commits and identify functions/components with high business logic complexity and no test coverage. For each, write the test spec (unit or integration) and output a ready-to-use test file. Prioritize auth, payments, and data mutation flows.",
    include_context: { members: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#0d2a0d',
  },
  {
    id: 'suggest-clean-feature-flags',
    name: 'Clean up feature flags',
    icon: '🚩',
    description: 'Find stale feature flags that are fully rolled out and remove dead code paths',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Analyze {{circle_name}}'s codebase for stale feature flags. List flags that are: enabled for 100% of users, older than 30 days, or never referenced. For each, suggest the exact code deletion to clean them up. Output as a checklist.",
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#2a0d0d',
  },
  {
    id: 'suggest-find-critical-bugs',
    name: 'Find critical bugs',
    icon: '🐛',
    description: 'Analyze recent commits for high-severity correctness bugs and submit safe fixes',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Scan {{circle_name}}'s recent commits for critical correctness bugs: null pointer dereferences, off-by-one errors, race conditions, incorrect error handling, data loss risks. For each bug found: file + line, severity, root cause, proposed safe fix. Only report high/critical severity.",
    include_context: { members: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#2a1a0d',
  },
  {
    id: 'suggest-fix-ci-failures',
    name: 'Fix CI failures',
    icon: '⚙️',
    description: 'Detect CI failures on main and automatically open PRs with fixes',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'github', event: 'ci_completed' },
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: 'A CI run just completed for {{circle_name}}. CI data: {{event}}. If it failed, analyze the failure logs, identify the root cause, and propose an exact fix (file + code change). If all checks passed, respond with SKIP.',
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#0d1a2a',
  },
  {
    id: 'suggest-generate-docs',
    name: 'Generate docs',
    icon: '📄',
    description: 'Create and update developer documentation for recently changed or under-documented code',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Review {{circle_name}}'s recent code changes and identify: new exports with no JSDoc, updated APIs with outdated docs, complex functions without comments. Generate complete documentation for the top 5 most critical gaps. Format as ready-to-paste JSDoc + README updates.",
    include_context: { members: true, tasks: true },
    suggested: true,
    suggestedIconBg: '#1a1a2a',
  },
  {
    id: 'suggest-investigate-pagerduty',
    name: 'Investigate PagerDuty incidents',
    icon: '🔍',
    description: 'Investigate incidents using logs and code context to produce root cause analysis',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'slack', event: 'message' },
    agent: 'BlackSwan',
    model: 'claude-opus',
    output_target: 'chat',
    prompt: 'An incident was triggered for {{circle_name}}. Incident data: {{event}}. Perform a rapid root cause analysis: what service is affected, likely causes based on recent deployments, immediate mitigation steps, and long-term fix. Output a structured RCA in under 300 words.',
    include_context: { members: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#2a0d1a',
  },
  {
    id: 'suggest-investigate-datadog',
    name: 'Investigate top Datadog errors',
    icon: '🔬',
    description: 'Investigate recurring production errors, identify root causes, and propose fixes',
    category: 'ops',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Review {{circle_name}}'s top production errors from the last 24h. For each error: count/frequency, first vs latest occurrence, affected users, likely code location, proposed fix. Prioritize by user impact. Output top 3 errors with full investigation.",
    include_context: { members: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#1a0a0a',
  },
  {
    id: 'suggest-triage-linear',
    name: 'Triage Linear issues',
    icon: '🎟️',
    description: 'Triage new issues by investigating bugs, planning feature requests, and opening PRs for easy fixes',
    category: 'ops',
    trigger_type: 'event',
    event_config: { provider: 'linear', event: 'issue_created' },
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: 'A new Linear issue was created for {{circle_name}}. Issue: {{event}}. Triage it: 1) Classify (bug/feature/chore/spike) 2) Estimate complexity (S/M/L/XL) 3) Suggest priority (urgent/high/medium/low) with rationale 4) If it\'s a small bug, write the fix. 5) Assign to the most relevant team member based on expertise.',
    include_context: { members: true },
    suggested: true,
    suggestedIconBg: '#0d0d2a',
  },

  // ── Accountability & Growth (suggested) ────────────────────────────────────

  {
    id: 'suggest-morning-standup',
    name: 'Morning standup',
    icon: '🌅',
    description: 'Kick off each day with intentions, energy check, and yesterday\'s review',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Good morning {{circle_name}}. Review yesterday's results — who completed their tasks, who fell short. Post a daily intentions prompt asking each member for their TOP 3 today and a quick energy check (🔋 1-10). Tailor the tone based on yesterday's momentum.",
    include_context: { members: true, check_ins: true, tasks: true },
    suggested: true,
    suggestedIconBg: '#1a200d',
  },
  {
    id: 'suggest-streak-leaderboard',
    name: 'Streak leaderboard',
    icon: '🔥',
    description: 'Daily streak rankings with medals, milestones, and friendly competition',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Post the daily streak leaderboard for {{circle_name}}. Rank all members by streak length. 🥇🥈🥉 for top 3. Call out broken streaks (RIP 💀), celebrate milestones (7, 14, 30, 60, 90 days), and hype the leader. Keep it fun and competitive.",
    include_context: { members: true, streaks: true },
    suggested: true,
    suggestedIconBg: '#2a150d',
  },
  {
    id: 'suggest-procrastination-buster',
    name: 'Bust procrastination',
    icon: '⚡',
    description: 'Find stale tasks, estimate real time to complete, and challenge members to start',
    category: 'accountability',
    trigger_type: 'schedule',
    cron_expression: 'daily',
    agent: 'BlackSwan',
    model: 'claude-haiku',
    output_target: 'chat',
    prompt: "Find tasks in {{circle_name}} sitting in 'todo' or 'backlog' for 3+ days. For each: tag the assignee, estimate real time (most things take 15-45 min), issue a challenge: 'Can you start this in the next 2 hours? Reply ✅ to commit.' Flag patterns of 3+ stale tasks.",
    include_context: { members: true, tasks: true },
    suggested: true,
    suggestedIconBg: '#2a1a00',
  },
  {
    id: 'suggest-win-of-the-week',
    name: 'Win of the week',
    icon: '🏆',
    description: 'Celebrate MVPs, streaks, comebacks, and biggest improvements weekly',
    category: 'engagement',
    trigger_type: 'schedule',
    cron_expression: 'weekly',
    agent: 'BlackSwan',
    model: 'claude-sonnet',
    output_target: 'chat',
    prompt: "Review the past 7 days for {{circle_name}}. Award: 🏆 MVP, 🔥 Iron Will (longest streak), 🚀 Momentum (biggest improvement), 💪 Comeback (recovered from setback). Write hype paragraphs for each winner. Make it feel like a celebration.",
    include_context: { members: true, check_ins: true, tasks: true, streaks: true, analytics: true },
    suggested: true,
    suggestedIconBg: '#1a0d20',
  },
];
