export type CircleIntegrationGroupKey =
  | 'ai_agents_services'
  | 'code_delivery'
  | 'auth_identity'
  | 'publishing_web'
  | 'comms_community'
  | 'marketing_growth'
  | 'data_search'
  | 'ops_infra'
  | 'observability_security'
  | 'crm_revenue'
  | 'design_knowledge'
  | 'workflow_automation';

export type CircleIntegrationPlatformKey =
  | 'browserbase'
  | 'stagehand'
  | 'playwright_mcp'
  | 'browserless'
  | 'browserstack'
  | 'firecrawl'
  | 'apify'
  | 'steel'
  | 'hyperbrowser'
  | 'airtop'
  | 'skyvern'
  | 'browser_use'
  | 'braintrust'
  | 'vercel'
  | 'netlify'
  | 'descope'
  | 'github'
  | 'wordpress'
  | 'slack'
  | 'teams'
  | 'discord'
  | 'helius'
  | 'algolia'
  | 'pinecone'
  | 'aws'
  | 'cloudflare'
  | 'resend'
  | 'hubspot'
  | 'google_analytics'
  | 'google_search_console'
  | 'google_ads'
  | 'meta_ads'
  | 'posthog'
  | 'sentry'
  | 'shopify'
  | 'mailchimp'
  | 'convertkit'
  | 'salesforce'
  | 'pipedrive'
  | 'figma'
  | 'notion'
  | 'launchdarkly'
  | 'datadog'
  | 'cloudinary'
  | 'mux'
  | 'stripe'
  // ── Wave 1 expansion (DevOps, AI infra, data, project mgmt, etc.) ──
  | 'docker'
  | 'kubernetes'
  | 'fly_io'
  | 'railway'
  | 'render'
  | 'digitalocean'
  | 'supabase'
  | 'neon'
  | 'mongodb_atlas'
  | 'upstash'
  | 'hugging_face'
  | 'replicate'
  | 'modal'
  | 'openrouter'
  | 'linear'
  | 'jira'
  | 'snyk'
  | 'clerk'
  | 'postmark'
  | 'cloudflare_r2'
  | 'qdrant'
  | 'ngrok'
  | 'trigger_dev'
  // ── Wave 2: native LLM providers (BYOK) ──
  | 'anthropic'
  | 'openai'
  | 'google_ai'
  | 'groq'
  | 'mistral_ai'
  | 'cohere'
  | 'perplexity'
  | 'together_ai'
  | 'fireworks_ai'
  | 'deepseek'
  | 'z_ai'
  | 'minimax'
  | 'ollama';

export interface CircleIntegrationGroup {
  key: CircleIntegrationGroupKey;
  label: string;
  description: string;
}

export interface CircleIntegrationCatalogItem {
  id: string;
  label: string;
  icon: string;
  color: string;
  group: CircleIntegrationGroupKey;
  description: string;
  relationships: string[];
  capabilityLabel: string;
  scopeLabel: string;
  availability: 'available' | 'planned';
  platformKey?: CircleIntegrationPlatformKey;
  recentlyAdded?: boolean;
  /**
   * Lower number = surfaces earlier when sort=popularity. Curated rather
   * than data-driven: until we have real install telemetry to back a
   * "most installed" ranking, we hand-rank the providers most chat
   * users reach for first. Items without a rank sort to the bottom.
   */
  popularityRank?: number;
}

export const CIRCLE_INTEGRATION_GROUPS: CircleIntegrationGroup[] = [
  {
    key: 'ai_agents_services',
    label: 'AI Agents And Services',
    description: 'Coding agents, web automation, evals, agent infrastructure, and model-facing services.',
  },
  {
    key: 'code_delivery',
    label: 'Code And Delivery',
    description: 'Source control, coding agents, deployment signals, and engineering execution.',
  },
  {
    key: 'auth_identity',
    label: 'Authentication And Identity',
    description: 'Auth, SSO, permissions, user identity, and access management.',
  },
  {
    key: 'publishing_web',
    label: 'Publishing And Web',
    description: 'CMS, websites, landing pages, and content operations.',
  },
  {
    key: 'comms_community',
    label: 'Comms And Community',
    description: 'Internal coordination, alerts, team messaging, and public communities.',
  },
  {
    key: 'marketing_growth',
    label: 'Marketing And Growth',
    description: 'Analytics, campaigns, search, audience growth, and channel performance.',
  },
  {
    key: 'data_search',
    label: 'Data And Search',
    description: 'Databases, vector stores, internal knowledge search, and retrieval systems.',
  },
  {
    key: 'ops_infra',
    label: 'Operations And Infrastructure',
    description: 'Hosting, DNS, environments, access, observability, and execution safety.',
  },
  {
    key: 'observability_security',
    label: 'Observability And Security',
    description: 'Monitoring, logging, tracing, alerts, security reviews, and guardrails.',
  },
  {
    key: 'crm_revenue',
    label: 'CRM And Revenue',
    description: 'Leads, customers, billing, storefronts, and commercial operations.',
  },
  {
    key: 'design_knowledge',
    label: 'Design And Knowledge',
    description: 'Creative assets, documentation, briefs, SOPs, and knowledge systems.',
  },
  {
    key: 'workflow_automation',
    label: 'Workflow And Automation',
    description: 'Email, task routing, approvals, queues, automations, and operational glue.',
  },
];

export const CIRCLE_INTEGRATION_CATALOG: CircleIntegrationCatalogItem[] = [
  {
    id: 'openswan-runtime',
    label: 'OpenSwan Runtime',
    icon: 'OS',
    color: '#22c55e',
    group: 'ai_agents_services',
    description: 'Coding-agent runtime, session control, delegation, web automation, and execution cockpit for Pixel Agents.',
    relationships: ['Office', 'Coding agents', 'Tasks'],
    capabilityLabel: 'Native coding-agent runtime',
    scopeLabel: 'Built into the app',
    availability: 'available',
  },
  {
    id: 'browserbase',
    label: 'Browserbase',
    icon: 'BB',
    color: '#14b8a6',
    group: 'ai_agents_services',
    description: 'Cloud browser automation for agents that need durable, remote web sessions and browser task execution.',
    relationships: ['Web automation', 'Support agents', 'QA'],
    capabilityLabel: 'Agent browser infrastructure',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'browserbase',
  },
  {
    id: 'stagehand',
    label: 'Stagehand',
    icon: 'SH',
    color: '#06b6d4',
    group: 'ai_agents_services',
    description: 'AI browser-agent framework for natural-language web actions, self-healing browser flows, and reusable agent workflows.',
    relationships: ['Browserbase', 'Playwright', 'OpenSwan'],
    capabilityLabel: 'AI browser action layer',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'stagehand',
    recentlyAdded: true,
  },
  {
    id: 'playwright-mcp',
    label: 'Playwright MCP',
    icon: 'PW',
    color: '#2dd4bf',
    group: 'ai_agents_services',
    description: 'Deterministic browser control, DOM snapshots, screenshots, and test generation through the Model Context Protocol.',
    relationships: ['Browser QA', 'MCP', 'OpenSwan'],
    capabilityLabel: 'Deterministic browser control',
    scopeLabel: 'Local or circle-wide',
    availability: 'available',
    platformKey: 'playwright_mcp',
    recentlyAdded: true,
  },
  {
    id: 'browserless',
    label: 'Browserless',
    icon: 'BL',
    color: '#f97316',
    group: 'ai_agents_services',
    description: 'Headless browser API for screenshots, PDFs, scraping, scripted browser functions, and live browser debugging.',
    relationships: ['Screenshots', 'Scraping', 'Browser QA'],
    capabilityLabel: 'Headless browser API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'browserless',
    recentlyAdded: true,
  },
  {
    id: 'browserstack',
    label: 'BrowserStack',
    icon: 'BS',
    color: '#f59e0b',
    group: 'ai_agents_services',
    description: 'Real-browser and real-device cloud testing for cross-browser QA, session recordings, screenshots, and debugging.',
    relationships: ['QA', 'Real devices', 'Release checks'],
    capabilityLabel: 'Cross-browser and device QA',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'browserstack',
    recentlyAdded: true,
  },
  {
    id: 'firecrawl',
    label: 'Firecrawl',
    icon: 'FC',
    color: '#ef4444',
    group: 'ai_agents_services',
    description: 'Web scrape, crawl, search, and extract APIs that convert pages into clean markdown or structured data for agents.',
    relationships: ['Research', 'RAG', 'Web data'],
    capabilityLabel: 'LLM-ready web extraction',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'firecrawl',
    recentlyAdded: true,
  },
  {
    id: 'apify',
    label: 'Apify',
    icon: 'AP',
    color: '#22c55e',
    group: 'ai_agents_services',
    description: 'Cloud Actors for web scraping, browser automation, datasets, scheduled crawls, and production web-data workflows.',
    relationships: ['Scraping', 'Datasets', 'Automation'],
    capabilityLabel: 'Web automation actors',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'apify',
    recentlyAdded: true,
  },
  {
    id: 'steel',
    label: 'Steel',
    icon: 'ST',
    color: '#94a3b8',
    group: 'ai_agents_services',
    description: 'Open-source browser API for cloud browser fleets, autonomous web agents, scraping jobs, and browser session control.',
    relationships: ['Browser agents', 'Cloud browsers', 'OpenSwan'],
    capabilityLabel: 'Open browser agent API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'steel',
    recentlyAdded: true,
  },
  {
    id: 'hyperbrowser',
    label: 'Hyperbrowser',
    icon: 'HB',
    color: '#38bdf8',
    group: 'ai_agents_services',
    description: 'Browser-as-a-service platform for AI agents, scalable browser sessions, scraping, and Browser Use task execution.',
    relationships: ['Cloud browsers', 'Browser Use', 'OpenSwan'],
    capabilityLabel: 'Scalable browser-agent platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'hyperbrowser',
    recentlyAdded: true,
  },
  {
    id: 'airtop',
    label: 'Airtop',
    icon: 'AT',
    color: '#60a5fa',
    group: 'ai_agents_services',
    description: 'Cloud browser automation for AI agents that need natural-language browsing, managed sessions, and web task execution.',
    relationships: ['AI browser control', 'Managed sessions', 'OpenSwan'],
    capabilityLabel: 'AI browser automation API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'airtop',
    recentlyAdded: true,
  },
  {
    id: 'skyvern',
    label: 'Skyvern',
    icon: 'SV',
    color: '#a78bfa',
    group: 'ai_agents_services',
    description: 'LLM and computer-vision browser workflow automation for forms, dashboards, authenticated sites, and repeatable web operations.',
    relationships: ['Browser workflows', 'Login-heavy sites', 'Operations'],
    capabilityLabel: 'Vision-guided browser workflows',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'skyvern',
    recentlyAdded: true,
  },
  {
    id: 'browser-use',
    label: 'Browser Use',
    icon: 'BU',
    color: '#34d399',
    group: 'ai_agents_services',
    description: 'Open-source browser agent framework for navigating, interpreting, and manipulating web content with LLM-driven tasks.',
    relationships: ['Browser agents', 'Self-hosting', 'OpenSwan'],
    capabilityLabel: 'Open-source browser agent framework',
    scopeLabel: 'Local or circle-wide',
    availability: 'available',
    platformKey: 'browser_use',
    recentlyAdded: true,
  },
  {
    id: 'braintrust',
    label: 'Braintrust',
    icon: 'BT',
    color: '#8b5cf6',
    group: 'ai_agents_services',
    description: 'AI evals, monitoring, prompt regression checks, and experimentation for agent quality.',
    relationships: ['Research', 'Evals', 'Observability'],
    capabilityLabel: 'Agent quality platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'braintrust',
    recentlyAdded: true,
  },
  {
    id: 'github',
    label: 'GitHub',
    icon: '{>}',
    color: '#238636',
    group: 'code_delivery',
    description: 'Repos, pull requests, issues, CI, reviews, and shipping workflows.',
    relationships: ['Deploys', 'Tasks', 'Coding agents'],
    capabilityLabel: 'Engineering system of record',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'github',
    popularityRank: 3,
  },
  {
    id: 'vercel',
    label: 'Vercel',
    icon: '▲',
    color: '#ffffff',
    group: 'code_delivery',
    description: 'Deployments, previews, domains, environment variables, project linking, and production shipping workflows.',
    relationships: ['GitHub', 'OpenSwan', 'Cloudflare'],
    capabilityLabel: 'Frontend deploy platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'vercel',
    popularityRank: 8,
  },
  {
    id: 'netlify',
    label: 'Netlify',
    icon: 'NL',
    color: '#00C7B7',
    group: 'code_delivery',
    description: 'Deployments, previews, domains, forms, and site delivery workflows for static and frontend properties.',
    relationships: ['GitHub', 'Cloudflare', 'OpenSwan'],
    capabilityLabel: 'Frontend delivery platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'netlify',
  },
  {
    id: 'descope',
    label: 'Descope',
    icon: 'DS',
    color: '#60a5fa',
    group: 'auth_identity',
    description: 'Authentication, MFA, SSO, identity flows, and secure app access patterns.',
    relationships: ['Security', 'Users', 'Approvals'],
    capabilityLabel: 'Identity and auth platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'descope',
  },
  {
    id: 'launchdarkly',
    label: 'LaunchDarkly',
    icon: 'LD',
    color: '#7c3aed',
    group: 'workflow_automation',
    description: 'Feature flags, rollouts, guarded releases, experiments, and progressive delivery workflows.',
    relationships: ['PostHog', 'Vercel', 'Product'],
    capabilityLabel: 'Feature flags and experimentation',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'launchdarkly',
    recentlyAdded: true,
  },
  {
    id: 'wordpress',
    label: 'WordPress',
    icon: 'WP',
    color: '#21759B',
    group: 'publishing_web',
    description: 'Blog publishing, page updates, CMS workflows, editorial drafts, and content operations.',
    relationships: ['SEO', 'Content', 'Marketing ops'],
    capabilityLabel: 'Publishing system',
    scopeLabel: 'Circle-wide preferred',
    availability: 'available',
    platformKey: 'wordpress',
  },
  {
    id: 'slack',
    label: 'Slack',
    icon: '💬',
    color: '#4A154B',
    group: 'comms_community',
    description: 'Channel notifications, team check-ins, launch alerts, and operating comms.',
    relationships: ['Standups', 'Alerts', 'Approvals'],
    capabilityLabel: 'Internal team messaging',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'slack',
    popularityRank: 5,
  },
  {
    id: 'teams',
    label: 'Microsoft Teams',
    icon: '💼',
    color: '#5B5FC7',
    group: 'comms_community',
    description: 'Enterprise team communication, channel notices, and company coordination.',
    relationships: ['Enterprise comms', 'Approvals', 'Notifications'],
    capabilityLabel: 'Enterprise team messaging',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'teams',
  },
  {
    id: 'discord',
    label: 'Discord',
    icon: '🎮',
    color: '#5865F2',
    group: 'comms_community',
    description: 'Community messaging, channel browsing, server sync, and public engagement.',
    relationships: ['Community', 'Support', 'Announcements'],
    capabilityLabel: 'Community messaging',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'discord',
    popularityRank: 15,
  },
  {
    id: 'helius',
    label: 'Helius',
    icon: '◎',
    color: '#9945FF',
    group: 'crm_revenue',
    description: 'Solana wallet data, token activity, swaps, and crypto-native finance operations.',
    relationships: ['Treasury', 'Trading', 'Onchain analytics'],
    capabilityLabel: 'Crypto finance ops',
    scopeLabel: 'User-linked',
    availability: 'available',
    platformKey: 'helius',
  },
  {
    id: 'google-analytics',
    label: 'Google Analytics',
    icon: 'GA',
    color: '#F59E0B',
    group: 'marketing_growth',
    description: 'Traffic, funnel performance, conversion reporting, and site behavior analysis.',
    relationships: ['Search Console', 'WordPress', 'Campaigns'],
    capabilityLabel: 'Marketing measurement',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'google_analytics',
  },
  {
    id: 'search-console',
    label: 'Google Search Console',
    icon: 'GSC',
    color: '#10B981',
    group: 'marketing_growth',
    description: 'Search visibility, indexing health, keyword opportunity, and technical SEO insight.',
    relationships: ['Analytics', 'WordPress', 'SEO'],
    capabilityLabel: 'SEO system',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'google_search_console',
  },
  {
    id: 'algolia',
    label: 'Algolia',
    icon: 'ALG',
    color: '#0ea5e9',
    group: 'data_search',
    description: 'User-facing search, indexing, query analytics, and discovery for docs, content, and products.',
    relationships: ['Docs', 'WordPress', 'Knowledge'],
    capabilityLabel: 'User-facing search',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'algolia',
  },
  {
    id: 'cloudinary',
    label: 'Cloudinary',
    icon: 'CLD',
    color: '#2563eb',
    group: 'data_search',
    description: 'Media storage, transformations, asset delivery, and image-heavy content pipelines.',
    relationships: ['WordPress', 'Figma', 'Marketing'],
    capabilityLabel: 'Media pipeline',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'cloudinary',
    recentlyAdded: true,
  },
  {
    id: 'pinecone',
    label: 'Pinecone',
    icon: 'PIN',
    color: '#a855f7',
    group: 'data_search',
    description: 'Vector retrieval for memory, research corpus, semantic search, and agent knowledge systems.',
    relationships: ['Research corpus', 'Soul memory', 'Agents'],
    capabilityLabel: 'Semantic retrieval layer',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'pinecone',
  },
  {
    id: 'supabase-data',
    label: 'Supabase Data',
    icon: 'SB',
    color: '#3ecf8e',
    group: 'data_search',
    description: 'Database, storage, auth, realtime, and backend workflows for app-native operational data.',
    relationships: ['Storage', 'Realtime', 'App backend'],
    capabilityLabel: 'App data platform',
    scopeLabel: 'Built into the app',
    availability: 'available',
  },
  {
    id: 'google-ads',
    label: 'Google Ads',
    icon: 'GAD',
    color: '#2563eb',
    group: 'marketing_growth',
    description: 'Campaign reporting, paid search operations, audience testing, and ad performance workflows.',
    relationships: ['Analytics', 'CRM', 'Landing pages'],
    capabilityLabel: 'Paid acquisition',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'google_ads',
  },
  {
    id: 'meta-ads',
    label: 'Meta Ads',
    icon: 'MAD',
    color: '#2563eb',
    group: 'marketing_growth',
    description: 'Paid social campaigns, audience testing, creative analysis, and acquisition ops.',
    relationships: ['Analytics', 'CRM', 'Landing pages'],
    capabilityLabel: 'Paid social acquisition',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'meta_ads',
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    icon: 'CF',
    color: '#F97316',
    group: 'ops_infra',
    description: 'DNS, CDN, caching, security controls, redirects, and migration cutovers.',
    relationships: ['Hosting', 'WordPress', 'Migrations'],
    capabilityLabel: 'Edge and DNS control',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'cloudflare',
  },
  {
    id: 'datadog',
    label: 'Datadog',
    icon: 'DD',
    color: '#7c3aed',
    group: 'observability_security',
    description: 'Logs, traces, metrics, service health, alerts, and infrastructure visibility.',
    relationships: ['AWS', 'Sentry', 'OpenSwan'],
    capabilityLabel: 'Monitoring and observability',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'datadog',
    recentlyAdded: true,
  },
  {
    id: 'hosting',
    label: 'AWS',
    icon: 'AWS',
    color: '#FF9900',
    group: 'ops_infra',
    description: 'Infrastructure, Route 53, S3, CloudFront, SES, and broader platform operations.',
    relationships: ['GitHub', 'Cloudflare', 'Migrations'],
    capabilityLabel: 'Infrastructure and deploy control',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'aws',
  },
  {
    id: 'resend-email',
    label: 'Resend / Email Delivery',
    icon: '✉',
    color: '#f43f5e',
    group: 'workflow_automation',
    description: 'Transactional email, campaign delivery, notifications, and approval flows.',
    relationships: ['CRM', 'Marketing', 'Support'],
    capabilityLabel: 'Email delivery layer',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'resend',
  },
  {
    id: 'workflow-automation',
    label: 'Workflow Automation',
    icon: 'WF',
    color: '#22c55e',
    group: 'workflow_automation',
    description: 'Queues, approval chains, agent handoffs, task orchestration, and operational automations.',
    relationships: ['Tasks', 'Comms', 'Marketplace apps'],
    capabilityLabel: 'Automation backbone',
    scopeLabel: 'Built into the app',
    availability: 'available',
  },
  {
    id: 'crm',
    label: 'HubSpot',
    icon: 'HS',
    color: '#F97316',
    group: 'crm_revenue',
    description: 'CRM, contacts, deals, lifecycle automation, forms, and revenue operations.',
    relationships: ['Email', 'Ads', 'Content'],
    capabilityLabel: 'Revenue system of record',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'hubspot',
  },
  {
    id: 'salesforce',
    label: 'Salesforce',
    icon: 'SF',
    color: '#00A1E0',
    group: 'crm_revenue',
    description: 'Enterprise CRM, opportunities, accounts, contacts, and large-team revenue workflows.',
    relationships: ['Revenue', 'Email', 'Support'],
    capabilityLabel: 'Enterprise CRM platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'salesforce',
  },
  {
    id: 'pipedrive',
    label: 'Pipedrive',
    icon: 'PD',
    color: '#0f8b4c',
    group: 'crm_revenue',
    description: 'SMB sales pipeline management, deal tracking, contacts, and lean revenue operations.',
    relationships: ['Revenue', 'Email', 'Analytics'],
    capabilityLabel: 'SMB CRM platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'pipedrive',
  },
  {
    id: 'shopify',
    label: 'Shopify',
    icon: 'SH',
    color: '#95BF47',
    group: 'crm_revenue',
    description: 'Storefront operations, products, orders, ecommerce workflows, and commercial fulfillment.',
    relationships: ['Stripe', 'Analytics', 'Email'],
    capabilityLabel: 'Commerce platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'shopify',
  },
  {
    id: 'mailchimp',
    label: 'Mailchimp',
    icon: 'MC',
    color: '#f59e0b',
    group: 'crm_revenue',
    description: 'Campaign automation, audience segmentation, and lifecycle email messaging.',
    relationships: ['CRM', 'Analytics', 'WordPress'],
    capabilityLabel: 'Lifecycle messaging',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'mailchimp',
  },
  {
    id: 'convertkit',
    label: 'ConvertKit',
    icon: 'CK',
    color: '#a855f7',
    group: 'crm_revenue',
    description: 'Creator email automation, broadcasts, audience funnels, and lifecycle messaging.',
    relationships: ['CRM', 'Analytics', 'Content'],
    capabilityLabel: 'Audience messaging',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'convertkit',
  },
  {
    id: 'payments',
    label: 'Stripe',
    icon: '$',
    color: '#635BFF',
    group: 'crm_revenue',
    description: 'Payments, subscriptions, invoices, checkout, and revenue operations.',
    relationships: ['CRM', 'WordPress', 'Analytics'],
    capabilityLabel: 'Commercial operations',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'stripe',
    popularityRank: 10,
  },
  {
    id: 'figma',
    label: 'Figma',
    icon: '◧',
    color: '#EC4899',
    group: 'design_knowledge',
    description: 'Design reviews, asset references, system updates, and creative handoffs.',
    relationships: ['Brand', 'Landing pages', 'Product design'],
    capabilityLabel: 'Design system',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'figma',
    popularityRank: 14,
  },
  {
    id: 'mux',
    label: 'Mux',
    icon: 'MUX',
    color: '#ec4899',
    group: 'design_knowledge',
    description: 'Video ingestion, streaming, asset playback, and video-heavy product or media workflows.',
    relationships: ['Cloudinary', 'Content', 'Marketing'],
    capabilityLabel: 'Video platform',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'mux',
    recentlyAdded: true,
  },
  {
    id: 'posthog',
    label: 'PostHog',
    icon: 'PH',
    color: '#f97316',
    group: 'observability_security',
    description: 'Product analytics, feature flags, experiments, funnels, and usage visibility.',
    relationships: ['Analytics', 'Experiments', 'Product'],
    capabilityLabel: 'Product analytics and flags',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'posthog',
  },
  {
    id: 'sentry',
    label: 'Sentry',
    icon: 'SE',
    color: '#a78bfa',
    group: 'observability_security',
    description: 'Errors, performance traces, crash monitoring, and production issue visibility.',
    relationships: ['Observability', 'QA', 'Runtime'],
    capabilityLabel: 'Error and performance monitoring',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'sentry',
  },
  {
    id: 'knowledge',
    label: 'Docs And Knowledge',
    icon: 'DOC',
    color: '#94A3B8',
    group: 'design_knowledge',
    description: 'Notion, docs, SOPs, briefs, and internal knowledge operations.',
    relationships: ['Research', 'Planning', 'Ops'],
    capabilityLabel: 'Knowledge system',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'notion',
    popularityRank: 9,
  },
  // ── Wave 1 expansion ────────────────────────────────────────────────
  {
    id: 'docker',
    label: 'Docker',
    icon: 'DKR',
    color: '#2496ED',
    group: 'ops_infra',
    description: 'Container builds, registry pushes, and image runs across the team via Docker Hub or local sockets.',
    relationships: ['Kubernetes', 'CI/CD', 'Local dev'],
    capabilityLabel: 'Container build + run',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'docker',
    recentlyAdded: true,
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    icon: 'K8S',
    color: '#326CE5',
    group: 'ops_infra',
    description: 'Cluster control via kubeconfig — inspect pods, roll restarts, apply manifests with plan-then-apply guardrails.',
    relationships: ['Docker', 'Helm', 'CI/CD'],
    capabilityLabel: 'Cluster control',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'kubernetes',
    recentlyAdded: true,
  },
  {
    id: 'fly-io',
    label: 'Fly.io',
    icon: 'FLY',
    color: '#7B3FE4',
    group: 'ops_infra',
    description: 'Edge VMs, Postgres, and branch previews for full-stack apps — deploy, scale, and stream logs from chat.',
    relationships: ['Postgres', 'Branch previews', 'Edge'],
    capabilityLabel: 'Edge VM + Postgres host',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'fly_io',
    recentlyAdded: true,
  },
  {
    id: 'railway',
    label: 'Railway',
    icon: 'RWY',
    color: '#0B0D0E',
    group: 'ops_infra',
    description: 'Git-push PaaS with managed databases — provision Postgres + Redis and wire env vars in one shot.',
    relationships: ['Postgres', 'Redis', 'Branch previews'],
    capabilityLabel: 'Git-push PaaS',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'railway',
    recentlyAdded: true,
  },
  {
    id: 'render',
    label: 'Render',
    icon: 'RDR',
    color: '#46E3B7',
    group: 'ops_infra',
    description: 'Web services, cron jobs, and managed databases — trigger deploys and tail logs without leaving chat.',
    relationships: ['Cron', 'Postgres', 'Web services'],
    capabilityLabel: 'PaaS + cron host',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'render',
    recentlyAdded: true,
  },
  {
    id: 'digitalocean',
    label: 'DigitalOcean',
    icon: 'DO',
    color: '#0080FF',
    group: 'ops_infra',
    description: 'Droplets, App Platform, Managed DBs, and Spaces object storage for cost-conscious side projects.',
    relationships: ['Droplets', 'Spaces', 'Managed DBs'],
    capabilityLabel: 'Cloud hosting + storage',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'digitalocean',
    recentlyAdded: true,
  },
  {
    id: 'supabase',
    label: 'Supabase',
    icon: 'SB',
    color: '#3ECF8E',
    group: 'data_search',
    description: 'Postgres + auth + storage + realtime — run SQL, manage RLS policies, and read storage buckets directly.',
    relationships: ['Postgres', 'Auth', 'Realtime'],
    capabilityLabel: 'Postgres backend',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'supabase',
    recentlyAdded: true,
  },
  {
    id: 'neon',
    label: 'Neon',
    icon: 'NEO',
    color: '#00E599',
    group: 'data_search',
    description: 'Serverless Postgres with branching — branch the prod DB for a PR, run migrations, drop on merge.',
    relationships: ['Postgres', 'PR previews', 'Migrations'],
    capabilityLabel: 'Serverless Postgres',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'neon',
    recentlyAdded: true,
  },
  {
    id: 'mongodb-atlas',
    label: 'MongoDB Atlas',
    icon: 'MDB',
    color: '#13AA52',
    group: 'data_search',
    description: 'Managed MongoDB — query collections, check index health, and run aggregations on demand.',
    relationships: ['NoSQL', 'Mongo', 'Aggregations'],
    capabilityLabel: 'Managed MongoDB',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'mongodb_atlas',
    recentlyAdded: true,
  },
  {
    id: 'upstash',
    label: 'Upstash',
    icon: 'UPS',
    color: '#00E9A3',
    group: 'data_search',
    description: 'Serverless Redis, Kafka, and Vector — read/write cache, inspect queue depth without a Redis client.',
    relationships: ['Redis', 'Kafka', 'Vector'],
    capabilityLabel: 'Serverless Redis + queues',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'upstash',
    recentlyAdded: true,
  },
  {
    id: 'hugging-face',
    label: 'Hugging Face',
    icon: 'HF',
    color: '#FFD21E',
    group: 'ai_agents_services',
    description: 'Models, datasets, Spaces, Inference Endpoints — pull a fine-tuned model card and deploy as an endpoint.',
    relationships: ['Models', 'Datasets', 'Inference'],
    capabilityLabel: 'Model + dataset hub',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'hugging_face',
    recentlyAdded: true,
    popularityRank: 13,
  },
  {
    id: 'replicate',
    label: 'Replicate',
    icon: 'RPL',
    color: '#000000',
    group: 'ai_agents_services',
    description: 'Hosted model inference for generative tasks — run an image/video model from a prompt and attach the result.',
    relationships: ['Image gen', 'Video gen', 'OSS models'],
    capabilityLabel: 'Generative model API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'replicate',
    recentlyAdded: true,
    // Pinned to the bottom of the popularity sort by request — Replicate
    // is more useful for image/video generation than chat, so it shouldn't
    // dominate the chat-LLM picker even though it lives in the same group.
    popularityRank: 999,
  },
  {
    id: 'modal',
    label: 'Modal',
    icon: 'MDL',
    color: '#7C3AED',
    group: 'ai_agents_services',
    description: 'Serverless Python on GPU/CPU — ship a function and call it from agent runs without managing infra.',
    relationships: ['GPU', 'Serverless', 'Python'],
    capabilityLabel: 'Serverless GPU jobs',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'modal',
    recentlyAdded: true,
    popularityRank: 24,
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    icon: 'OR',
    color: '#6366F1',
    group: 'ai_agents_services',
    description: '100+ LLMs through one API — A/B a prompt across Claude, GPT, Gemini, and OSS models in a single call.',
    relationships: ['Multi-model', 'Routing', 'A/B prompts'],
    capabilityLabel: 'Unified LLM router',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'openrouter',
    recentlyAdded: true,
    popularityRank: 4,
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    icon: 'A',
    color: '#D97706',
    group: 'ai_agents_services',
    description: 'Claude Opus / Sonnet / Haiku direct from Anthropic. Bring your own key to bill on your account instead of the platform.',
    relationships: ['Claude Opus', 'Claude Sonnet', 'Claude Haiku'],
    capabilityLabel: 'Native Anthropic API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'anthropic',
    recentlyAdded: true,
    popularityRank: 1,
  },
  {
    id: 'openai',
    label: 'OpenAI',
    icon: 'O',
    color: '#10A37F',
    group: 'ai_agents_services',
    description: 'GPT-5 / GPT-4o / o4 reasoning direct from OpenAI. BYOK so requests bill against your OpenAI account.',
    relationships: ['GPT-5', 'GPT-4o', 'o4 reasoning'],
    capabilityLabel: 'Native OpenAI API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'openai',
    recentlyAdded: true,
    popularityRank: 2,
  },
  {
    id: 'google-ai',
    label: 'Google AI',
    icon: 'G',
    color: '#4285F4',
    group: 'ai_agents_services',
    description: 'Gemini 2.5 Pro / Flash via Google AI Studio. Long-context and multimodal directly from Google.',
    relationships: ['Gemini 2.5 Pro', 'Gemini 2.5 Flash', 'Multimodal'],
    capabilityLabel: 'Native Gemini API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'google_ai',
    recentlyAdded: true,
    popularityRank: 6,
  },
  {
    id: 'groq',
    label: 'Groq',
    icon: 'GQ',
    color: '#F97316',
    group: 'ai_agents_services',
    description: 'Ultra-fast Llama / Mixtral inference on LPU hardware. Sub-second latency for chat-heavy workloads.',
    relationships: ['Llama 3.3', 'Mixtral', 'Sub-second latency'],
    capabilityLabel: 'High-speed inference',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'groq',
    recentlyAdded: true,
    popularityRank: 7,
  },
  {
    id: 'mistral-ai',
    label: 'Mistral AI',
    icon: 'MS',
    color: '#FA520F',
    group: 'ai_agents_services',
    description: 'Mistral Large / Codestral / Pixtral direct from Mistral. Strong Europe-hosted alternative for code + chat.',
    relationships: ['Mistral Large', 'Codestral', 'Pixtral'],
    capabilityLabel: 'Native Mistral API',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'mistral_ai',
    recentlyAdded: true,
    popularityRank: 16,
  },
  {
    id: 'cohere',
    label: 'Cohere',
    icon: 'CH',
    color: '#39594D',
    group: 'ai_agents_services',
    description: 'Command R+ chat + Embed v3 + Rerank. Strong for retrieval-augmented agents and enterprise use cases.',
    relationships: ['Command R+', 'Embed v3', 'Rerank'],
    capabilityLabel: 'Chat + embeddings + rerank',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'cohere',
    recentlyAdded: true,
    popularityRank: 19,
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    icon: 'PX',
    color: '#1FB8CD',
    group: 'ai_agents_services',
    description: 'Sonar models with built-in web search. Citations come back inline so chat can ground answers in live sources.',
    relationships: ['Sonar', 'Web search', 'Citations'],
    capabilityLabel: 'Search-grounded chat',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'perplexity',
    recentlyAdded: true,
    popularityRank: 17,
  },
  {
    id: 'together-ai',
    label: 'Together AI',
    icon: 'TG',
    color: '#0F6FFF',
    group: 'ai_agents_services',
    description: 'OSS frontier models (Llama, Qwen, DeepSeek) on managed inference. Cheap and fast for high-volume chat.',
    relationships: ['Llama', 'Qwen', 'DeepSeek'],
    capabilityLabel: 'OSS model hosting',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'together_ai',
    recentlyAdded: true,
    popularityRank: 18,
  },
  {
    id: 'fireworks-ai',
    label: 'Fireworks AI',
    icon: 'FW',
    color: '#5B36BD',
    group: 'ai_agents_services',
    description: 'Production OSS inference with FireFunction tool calling. Optimised for low-latency function-call agents.',
    relationships: ['FireFunction', 'OSS hosting', 'Tool calling'],
    capabilityLabel: 'Function-tuned OSS hosting',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'fireworks_ai',
    recentlyAdded: true,
    popularityRank: 21,
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    icon: 'DS',
    color: '#1A6FE0',
    group: 'ai_agents_services',
    description: 'DeepSeek R1 reasoning + V3 chat. Strong reasoning at OSS prices, ideal for code review and planning.',
    relationships: ['DeepSeek R1', 'DeepSeek V3', 'Reasoning'],
    capabilityLabel: 'Reasoning + chat',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'deepseek',
    recentlyAdded: true,
    popularityRank: 12,
  },
  {
    id: 'z-ai',
    label: 'Z.AI / GLM',
    icon: 'Z',
    color: '#0EA5E9',
    group: 'ai_agents_services',
    description: 'GLM-4 / GLM-4.5 chat from Zhipu / Z.AI. Multilingual coverage and strong on reasoning benchmarks.',
    relationships: ['GLM-4', 'GLM-4.5', 'Multilingual'],
    capabilityLabel: 'GLM chat models',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'z_ai',
    recentlyAdded: true,
    popularityRank: 22,
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    icon: 'MX',
    color: '#EC4899',
    group: 'ai_agents_services',
    description: 'MiniMax-Text + Speech 2.5. Long-context chat with strong Chinese / multilingual coverage.',
    relationships: ['MiniMax-Text', 'Speech 2.5', 'Long context'],
    capabilityLabel: 'Multilingual chat + speech',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'minimax',
    recentlyAdded: true,
    popularityRank: 23,
  },
  {
    id: 'ollama',
    label: 'Ollama (Local)',
    icon: 'OL',
    color: '#5B21B6',
    group: 'ai_agents_services',
    description: 'Run open models locally — Llama, Qwen, DeepSeek. Point at the Ollama URL on your machine; no cloud API key required.',
    relationships: ['Local', 'Llama', 'Qwen'],
    capabilityLabel: 'Local model runtime',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'ollama',
    recentlyAdded: true,
    popularityRank: 20,
  },
  {
    id: 'linear',
    label: 'Linear',
    icon: 'LIN',
    color: '#5E6AD2',
    group: 'workflow_automation',
    description: 'Issue tracker for modern dev teams — create issues from chat and update status when a PR merges.',
    relationships: ['Issues', 'Cycles', 'Roadmap'],
    capabilityLabel: 'Issue tracker',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'linear',
    recentlyAdded: true,
    popularityRank: 11,
  },
  {
    id: 'jira',
    label: 'Jira',
    icon: 'JIR',
    color: '#0052CC',
    group: 'workflow_automation',
    description: 'Sprint and issue management for larger teams — pull sprint state and surface blockers in chat.',
    relationships: ['Sprints', 'Issues', 'Confluence'],
    capabilityLabel: 'Issue + sprint management',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'jira',
    recentlyAdded: true,
  },
  {
    id: 'snyk',
    label: 'Snyk',
    icon: 'SNY',
    color: '#4C4A73',
    group: 'observability_security',
    description: 'Vulnerability scanning for code, deps, containers, and IaC — triage CVEs and open fix PRs automatically.',
    relationships: ['CVE triage', 'SCA', 'Container scan'],
    capabilityLabel: 'Security scanning',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'snyk',
    recentlyAdded: true,
  },
  {
    id: 'clerk',
    label: 'Clerk',
    icon: 'CLK',
    color: '#6C47FF',
    group: 'auth_identity',
    description: 'Drop-in auth UI — provision test users with specific roles for E2E tests and read session state.',
    relationships: ['Auth', 'SSO', 'Sessions'],
    capabilityLabel: 'Drop-in auth UI',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'clerk',
    recentlyAdded: true,
  },
  {
    id: 'postmark',
    label: 'Postmark',
    icon: 'PMK',
    color: '#FFDE00',
    group: 'workflow_automation',
    description: 'Transactional email known for deliverability — send tests and inspect bounce reasons from agent runs.',
    relationships: ['Transactional email', 'Deliverability', 'Bounces'],
    capabilityLabel: 'Transactional email',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'postmark',
    recentlyAdded: true,
  },
  {
    id: 'cloudflare-r2',
    label: 'Cloudflare R2',
    icon: 'R2',
    color: '#F38020',
    group: 'ops_infra',
    description: 'S3-compatible object storage with no egress fees — store agent artifacts cheaply and serve via Workers.',
    relationships: ['Object storage', 'Workers', 'CDN'],
    capabilityLabel: 'Object storage',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'cloudflare_r2',
    recentlyAdded: true,
  },
  {
    id: 'qdrant',
    label: 'Qdrant',
    icon: 'QDR',
    color: '#DC382D',
    group: 'data_search',
    description: 'Rust-based vector DB with strong filter performance — store agent memories with rich metadata filters.',
    relationships: ['Vector', 'RAG', 'Memory'],
    capabilityLabel: 'Vector DB + filters',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'qdrant',
    recentlyAdded: true,
  },
  {
    id: 'ngrok',
    label: 'ngrok',
    icon: 'NGR',
    color: '#1F1E37',
    group: 'workflow_automation',
    description: 'Public tunnels for local dev and webhooks — expose a local agent endpoint to receive a webhook.',
    relationships: ['Tunnels', 'Webhooks', 'Local dev'],
    capabilityLabel: 'Public tunnels',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'ngrok',
    recentlyAdded: true,
  },
  {
    id: 'trigger-dev',
    label: 'Trigger.dev',
    icon: 'TRG',
    color: '#A8FF53',
    group: 'workflow_automation',
    description: 'Background jobs purpose-built for AI workflows — enqueue durable agent jobs that survive restarts.',
    relationships: ['Background jobs', 'AI workflows', 'Webhooks'],
    capabilityLabel: 'Durable background jobs',
    scopeLabel: 'Circle-wide',
    availability: 'available',
    platformKey: 'trigger_dev',
    recentlyAdded: true,
  },
];

export function getCatalogItemsForGroup(group: CircleIntegrationGroupKey): CircleIntegrationCatalogItem[] {
  return CIRCLE_INTEGRATION_CATALOG.filter(item => item.group === group);
}
