import type { ResearchDocument } from './researchKnowledge';

const CIVIL_SPIRIT_ID = 'civil-engineer';
const CIVIL_SKILL_BUNDLE = 'civileng-design-codes-and-field-judgment';

export function getBuiltInCivilEngineeringResearchDocuments(): ResearchDocument[] {
  const commonMetadata = {
    relevant_spirits: [CIVIL_SPIRIT_ID],
    source_family: 'civil-engineering-builtins',
  };

  return [
    {
      id: 'builtin-civil-licensure-and-disciplines',
      title: 'Civil Licensure And Discipline Scope',
      summary: 'Senior civil guidance should track the current FE-to-PE path and the main PE Civil depth domains: construction, geotechnical, structural, transportation, and water resources/environmental.',
      content: [
        'Use FE/PE framing to separate entry-level fundamentals from professional-practice judgment.',
        'The SOUL should think across five recurring civil domains: construction, geotechnical, structural, transportation, and water resources/environmental.',
        'When structural authority, jurisdictional adoption, or sealed design is in question, escalate to local licensed review instead of pretending the issue is generic.',
      ].join('\n'),
      tags: ['civil', 'licensure', 'pe', 'fe', 'discipline-scope', CIVIL_SPIRIT_ID, CIVIL_SKILL_BUNDLE],
      source_type: 'guideline',
      source_title: 'NCEES / ASCE civil practice framing',
      source_url: 'https://ncees.org/exams/pe-exam/civil/',
      authors: ['The Underground Circle'],
      publication_date: '2026-04-16',
      review_status: 'reviewed',
      evidence_score: 0.9,
      visibility: 'public',
      is_active: true,
      domain_key: 'civil_infrastructure',
      metadata: commonMetadata,
    },
    {
      id: 'builtin-civil-field-and-lab-tests',
      title: 'Civil Field And Lab Test Matrix',
      summary: 'Senior civil review should always map discipline questions to site characterization, earthwork acceptance, concrete QA, foundation verification, drainage observations, and survey control.',
      content: [
        'Site characterization: borings, test pits, SPT, CPT where available, and groundwater observations.',
        'Earthwork control: classification, Atterberg/sieve context, moisture-density relationships, proof rolling, and in-place density acceptance.',
        'Concrete QA/QC: slump, air, temperature, cylinders, curing, placement observations, and cover/tolerance concerns.',
        'Foundation/specialty work: pile records, load testing, drilled shaft cleanliness and integrity controls, and settlement/performance monitoring.',
        'Survey/layout: benchmarks, control, staking tolerance, as-builts, and conflict reconciliation.',
      ].join('\n'),
      tags: ['civil', 'qa-qc', 'testing', 'geotechnical', 'earthwork', 'concrete', 'survey', CIVIL_SPIRIT_ID, CIVIL_SKILL_BUNDLE],
      source_type: 'report',
      source_title: 'Built-in Civil QA/QC Reference',
      source_url: 'https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06089.pdf',
      authors: ['The Underground Circle'],
      publication_date: '2026-04-16',
      review_status: 'reviewed',
      evidence_score: 0.88,
      visibility: 'public',
      is_active: true,
      domain_key: 'civil_infrastructure',
      metadata: commonMetadata,
    },
    {
      id: 'builtin-civil-structural-materials-stack',
      title: 'Civil Structural And Materials Reference Stack',
      summary: 'Civil structural answers should identify the governing load path, material family, detailing constraints, durability exposure, and owner/code edition before sounding final.',
      content: [
        'Structural civil work usually sits on a stack of load criteria, material standards, and owner/jurisdiction requirements.',
        'Default reference families include ASCE 7 load concepts, ACI concrete practice, AISC steel practice, and AASHTO owner standards when bridge/highway work is involved.',
        'Strong senior review distinguishes strength, serviceability, durability, inspection access, and constructability instead of giving one undifferentiated answer.',
      ].join('\n'),
      tags: ['civil', 'structural', 'materials', 'loads', 'aci', 'aisc', 'aashto', CIVIL_SPIRIT_ID, CIVIL_SKILL_BUNDLE],
      source_type: 'guideline',
      source_title: 'Built-in Structural Materials Stack',
      source_url: 'https://www.aisc.org/aisc/publications/current-standards/',
      authors: ['The Underground Circle'],
      publication_date: '2026-04-16',
      review_status: 'reviewed',
      evidence_score: 0.84,
      visibility: 'public',
      is_active: true,
      domain_key: 'civil_infrastructure',
      metadata: commonMetadata,
    },
    {
      id: 'builtin-civil-drainage-and-permitting',
      title: 'Civil Drainage, Stormwater, And Permit Logic',
      summary: 'Senior civil drainage work should connect hydrology assumptions, conveyance/storage intent, erosion control, outfall stability, and permit-driven inspection requirements.',
      content: [
        'Drainage answers should state drainage area assumptions, design storm/criteria, flow path, allowable headwater or storage intent, and downstream/outfall implications.',
        'Stormwater and construction-phase answers should account for SWPPP logic, erosion and sediment controls, dewatering constraints, and inspection documentation where applicable.',
        'For culverts and highway drainage, FHWA guidance should inform inlet/outlet behavior, velocities, scour, debris, and maintenance implications.',
      ].join('\n'),
      tags: ['civil', 'drainage', 'stormwater', 'erosion-control', 'culvert', 'permitting', CIVIL_SPIRIT_ID, CIVIL_SKILL_BUNDLE],
      source_type: 'guideline',
      source_title: 'Built-in Drainage And Permitting Reference',
      source_url: 'https://www.fhwa.dot.gov/engineering/hydraulics/highwaydrain/',
      authors: ['The Underground Circle'],
      publication_date: '2026-04-16',
      review_status: 'reviewed',
      evidence_score: 0.87,
      visibility: 'public',
      is_active: true,
      domain_key: 'civil_infrastructure',
      metadata: commonMetadata,
    },
    {
      id: 'builtin-civil-safety-and-construction-controls',
      title: 'Civil Construction Safety And Control Points',
      summary: 'Temporary works, excavation, traffic control, dewatering, and field nonconformance are safety-critical and should trigger stronger escalation behavior than generic design discussion.',
      content: [
        'Excavation and trenching should be treated as safety-critical and tied to competent-person requirements, temporary support logic, and changing site conditions.',
        'Traffic control changes should be handled as public-safety issues, not just plan markup requests.',
        'Nonconformances should be documented with issue, governing requirement, field risk, recommended disposition, and closeout evidence.',
      ].join('\n'),
      tags: ['civil', 'construction', 'safety', 'traffic-control', 'excavation', 'field-issues', CIVIL_SPIRIT_ID, CIVIL_SKILL_BUNDLE],
      source_type: 'guideline',
      source_title: 'Built-in Construction Safety Controls',
      source_url: 'https://www.osha.gov/etools/construction/trenching/competent-person',
      authors: ['The Underground Circle'],
      publication_date: '2026-04-16',
      review_status: 'reviewed',
      evidence_score: 0.89,
      visibility: 'public',
      is_active: true,
      domain_key: 'civil_infrastructure',
      metadata: commonMetadata,
    },
  ];
}
