/**
 * desktopBridge — UC-side client for the Claude Code bridge's
 * desktop-automation endpoints (Phase 1a — see
 * `docs/DESKTOP_AUTOMATION_PHASE_1_PLAN.md`).
 *
 * Usage from an agent tool / chat action:
 *
 *   if (!(await isDesktopBridgeAvailable())) { ... }
 *   await pairDesktopBridge(); // first time only
 *   await launchApp('Zoom');
 *   await pressKeys('Cmd+N');
 *   await typeText('Chris');
 *
 * All calls return `{ ok, error?, errorCode?, data? }` — no throws at
 * the boundary (matches the rest of our lib posture).
 */

import {
  parseKeyCombo,
  isValidAppName,
  validateDesktopUrl,
  validateDesktopPath,
  validateClickCoords,
  type DesktopBridgeError,
  type DesktopResult,
  type DesktopHealth,
} from './desktopBridgeProtocol';

export type { DesktopBridgeError, DesktopResult, DesktopHealth } from './desktopBridgeProtocol';

const BRIDGE_URL = 'http://localhost:7778';
export const BRIDGE_HEALTH_URL = `${BRIDGE_URL}/desktop/health`;
const TOKEN_KEY = 'uc_desktop_bridge_token_v1';

// ─── Availability probe ────────────────────────────────────────────────────

export async function isDesktopBridgeAvailable(): Promise<boolean> {
  try {
    const res = await fetch(`${BRIDGE_URL}/desktop/health`, { cache: 'no-store' });
    if (!res.ok) return false;
    const json = (await res.json()) as DesktopHealth;
    return !!json?.supported;
  } catch {
    return false;
  }
}

export async function getDesktopBridgeHealth(): Promise<DesktopHealth | null> {
  try {
    const res = await fetch(`${BRIDGE_URL}/desktop/health`, { cache: 'no-store' });
    if (!res.ok) return null;
    return (await res.json()) as DesktopHealth;
  } catch {
    return null;
  }
}

// ─── Token storage ────────────────────────────────────────────────────────
//
// The web client caches the paired token in localStorage. It's
// intentionally plain-text on disk (same trust level as any other
// localStorage secret we hold — session cookies, BYO API keys) because
// the token is only useful against a bridge running on THIS machine,
// and any attacker with disk access can read ~/.uc-desktop-token
// directly anyway.

function readToken(): string | null {
  try {
    if (typeof localStorage === 'undefined') return null;
    return localStorage.getItem(TOKEN_KEY);
  } catch {
    return null;
  }
}

function writeToken(value: string) {
  try {
    if (typeof localStorage !== 'undefined') localStorage.setItem(TOKEN_KEY, value);
  } catch {
    /* quota / private-mode — caller proceeds without persistence */
  }
}

export function clearDesktopBridgeToken(): void {
  try {
    if (typeof localStorage !== 'undefined') localStorage.removeItem(TOKEN_KEY);
  } catch {}
}

/**
 * Returns cached token status so the UI can render chips and so agent
 * tool wrappers can short-circuit without hitting the network.
 */
export function isDesktopBridgePaired(): boolean {
  const t = readToken();
  return !!t && t.length >= 32;
}

/**
 * Best-effort "make sure we're paired" used by every write-path helper.
 * If the bridge is reachable and supported and we don't have a token
 * yet, silently calls `pairDesktopBridge()`. No user prompt — the
 * bridge binds to localhost only and a same-origin fetch is the same
 * trust boundary as the user's own shell. On any failure the caller
 * surfaces the original error to the user.
 */
export async function ensureDesktopBridgePaired(): Promise<DesktopResult<{ token: string; autoPaired: boolean }>> {
  const cached = readToken();
  if (cached && cached.length >= 32) {
    return { ok: true, data: { token: cached, autoPaired: false } };
  }
  const health = await getDesktopBridgeHealth();
  if (!health) {
    return { ok: false, error: 'bridge_offline', errorCode: 'bridge_offline' };
  }
  if (!health.supported) {
    return { ok: false, error: 'platform_unsupported', errorCode: 'platform_unsupported' };
  }
  const paired = await pairDesktopBridge();
  if (!paired.ok) return paired as DesktopResult<{ token: string; autoPaired: boolean }>;
  return { ok: true, data: { token: paired.data!.token, autoPaired: true } };
}

// ─── Pairing ───────────────────────────────────────────────────────────────

/**
 * One-time handshake with the local bridge. Reads the shared token from
 * `~/.uc-desktop-token` (generated by the bridge on first start) and
 * caches it in `localStorage`. Call once per device.
 */
export async function pairDesktopBridge(): Promise<DesktopResult<{ token: string }>> {
  try {
    const res = await fetch(`${BRIDGE_URL}/desktop/pair`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: '{}',
    });
    if (!res.ok) {
      return failFromStatus(res.status, await safeText(res)) as DesktopResult<{ token: string }>;
    }
    const json = (await res.json()) as { ok: boolean; token?: string; error?: string };
    if (!json.ok || !json.token) {
      return { ok: false, error: json.error || 'pairing response missing token', errorCode: 'unknown' };
    }
    writeToken(json.token);
    return { ok: true, data: { token: json.token } };
  } catch (err: any) {
    return { ok: false, error: err?.message || 'bridge unreachable', errorCode: 'bridge_offline' };
  }
}

// ─── Desktop actions ───────────────────────────────────────────────────────

export async function listRunningApps(): Promise<DesktopResult<string[]>> {
  const r = await callBridge('GET', '/desktop/running-apps');
  if (!r.ok) return r as DesktopResult<string[]>;
  return { ok: true, data: ((r.data as any)?.apps as string[]) || [] };
}

export async function launchApp(appName: string): Promise<DesktopResult<{ appName: string }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName (letters/numbers/space/.-_() only)', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/launch', { appName });
  if (!r.ok) return r as DesktopResult<{ appName: string }>;
  return { ok: true, data: { appName: (r.data as any)?.appName || appName } };
}

export async function focusApp(appName: string): Promise<DesktopResult<{ appName: string }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/focus', { appName });
  if (!r.ok) return r as DesktopResult<{ appName: string }>;
  return { ok: true, data: { appName: (r.data as any)?.appName || appName } };
}

export async function typeText(text: string): Promise<DesktopResult<{ chars: number }>> {
  if (typeof text !== 'string' || text.length === 0) {
    return { ok: false, error: 'text must be a non-empty string', errorCode: 'invalid_input' };
  }
  if (text.length > 4000) {
    return { ok: false, error: 'text too long (max 4000 chars per call)', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/type', { text });
  if (!r.ok) return r as DesktopResult<{ chars: number }>;
  return { ok: true, data: { chars: (r.data as any)?.chars ?? text.length } };
}

/** Phase 1c — waits until `appName` shows up in the running-app list.
 *  Replaces the old `sleep(1200)` race in auto-chain — we start typing
 *  only after the app has rendered its first window. */
export async function waitForApp(
  appName: string,
  timeoutMs?: number,
): Promise<DesktopResult<{ appName: string; elapsedMs: number }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName', errorCode: 'invalid_input' };
  }
  const body: Record<string, unknown> = { appName };
  if (typeof timeoutMs === 'number') body.timeoutMs = timeoutMs;
  const r = await callBridge('POST', '/desktop/wait_for_app', body);
  if (!r.ok) return r as DesktopResult<{ appName: string; elapsedMs: number }>;
  // Bridge returns `{ ok: false, error: 'timeout', appName, waitedMs }`
  // as a 200 — callBridge normalised it. We re-project onto the
  // typed shape with the elapsedMs it gave us.
  const d = r.data as any;
  return { ok: true, data: { appName: d?.appName || appName, elapsedMs: Number(d?.elapsedMs ?? 0) } };
}

/** Phase 1c — full-screen screenshot as a base64 PNG data URL. Lets
 *  the agent verify what happened after a destructive tool call. */
export async function takeScreenshot(): Promise<DesktopResult<{ base64: string; mimeType: string; sizeBytes: number; dataUrl: string }>> {
  const r = await callBridge('GET', '/desktop/screenshot');
  if (!r.ok) return r as DesktopResult<{ base64: string; mimeType: string; sizeBytes: number; dataUrl: string }>;
  const d = r.data as any;
  const base64 = String(d?.base64 || '');
  const mimeType = String(d?.mimeType || 'image/png');
  const sizeBytes = Number(d?.sizeBytes ?? 0);
  if (!base64) {
    return { ok: false, error: 'bridge returned empty screenshot payload', errorCode: 'unknown' };
  }
  return {
    ok: true,
    data: { base64, mimeType, sizeBytes, dataUrl: `data:${mimeType};base64,${base64}` },
  };
}

/** Phase 1d — opens a URL in the user's default browser via `open`.
 *  Validated client-side + server-side; accepts http / https / file /
 *  mailto schemes. */
export async function openUrl(rawUrl: string): Promise<DesktopResult<{ url: string; scheme: string }>> {
  const v = validateDesktopUrl(rawUrl);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/open_url', { url: v.url });
  if (!r.ok) return r as DesktopResult<{ url: string; scheme: string }>;
  const d = r.data as any;
  return { ok: true, data: { url: d?.url || v.url, scheme: d?.scheme || v.scheme } };
}

/** Phase 1d — `open <path>` in the default app. Path must not contain
 *  shell metacharacters. */
export async function openPath(rawPath: string): Promise<DesktopResult<{ path: string }>> {
  const v = validateDesktopPath(rawPath);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/open_path', { path: v.path });
  if (!r.ok) {
    // Surface `path_not_found` as a typed errorCode so callers can
    // choose a better fallback than a generic HTTP 400.
    if (String(r.error || '').includes('path_not_found')) {
      return { ok: false, error: 'File or folder does not exist at that path.', errorCode: 'app_not_found' };
    }
    return r as DesktopResult<{ path: string }>;
  }
  return { ok: true, data: { path: (r.data as any)?.path || v.path } };
}

/** Phase 1d — mouse click at absolute screen coords. Uses cliclick when
 *  installed (accurate), falls back to AppleScript otherwise (best-
 *  effort). The health response's `optional.cliclick` flag tells clients
 *  whether to try at all. */
export async function clickAt(x: number, y: number): Promise<DesktopResult<{ x: number; y: number; via: string }>> {
  const v = validateClickCoords(x, y);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/click_at', { x: v.x, y: v.y });
  if (!r.ok) return r as DesktopResult<{ x: number; y: number; via: string }>;
  const d = r.data as any;
  return { ok: true, data: { x: d?.x ?? v.x, y: d?.y ?? v.y, via: d?.via || 'unknown' } };
}

/** Phase 1d — returns the primary screen resolution so callers can
 *  bound click coordinates before sending them. */
export async function getScreenSize(): Promise<DesktopResult<{ width: number; height: number }>> {
  const r = await callBridge('GET', '/desktop/screen_size');
  if (!r.ok) return r as DesktopResult<{ width: number; height: number }>;
  const d = r.data as any;
  return { ok: true, data: { width: Number(d?.width || 0), height: Number(d?.height || 0) } };
}

export async function pressKeys(combo: string): Promise<DesktopResult<{ combo: string }>> {
  const parsed = parseKeyCombo(combo);
  if (!parsed.ok) {
    return { ok: false, error: parsed.error, errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/keys', { combo });
  if (!r.ok) return r as DesktopResult<{ combo: string }>;
  return { ok: true, data: { combo: (r.data as any)?.combo || combo } };
}

// ─── Internals ────────────────────────────────────────────────────────────

async function callBridge(
  method: 'GET' | 'POST',
  pathname: string,
  body?: Record<string, unknown>,
): Promise<DesktopResult> {
  let token = readToken();
  // Auto-pair on first call — the bridge binds to localhost so a same-
  // origin fetch is the same trust boundary as the user's own shell.
  // Saves the user an explicit "Pair Desktop Bridge" tap on fresh
  // installs. No-op if already paired.
  if (!token) {
    const ensured = await ensureDesktopBridgePaired();
    if (!ensured.ok) return ensured;
    token = ensured.data!.token;
  }
  try {
    const res = await fetch(`${BRIDGE_URL}${pathname}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        'X-UC-Desktop-Token': token,
      },
      body: method === 'POST' ? JSON.stringify(body || {}) : undefined,
    });
    if (!res.ok) return failFromStatus(res.status, await safeText(res));
    const json = (await res.json()) as { ok?: boolean; error?: string; [k: string]: unknown };
    if (!json.ok) {
      return {
        ok: false,
        error: json.error || `bridge returned ok:false`,
        errorCode: mapBodyErrorToCode(json.error),
      };
    }
    return { ok: true, data: json };
  } catch (err: any) {
    return { ok: false, error: err?.message || 'bridge unreachable', errorCode: 'bridge_offline' };
  }
}

function failFromStatus(status: number, bodyText: string): DesktopResult {
  if (status === 401) return { ok: false, error: 'Desktop token rejected — re-pair.', errorCode: 'not_paired' };
  if (status === 403) return { ok: false, error: 'Origin blocked by bridge.', errorCode: 'origin_blocked' };
  if (status === 501) return { ok: false, error: 'Bridge is on a platform that does not support desktop automation.', errorCode: 'platform_unsupported' };
  if (status === 400) {
    const parsed = tryParseJsonError(bodyText);
    return { ok: false, error: parsed || 'bad request', errorCode: mapBodyErrorToCode(parsed || '') };
  }
  return { ok: false, error: bodyText || `HTTP ${status}`, errorCode: 'unknown' };
}

function mapBodyErrorToCode(err: string | undefined | null): DesktopBridgeError {
  const m = String(err || '').toLowerCase();
  if (m.includes('app_not_found') || m.includes('not found')) return 'app_not_found';
  if (m.includes('not allowed') || m.includes('permission')) return 'permission_denied';
  if (m.includes('timed out')) return 'timeout';
  if (m.includes('invalid')) return 'invalid_input';
  return 'unknown';
}

function tryParseJsonError(bodyText: string): string | null {
  try {
    const parsed = JSON.parse(bodyText);
    if (parsed && typeof parsed.error === 'string') return parsed.error;
  } catch {}
  return null;
}

async function safeText(res: Response): Promise<string> {
  try { return await res.text(); } catch { return ''; }
}
