/**
 * desktopBridge — UC-side client for the Claude Code bridge's
 * desktop-automation endpoints (Phase 1a — see
 * `docs/DESKTOP_AUTOMATION_PHASE_1_PLAN.md`).
 *
 * Usage from an agent tool / chat action:
 *
 *   if (!(await isDesktopBridgeAvailable())) { ... }
 *   await pairDesktopBridge(); // first time only
 *   await launchApp('Zoom');
 *   await pressKeys('Cmd+N');
 *   await typeText('Chris');
 *
 * All calls return `{ ok, error?, errorCode?, data? }` — no throws at
 * the boundary (matches the rest of our lib posture).
 */

import {
  parseKeyCombo,
  isValidAppName,
  validateDesktopUrl,
  validateDesktopPath,
  validateClickCoords,
  type DesktopBridgeError,
  type DesktopResult,
  type DesktopHealth,
} from './desktopBridgeProtocol';
import { getBridgeUrl } from './bridgeEnvironment';

export type { DesktopBridgeError, DesktopResult, DesktopHealth } from './desktopBridgeProtocol';

const BRIDGE_PORT = 7778;
export const BRIDGE_HEALTH_URL = 'http://localhost:7778/desktop/health';
const TOKEN_KEY = 'uc_desktop_bridge_token_v1';

export function getDesktopBridgeBaseUrl(): string | null {
  return getBridgeUrl(BRIDGE_PORT);
}

export function getDesktopBridgeHealthUrl(): string | null {
  const base = getDesktopBridgeBaseUrl();
  return base ? `${base}/desktop/health` : null;
}

// ─── Availability probe ────────────────────────────────────────────────────

export async function isDesktopBridgeAvailable(): Promise<boolean> {
  const base = getDesktopBridgeBaseUrl();
  if (!base) return false;
  try {
    const res = await fetch(`${base}/desktop/health`, { cache: 'no-store' });
    if (!res.ok) return false;
    const json = (await res.json()) as DesktopHealth;
    return !!json?.supported;
  } catch {
    return false;
  }
}

export async function getDesktopBridgeHealth(): Promise<DesktopHealth | null> {
  const base = getDesktopBridgeBaseUrl();
  if (!base) return null;
  try {
    const res = await fetch(`${base}/desktop/health`, { cache: 'no-store' });
    if (!res.ok) return null;
    return (await res.json()) as DesktopHealth;
  } catch {
    return null;
  }
}

// ─── Token storage ────────────────────────────────────────────────────────
//
// The web client caches the paired token in localStorage. It's
// intentionally plain-text on disk (same trust level as any other
// localStorage secret we hold — session cookies, BYO API keys) because
// the token is only useful against a bridge running on THIS machine,
// and any attacker with disk access can read ~/.uc-desktop-token
// directly anyway.

function readToken(): string | null {
  try {
    if (typeof localStorage === 'undefined') return null;
    return localStorage.getItem(TOKEN_KEY);
  } catch {
    return null;
  }
}

function writeToken(value: string) {
  try {
    if (typeof localStorage !== 'undefined') localStorage.setItem(TOKEN_KEY, value);
  } catch {
    /* quota / private-mode — caller proceeds without persistence */
  }
}

export function clearDesktopBridgeToken(): void {
  try {
    if (typeof localStorage !== 'undefined') localStorage.removeItem(TOKEN_KEY);
  } catch {}
}

/**
 * Returns cached token status so the UI can render chips and so agent
 * tool wrappers can short-circuit without hitting the network.
 */
export function isDesktopBridgePaired(): boolean {
  const t = readToken();
  return !!t && t.length >= 32;
}

/**
 * Best-effort "make sure we're paired" used by every write-path helper.
 * If the bridge is reachable and supported and we don't have a token
 * yet, silently calls `pairDesktopBridge()`. No user prompt — the
 * bridge binds to localhost only and a same-origin fetch is the same
 * trust boundary as the user's own shell. On any failure the caller
 * surfaces the original error to the user.
 */
export async function ensureDesktopBridgePaired(): Promise<DesktopResult<{ token: string; autoPaired: boolean }>> {
  const cached = readToken();
  if (cached && cached.length >= 32) {
    return { ok: true, data: { token: cached, autoPaired: false } };
  }
  const health = await getDesktopBridgeHealth();
  if (!health) {
    return { ok: false, error: 'bridge_offline', errorCode: 'bridge_offline' };
  }
  if (!health.supported) {
    return { ok: false, error: 'platform_unsupported', errorCode: 'platform_unsupported' };
  }
  const paired = await pairDesktopBridge();
  if (!paired.ok) return paired as DesktopResult<{ token: string; autoPaired: boolean }>;
  return { ok: true, data: { token: paired.data!.token, autoPaired: true } };
}

// ─── Pairing ───────────────────────────────────────────────────────────────

/**
 * One-time handshake with the local bridge. Reads the shared token from
 * `~/.uc-desktop-token` (generated by the bridge on first start) and
 * caches it in `localStorage`. Call once per device.
 */
export async function pairDesktopBridge(): Promise<DesktopResult<{ token: string }>> {
  const base = getDesktopBridgeBaseUrl();
  if (!base) {
    return { ok: false, error: 'bridge unavailable in this environment', errorCode: 'bridge_offline' };
  }
  try {
    const res = await fetch(`${base}/desktop/pair`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: '{}',
    });
    if (!res.ok) {
      return failFromStatus(res.status, await safeText(res)) as DesktopResult<{ token: string }>;
    }
    const json = (await res.json()) as { ok: boolean; token?: string; error?: string };
    if (!json.ok || !json.token) {
      return { ok: false, error: json.error || 'pairing response missing token', errorCode: 'unknown' };
    }
    writeToken(json.token);
    return { ok: true, data: { token: json.token } };
  } catch (err: any) {
    return { ok: false, error: err?.message || 'bridge unreachable', errorCode: 'bridge_offline' };
  }
}

// ─── Desktop actions ───────────────────────────────────────────────────────

export async function listRunningApps(): Promise<DesktopResult<string[]>> {
  const r = await callBridge('GET', '/desktop/running-apps');
  if (!r.ok) return r as DesktopResult<string[]>;
  return { ok: true, data: ((r.data as any)?.apps as string[]) || [] };
}

export type DesktopBrowserTab = {
  browser: string;
  title: string;
  url: string;
};

export async function listBrowserTabs(browsers?: string[]): Promise<DesktopResult<{ tabs: DesktopBrowserTab[]; errors: string[] }>> {
  const query = browsers && browsers.length > 0 ? `?browsers=${encodeURIComponent(browsers.join(','))}` : '';
  const r = await callBridge('GET', `/desktop/browser_tabs${query}`);
  if (!r.ok) return r as DesktopResult<{ tabs: DesktopBrowserTab[]; errors: string[] }>;
  const d = r.data as any;
  return {
    ok: true,
    data: {
      tabs: Array.isArray(d?.tabs) ? d.tabs : [],
      errors: Array.isArray(d?.errors) ? d.errors : [],
    },
  };
}

export type DesktopWindowState = {
  frontmostApp: string;
  activeWindowTitle: string;
  activeWindowBounds: { x: number; y: number; width: number; height: number } | null;
  windows: string[];
};

export async function getWindowState(): Promise<DesktopResult<DesktopWindowState>> {
  const r = await callBridge('GET', '/desktop/window_state');
  if (!r.ok) return r as DesktopResult<DesktopWindowState>;
  const d = r.data as any;
  return {
    ok: true,
    data: {
      frontmostApp: String(d?.frontmostApp || ''),
      activeWindowTitle: String(d?.activeWindowTitle || ''),
      activeWindowBounds: d?.activeWindowBounds || null,
      windows: Array.isArray(d?.windows) ? d.windows : [],
    },
  };
}

export async function readClipboard(): Promise<DesktopResult<{ text: string; chars: number; truncated: boolean }>> {
  const r = await callBridge('GET', '/desktop/clipboard');
  if (!r.ok) return r as DesktopResult<{ text: string; chars: number; truncated: boolean }>;
  const d = r.data as any;
  return { ok: true, data: { text: String(d?.text || ''), chars: Number(d?.chars || 0), truncated: Boolean(d?.truncated) } };
}

export async function writeClipboard(text: string): Promise<DesktopResult<{ chars: number }>> {
  if (typeof text !== 'string') return { ok: false, error: 'text must be a string', errorCode: 'invalid_input' };
  if (text.length > 4000) return { ok: false, error: 'text too long (max 4000 chars)', errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/clipboard_write', { text });
  if (!r.ok) return r as DesktopResult<{ chars: number }>;
  return { ok: true, data: { chars: Number((r.data as any)?.chars ?? text.length) } };
}

export async function clearClipboard(): Promise<DesktopResult<Record<string, never>>> {
  const r = await callBridge('POST', '/desktop/clipboard_clear', {});
  if (!r.ok) return r as DesktopResult<Record<string, never>>;
  return { ok: true, data: {} };
}

export type DesktopFileEntry = {
  name: string;
  path: string;
  kind: 'file' | 'directory' | 'other';
  size: number | null;
  modifiedAt: string | null;
};

export async function listFiles(rawPath: string): Promise<DesktopResult<{ path: string; entries: DesktopFileEntry[]; truncated: boolean }>> {
  const v = validateDesktopPath(rawPath);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('GET', `/desktop/file_list?path=${encodeURIComponent(v.path)}`);
  if (!r.ok) return r as DesktopResult<{ path: string; entries: DesktopFileEntry[]; truncated: boolean }>;
  const d = r.data as any;
  return { ok: true, data: { path: String(d?.path || v.path), entries: Array.isArray(d?.entries) ? d.entries : [], truncated: Boolean(d?.truncated) } };
}

export async function readFile(rawPath: string, maxBytes?: number): Promise<DesktopResult<{ path: string; content: string; size: number; truncated: boolean }>> {
  const v = validateDesktopPath(rawPath);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const params = new URLSearchParams({ path: v.path });
  if (typeof maxBytes === 'number') params.set('maxBytes', String(maxBytes));
  const r = await callBridge('GET', `/desktop/file_read?${params.toString()}`);
  if (!r.ok) return r as DesktopResult<{ path: string; content: string; size: number; truncated: boolean }>;
  const d = r.data as any;
  return {
    ok: true,
    data: { path: String(d?.path || v.path), content: String(d?.content || ''), size: Number(d?.size || 0), truncated: Boolean(d?.truncated) },
  };
}

export type DesktopFileSearchMatch = {
  path: string;
  name: string;
  reason: 'name' | 'content';
  size: number;
  modifiedAt: string;
  snippet?: string;
};

export async function searchFiles(rootPath: string, query: string): Promise<DesktopResult<{ rootPath: string; query: string; matches: DesktopFileSearchMatch[]; visited: number; truncated: boolean }>> {
  const v = validateDesktopPath(rootPath);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const q = String(query || '').trim();
  if (!q || q.length > 120) return { ok: false, error: 'query is required and must be <= 120 chars', errorCode: 'invalid_input' };
  const params = new URLSearchParams({ rootPath: v.path, query: q });
  const r = await callBridge('GET', `/desktop/file_search?${params.toString()}`);
  if (!r.ok) return r as DesktopResult<{ rootPath: string; query: string; matches: DesktopFileSearchMatch[]; visited: number; truncated: boolean }>;
  const d = r.data as any;
  return {
    ok: true,
    data: {
      rootPath: String(d?.rootPath || v.path),
      query: String(d?.query || q),
      matches: Array.isArray(d?.matches) ? d.matches : [],
      visited: Number(d?.visited || 0),
      truncated: Boolean(d?.truncated),
    },
  };
}

export async function listShortcuts(): Promise<DesktopResult<string[]>> {
  const r = await callBridge('GET', '/desktop/shortcuts/list');
  if (!r.ok) return r as DesktopResult<string[]>;
  return { ok: true, data: Array.isArray((r.data as any)?.shortcuts) ? (r.data as any).shortcuts : [] };
}

export async function runShortcut(name: string): Promise<DesktopResult<{ name: string; output: string }>> {
  const clean = String(name || '').trim();
  if (!clean || clean.length > 120) return { ok: false, error: 'shortcut name is required and must be <= 120 chars', errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/shortcuts/run', { name: clean });
  if (!r.ok) return r as DesktopResult<{ name: string; output: string }>;
  return { ok: true, data: { name: String((r.data as any)?.name || clean), output: String((r.data as any)?.output || '') } };
}

export async function manageWindow(args: {
  action: 'focus' | 'raise' | 'minimize' | 'unminimize' | 'zoom' | 'resize';
  appName?: string;
  width?: number;
  height?: number;
}): Promise<DesktopResult<{ action: string; appName: string | null; width: number | null; height: number | null }>> {
  const r = await callBridge('POST', '/desktop/window_manage', args as Record<string, unknown>);
  if (!r.ok) return r as DesktopResult<{ action: string; appName: string | null; width: number | null; height: number | null }>;
  const d = r.data as any;
  return { ok: true, data: { action: String(d?.action || args.action), appName: d?.appName || null, width: d?.width ?? null, height: d?.height ?? null } };
}

export async function mouseMove(x: number, y: number): Promise<DesktopResult<{ x: number; y: number }>> {
  const v = validateClickCoords(x, y);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/mouse_move', { x: v.x, y: v.y });
  if (!r.ok) return r as DesktopResult<{ x: number; y: number }>;
  const d = r.data as any;
  return { ok: true, data: { x: Number(d?.x ?? v.x), y: Number(d?.y ?? v.y) } };
}

export async function mouseClick(args: {
  x: number;
  y: number;
  button?: 'left' | 'right';
  count?: number;
}): Promise<DesktopResult<{ x: number; y: number; button: string; count: number }>> {
  const v = validateClickCoords(args.x, args.y);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const button = args.button === 'right' ? 'right' : 'left';
  const count = Math.max(1, Math.min(3, Math.trunc(Number(args.count || 1))));
  const r = await callBridge('POST', '/desktop/mouse_click', { x: v.x, y: v.y, button, count });
  if (!r.ok) return r as DesktopResult<{ x: number; y: number; button: string; count: number }>;
  const d = r.data as any;
  return { ok: true, data: { x: Number(d?.x ?? v.x), y: Number(d?.y ?? v.y), button: String(d?.button || button), count: Number(d?.count || count) } };
}

export async function mouseDrag(args: {
  fromX: number;
  fromY: number;
  toX: number;
  toY: number;
  durationMs?: number;
}): Promise<DesktopResult<{ fromX: number; fromY: number; toX: number; toY: number; durationMs: number }>> {
  const start = validateClickCoords(args.fromX, args.fromY);
  if (!start.ok) return { ok: false, error: start.error, errorCode: 'invalid_input' };
  const end = validateClickCoords(args.toX, args.toY);
  if (!end.ok) return { ok: false, error: end.error, errorCode: 'invalid_input' };
  const durationMs = Math.max(50, Math.min(5000, Math.trunc(Number(args.durationMs || 450))));
  const r = await callBridge('POST', '/desktop/mouse_drag', { fromX: start.x, fromY: start.y, toX: end.x, toY: end.y, durationMs });
  if (!r.ok) return r as DesktopResult<{ fromX: number; fromY: number; toX: number; toY: number; durationMs: number }>;
  const d = r.data as any;
  return {
    ok: true,
    data: {
      fromX: Number(d?.fromX ?? start.x),
      fromY: Number(d?.fromY ?? start.y),
      toX: Number(d?.toX ?? end.x),
      toY: Number(d?.toY ?? end.y),
      durationMs: Number(d?.durationMs || durationMs),
    },
  };
}

export async function mouseScroll(args: { deltaY?: number; deltaX?: number; x?: number; y?: number } = {}): Promise<DesktopResult<{ x: number; y: number; deltaX: number; deltaY: number }>> {
  const r = await callBridge('POST', '/desktop/mouse_scroll', args as Record<string, unknown>);
  if (!r.ok) return r as DesktopResult<{ x: number; y: number; deltaX: number; deltaY: number }>;
  const d = r.data as any;
  return { ok: true, data: { x: Number(d?.x || 0), y: Number(d?.y || 0), deltaX: Number(d?.deltaX || 0), deltaY: Number(d?.deltaY || 0) } };
}

export async function launchApp(appName: string): Promise<DesktopResult<{ appName: string }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName (letters/numbers/space/.-_() only)', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/launch', { appName });
  if (!r.ok) return r as DesktopResult<{ appName: string }>;
  return { ok: true, data: { appName: (r.data as any)?.appName || appName } };
}

export async function focusApp(appName: string): Promise<DesktopResult<{ appName: string }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/focus', { appName });
  if (!r.ok) return r as DesktopResult<{ appName: string }>;
  return { ok: true, data: { appName: (r.data as any)?.appName || appName } };
}

export async function typeText(text: string): Promise<DesktopResult<{ chars: number }>> {
  if (typeof text !== 'string' || text.length === 0) {
    return { ok: false, error: 'text must be a non-empty string', errorCode: 'invalid_input' };
  }
  if (text.length > 4000) {
    return { ok: false, error: 'text too long (max 4000 chars per call)', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/type', { text });
  if (!r.ok) return r as DesktopResult<{ chars: number }>;
  return { ok: true, data: { chars: (r.data as any)?.chars ?? text.length } };
}

/** Phase 1c — waits until `appName` shows up in the running-app list.
 *  Replaces the old `sleep(1200)` race in auto-chain — we start typing
 *  only after the app has rendered its first window. */
export async function waitForApp(
  appName: string,
  timeoutMs?: number,
): Promise<DesktopResult<{ appName: string; elapsedMs: number }>> {
  if (!isValidAppName(appName)) {
    return { ok: false, error: 'Invalid appName', errorCode: 'invalid_input' };
  }
  const body: Record<string, unknown> = { appName };
  if (typeof timeoutMs === 'number') body.timeoutMs = timeoutMs;
  const r = await callBridge('POST', '/desktop/wait_for_app', body);
  if (!r.ok) return r as DesktopResult<{ appName: string; elapsedMs: number }>;
  // Bridge returns `{ ok: false, error: 'timeout', appName, waitedMs }`
  // as a 200 — callBridge normalised it. We re-project onto the
  // typed shape with the elapsedMs it gave us.
  const d = r.data as any;
  return { ok: true, data: { appName: d?.appName || appName, elapsedMs: Number(d?.elapsedMs ?? 0) } };
}

/** Phase 1c — full-screen screenshot as a base64 PNG data URL. Lets
 *  the agent verify what happened after a destructive tool call. */
export async function takeScreenshot(): Promise<DesktopResult<{ base64: string; mimeType: string; sizeBytes: number; dataUrl: string }>> {
  const r = await callBridge('GET', '/desktop/screenshot');
  if (!r.ok) return r as DesktopResult<{ base64: string; mimeType: string; sizeBytes: number; dataUrl: string }>;
  const d = r.data as any;
  const base64 = String(d?.base64 || '');
  const mimeType = String(d?.mimeType || 'image/png');
  const sizeBytes = Number(d?.sizeBytes ?? 0);
  if (!base64) {
    return { ok: false, error: 'bridge returned empty screenshot payload', errorCode: 'unknown' };
  }
  return {
    ok: true,
    data: { base64, mimeType, sizeBytes, dataUrl: `data:${mimeType};base64,${base64}` },
  };
}

/** Phase 1d — opens a URL in the user's default browser via `open`.
 *  Validated client-side + server-side; accepts http / https / file /
 *  mailto schemes. */
export async function openUrl(rawUrl: string): Promise<DesktopResult<{ url: string; scheme: string }>> {
  const v = validateDesktopUrl(rawUrl);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/open_url', { url: v.url });
  if (!r.ok) return r as DesktopResult<{ url: string; scheme: string }>;
  const d = r.data as any;
  return { ok: true, data: { url: d?.url || v.url, scheme: d?.scheme || v.scheme } };
}

/** Phase 1d — `open <path>` in the default app. Path must not contain
 *  shell metacharacters. */
export async function openPath(rawPath: string): Promise<DesktopResult<{ path: string }>> {
  const v = validateDesktopPath(rawPath);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/open_path', { path: v.path });
  if (!r.ok) {
    // Surface `path_not_found` as a typed errorCode so callers can
    // choose a better fallback than a generic HTTP 400.
    if (String(r.error || '').includes('path_not_found')) {
      return { ok: false, error: 'File or folder does not exist at that path.', errorCode: 'app_not_found' };
    }
    return r as DesktopResult<{ path: string }>;
  }
  return { ok: true, data: { path: (r.data as any)?.path || v.path } };
}

/** Phase 1d — mouse click at absolute screen coords. Uses cliclick when
 *  installed (accurate), falls back to AppleScript otherwise (best-
 *  effort). The health response's `optional.cliclick` flag tells clients
 *  whether to try at all. */
export async function clickAt(x: number, y: number): Promise<DesktopResult<{ x: number; y: number; via: string }>> {
  const v = validateClickCoords(x, y);
  if (!v.ok) return { ok: false, error: v.error, errorCode: 'invalid_input' };
  const r = await callBridge('POST', '/desktop/click_at', { x: v.x, y: v.y });
  if (!r.ok) return r as DesktopResult<{ x: number; y: number; via: string }>;
  const d = r.data as any;
  return { ok: true, data: { x: d?.x ?? v.x, y: d?.y ?? v.y, via: d?.via || 'unknown' } };
}

/** Phase 1d — returns the primary screen resolution so callers can
 *  bound click coordinates before sending them. */
export async function getScreenSize(): Promise<DesktopResult<{ width: number; height: number }>> {
  const r = await callBridge('GET', '/desktop/screen_size');
  if (!r.ok) return r as DesktopResult<{ width: number; height: number }>;
  const d = r.data as any;
  return { ok: true, data: { width: Number(d?.width || 0), height: Number(d?.height || 0) } };
}

// ─── UC-1: accessibility tree ────────────────────────────────────────────
//
// A11y-tree-grounded automation is ~75% cheaper per step than
// screenshot-grounded because a pruned tree fits in ~400 tokens vs
// ~1,500 for an XGA screenshot, and selectors ("role=button
// label='Send'") survive window resizes / theme changes / retina mixes
// that break pixel coordinates. Backed by the Swift helper at
// scripts/bin/uc-ax-helper which walks AXUIElement.

export interface A11yNode {
  id: string;                     // dotted path from root, e.g. "0.2.1"
  role: string;                   // AX role, e.g. "AXButton"
  label?: string;                 // title / description / identifier
  value?: string;                 // state (text-field contents etc.)
  bbox?: [number, number, number, number]; // [x, y, w, h] in screen coords
  children?: A11yNode[];
}

export interface A11yTreeResult {
  app: string;                    // frontmost app name or requested appName
  pid: number;                    // used for click_element path resolution
  budget_used: number;            // nodes walked before the maxNodes cap
  tree: A11yNode;
}

/**
 * Read the accessibility tree for a named app (or the frontmost app
 * when `appName` is omitted). The returned tree is pruned: layout
 * scaffolding without labels is elided, deeply-nested unaddressable
 * leaves are dropped, and a node budget keeps the payload under ~400
 * tokens for typical app windows.
 *
 * Returns `helper_missing` when the Swift helper binary isn't compiled
 * yet — callers should fall back to the vision path.
 */
export async function readA11yTree(args: {
  appName?: string;
  maxDepth?: number;
  maxNodes?: number;
} = {}): Promise<DesktopResult<A11yTreeResult>> {
  const params = new URLSearchParams();
  if (args.appName) params.set('app', args.appName);
  if (typeof args.maxDepth === 'number') params.set('max_depth', String(args.maxDepth));
  if (typeof args.maxNodes === 'number') params.set('max_nodes', String(args.maxNodes));
  const qs = params.toString();
  const r = await callBridge('GET', `/desktop/a11y_tree${qs ? `?${qs}` : ''}`);
  if (!r.ok) {
    // The bridge returns 503 when the helper binary isn't compiled
    // yet. Normalise that into a specific error code so callers can
    // fall back to screenshot grounding without guessing from text.
    const looksMissing = /not compiled|xcode-select/i.test(r.error || '');
    return {
      ok: false,
      error: r.error || 'a11y tree unavailable',
      errorCode: looksMissing ? 'helper_missing' : (r.errorCode || 'unknown'),
    } as DesktopResult<A11yTreeResult>;
  }
  const d = r.data as any;
  if (!d?.tree) {
    return { ok: false, error: 'bridge returned empty a11y payload', errorCode: 'unknown' };
  }
  return {
    ok: true,
    data: {
      app: String(d.app || args.appName || ''),
      pid: Number(d.pid || 0),
      budget_used: Number(d.budget_used || 0),
      tree: d.tree as A11yNode,
    },
  };
}

/**
 * Click an element by its dotted path (as returned from readA11yTree).
 * `pid` must match the PID the tree was fetched from — element paths
 * are only meaningful within their source process. The helper tries
 * AXPress first (native accessibility click) and falls back to a
 * synthesised CGEvent at the bbox centre for elements that don't
 * implement Press.
 */
export async function clickElement(args: { pid: number; path: string }): Promise<DesktopResult<{ method: string }>> {
  if (!args.pid || args.pid <= 0) {
    return { ok: false, error: 'pid required', errorCode: 'invalid_input' };
  }
  if (!args.path || !/^[0-9]+(\.[0-9]+)*$/.test(args.path)) {
    return { ok: false, error: 'path must be a dotted integer sequence', errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/click_element', { pid: args.pid, path: args.path });
  if (!r.ok) return r as DesktopResult<{ method: string }>;
  const d = r.data as any;
  return { ok: true, data: { method: String(d?.method || 'unknown') } };
}

/**
 * Flatten a pruned tree into a list of addressable nodes + a compact
 * rendering suitable for LLM consumption (one line per node, indented
 * by depth). Kept as a pure helper so both the client dispatcher and
 * smoke tests can format the same way.
 */
export function renderA11yTree(node: A11yNode, depth = 0, out: string[] = []): string[] {
  const indent = '  '.repeat(depth);
  const parts = [`${indent}[${node.id}]`, node.role];
  if (node.label) parts.push(`"${node.label.replace(/"/g, '\\"').slice(0, 120)}"`);
  if (node.value && node.value !== node.label) parts.push(`= "${node.value.replace(/"/g, '\\"').slice(0, 80)}"`);
  out.push(parts.join(' '));
  for (const child of node.children || []) {
    renderA11yTree(child, depth + 1, out);
  }
  return out;
}

export async function pressKeys(combo: string): Promise<DesktopResult<{ combo: string }>> {
  const parsed = parseKeyCombo(combo);
  if (!parsed.ok) {
    return { ok: false, error: parsed.error, errorCode: 'invalid_input' };
  }
  const r = await callBridge('POST', '/desktop/keys', { combo });
  if (!r.ok) return r as DesktopResult<{ combo: string }>;
  return { ok: true, data: { combo: (r.data as any)?.combo || combo } };
}

// ─── Internals ────────────────────────────────────────────────────────────

async function callBridge(
  method: 'GET' | 'POST',
  pathname: string,
  body?: Record<string, unknown>,
): Promise<DesktopResult> {
  let token = readToken();
  // Auto-pair on first call — the bridge binds to localhost so a same-
  // origin fetch is the same trust boundary as the user's own shell.
  // Saves the user an explicit "Pair Desktop Bridge" tap on fresh
  // installs. No-op if already paired.
  if (!token) {
    const ensured = await ensureDesktopBridgePaired();
    if (!ensured.ok) return ensured;
    token = ensured.data!.token;
  }
  try {
    const base = getDesktopBridgeBaseUrl();
    if (!base) {
      return { ok: false, error: 'bridge unavailable in this environment', errorCode: 'bridge_offline' };
    }
    const res = await fetch(`${base}${pathname}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        'X-UC-Desktop-Token': token,
      },
      body: method === 'POST' ? JSON.stringify(body || {}) : undefined,
    });
    if (!res.ok) return failFromStatus(res.status, await safeText(res));
    const json = (await res.json()) as { ok?: boolean; error?: string; [k: string]: unknown };
    if (!json.ok) {
      return {
        ok: false,
        error: json.error || `bridge returned ok:false`,
        errorCode: mapBodyErrorToCode(json.error),
      };
    }
    return { ok: true, data: json };
  } catch (err: any) {
    return { ok: false, error: err?.message || 'bridge unreachable', errorCode: 'bridge_offline' };
  }
}

function failFromStatus(status: number, bodyText: string): DesktopResult {
  if (status === 401) return { ok: false, error: 'Desktop token rejected — re-pair.', errorCode: 'not_paired' };
  if (status === 403) return { ok: false, error: 'Origin blocked by bridge.', errorCode: 'origin_blocked' };
  if (status === 501) return { ok: false, error: 'Bridge is on a platform that does not support desktop automation.', errorCode: 'platform_unsupported' };
  if (status === 400) {
    const parsed = tryParseJsonError(bodyText);
    return { ok: false, error: parsed || 'bad request', errorCode: mapBodyErrorToCode(parsed || '') };
  }
  return { ok: false, error: bodyText || `HTTP ${status}`, errorCode: 'unknown' };
}

function mapBodyErrorToCode(err: string | undefined | null): DesktopBridgeError {
  const m = String(err || '').toLowerCase();
  if (m.includes('app_not_found') || m.includes('not found')) return 'app_not_found';
  if (m.includes('not allowed') || m.includes('permission')) return 'permission_denied';
  if (m.includes('timed out')) return 'timeout';
  if (m.includes('invalid')) return 'invalid_input';
  return 'unknown';
}

function tryParseJsonError(bodyText: string): string | null {
  try {
    const parsed = JSON.parse(bodyText);
    if (parsed && typeof parsed.error === 'string') return parsed.error;
  } catch {}
  return null;
}

async function safeText(res: Response): Promise<string> {
  try { return await res.text(); } catch { return ''; }
}
