export interface MarketplaceAppDetail {
  usedBySouls: string[];
  unlocks: string[];
  exampleTasks: string[];
  relatedItemIds?: string[];
}

export const MARKETPLACE_APP_DETAILS: Record<string, MarketplaceAppDetail> = {
  'openswan-runtime': {
    usedBySouls: ['AI Researcher', 'Engineer', 'DevOps', 'QA'],
    unlocks: ['coding runtime control', 'subagent orchestration', 'session-driven execution'],
    exampleTasks: ['debug a failing build', 'run a migration plan', 'delegate browser automation to an agent'],
    relatedItemIds: ['browserbase', 'stagehand', 'playwright-mcp'],
  },
  browserbase: {
    usedBySouls: ['QA', 'Support', 'Growth', 'DevOps'],
    unlocks: ['durable browser sessions', 'web workflow automation', 'UI regression flows'],
    exampleTasks: ['log into a dashboard and verify a funnel', 'run a browser QA checklist', 'capture remote web state for an agent'],
    relatedItemIds: ['stagehand', 'hyperbrowser', 'browserless'],
  },
  stagehand: {
    usedBySouls: ['QA', 'Support', 'Growth', 'Engineer'],
    unlocks: ['natural-language browser actions', 'self-healing browser flows', 'Playwright-compatible agent recipes'],
    exampleTasks: ['complete a multi-step web form', 'verify a user flow with AI actions', 'turn a browser task into a reusable recipe'],
    relatedItemIds: ['browserbase', 'playwright-mcp', 'openswan-runtime'],
  },
  'playwright-mcp': {
    usedBySouls: ['Engineer', 'QA', 'DevOps'],
    unlocks: ['DOM-aware browser control', 'screenshots and snapshots', 'repeatable browser test generation'],
    exampleTasks: ['inspect a broken UI state', 'generate an e2e test from an agent session', 'debug selectors before launch'],
    relatedItemIds: ['stagehand', 'browserstack', 'browserless'],
  },
  browserless: {
    usedBySouls: ['QA', 'Engineer', 'Researcher', 'Ops'],
    unlocks: ['headless browser jobs', 'screenshots and PDFs', 'scripted scraping without full agent sessions'],
    exampleTasks: ['capture a landing page screenshot', 'render a PDF from a customer page', 'scrape JavaScript-heavy content cheaply'],
    relatedItemIds: ['browserbase', 'firecrawl', 'playwright-mcp'],
  },
  browserstack: {
    usedBySouls: ['QA', 'Engineer', 'PM'],
    unlocks: ['real-browser QA', 'real-device validation', 'release recordings and visual checks'],
    exampleTasks: ['test checkout on Safari iOS', 'validate a browser matrix before launch', 'record a failing mobile browser session'],
    relatedItemIds: ['playwright-mcp', 'sentry', 'posthog'],
  },
  firecrawl: {
    usedBySouls: ['Researcher', 'AI Researcher', 'Writer', 'SEO'],
    unlocks: ['clean markdown extraction', 'site crawls', 'structured web data for RAG'],
    exampleTasks: ['crawl a competitor site into markdown', 'extract pricing pages for research', 'build a source corpus for an agent'],
    relatedItemIds: ['apify', 'pinecone', 'knowledge'],
  },
  apify: {
    usedBySouls: ['Researcher', 'Data Engineer', 'Growth', 'Ops'],
    unlocks: ['web automation Actors', 'scheduled crawls', 'structured scraping datasets'],
    exampleTasks: ['run a product research Actor', 'schedule a lead-data crawl', 'export scraped results into a workflow'],
    relatedItemIds: ['firecrawl', 'browserless', 'pinecone'],
  },
  steel: {
    usedBySouls: ['Engineer', 'DevOps', 'QA'],
    unlocks: ['open browser fleets', 'cloud browser session control', 'custom browser-agent infrastructure'],
    exampleTasks: ['spin up controlled browser sessions', 'test a custom browser-agent backend', 'route OpenSwan web tasks through an open API'],
    relatedItemIds: ['hyperbrowser', 'browserbase', 'openswan-runtime'],
  },
  hyperbrowser: {
    usedBySouls: ['Engineer', 'QA', 'Researcher', 'Ops'],
    unlocks: ['scalable cloud browsers', 'Browser Use task execution', 'managed browser sessions for agents'],
    exampleTasks: ['run parallel browser research jobs', 'execute a Browser Use task in the cloud', 'scale web automation without local browser load'],
    relatedItemIds: ['browser-use', 'steel', 'browserbase'],
  },
  airtop: {
    usedBySouls: ['Support', 'Ops', 'Growth', 'QA'],
    unlocks: ['AI-controlled cloud browsing', 'managed browser profiles', 'natural-language browser actions'],
    exampleTasks: ['operate a customer portal with a managed browser profile', 'fill a recurring web form', 'let an agent browse a SaaS dashboard like a user'],
    relatedItemIds: ['skyvern', 'browserbase', 'openswan-runtime'],
  },
  skyvern: {
    usedBySouls: ['Ops', 'Support', 'QA', 'Finance'],
    unlocks: ['vision-guided browser workflows', 'authenticated dashboard automation', 'repeatable form and portal operations'],
    exampleTasks: ['submit vendor portal updates', 'operate a back-office dashboard', 'automate a login-heavy workflow with human approval'],
    relatedItemIds: ['airtop', 'browser-use', 'browserbase'],
  },
  'browser-use': {
    usedBySouls: ['Engineer', 'Researcher', 'Ops'],
    unlocks: ['self-hosted browser agents', 'LLM-driven web navigation', 'lower-control-cost browser task runners'],
    exampleTasks: ['run an open-source browser agent', 'test a local web automation strategy', 'prototype browser tasks before moving them to cloud infrastructure'],
    relatedItemIds: ['hyperbrowser', 'skyvern', 'stagehand'],
  },
  braintrust: {
    usedBySouls: ['AI Researcher', 'Engineer', 'QA'],
    unlocks: ['eval tracking', 'prompt regressions', 'agent quality scoring'],
    exampleTasks: ['compare two prompt strategies', 'monitor agent quality drift', 'evaluate research workflows'],
    relatedItemIds: ['openswan-runtime', 'posthog'],
  },
  github: {
    usedBySouls: ['Engineer', 'DevOps', 'QA', 'PM'],
    unlocks: ['repo access', 'PR workflows', 'issue tracking'],
    exampleTasks: ['open a PR', 'review code changes', 'triage a failing issue'],
    relatedItemIds: ['vercel', 'netlify', 'sentry'],
  },
  vercel: {
    usedBySouls: ['Engineer', 'DevOps', 'Designer', 'Growth'],
    unlocks: ['preview deploys', 'frontend releases', 'domain-linked shipping'],
    exampleTasks: ['ship a landing page update', 'inspect a preview deployment', 'roll out a frontend fix'],
    relatedItemIds: ['github', 'cloudflare', 'launchdarkly'],
  },
  netlify: {
    usedBySouls: ['Engineer', 'DevOps', 'Growth'],
    unlocks: ['static site deploys', 'preview builds', 'site delivery'],
    exampleTasks: ['publish a static microsite', 'deploy a marketing page', 'manage site previews'],
    relatedItemIds: ['github', 'cloudflare'],
  },
  wordpress: {
    usedBySouls: ['Writer', 'Marketer', 'SEO', 'PM'],
    unlocks: ['CMS publishing', 'page updates', 'editorial workflows'],
    exampleTasks: ['publish a blog post', 'update a service page', 'schedule a content draft'],
    relatedItemIds: ['google-analytics', 'search-console', 'resend-email'],
  },
  'google-analytics': {
    usedBySouls: ['Marketer', 'Growth', 'PM', 'Analyst'],
    unlocks: ['traffic reporting', 'funnel visibility', 'conversion analysis'],
    exampleTasks: ['audit a landing page funnel', 'report weekly acquisition performance', 'analyze campaign conversions'],
    relatedItemIds: ['search-console', 'posthog', 'google-ads'],
  },
  'search-console': {
    usedBySouls: ['SEO', 'Writer', 'Marketer'],
    unlocks: ['search visibility', 'indexing insight', 'technical SEO health'],
    exampleTasks: ['inspect indexing issues', 'analyze top search queries', 'review page performance in search'],
    relatedItemIds: ['google-analytics', 'wordpress', 'algolia'],
  },
  algolia: {
    usedBySouls: ['Engineer', 'Writer', 'PM'],
    unlocks: ['site search', 'query analytics', 'discovery workflows'],
    exampleTasks: ['improve docs search', 'index a content collection', 'analyze zero-result queries'],
    relatedItemIds: ['knowledge', 'wordpress', 'pinecone'],
  },
  pinecone: {
    usedBySouls: ['AI Researcher', 'Engineer', 'Knowledge'],
    unlocks: ['semantic retrieval', 'memory search', 'RAG indexing'],
    exampleTasks: ['index a research corpus', 'store embeddings', 'power semantic recall for Souls'],
    relatedItemIds: ['knowledge', 'braintrust', 'openswan-runtime'],
  },
  cloudflare: {
    usedBySouls: ['DevOps', 'Engineer', 'Security'],
    unlocks: ['DNS control', 'edge rules', 'cache and redirect management'],
    exampleTasks: ['cut over a domain migration', 'update DNS records', 'purge cache after a release'],
    relatedItemIds: ['vercel', 'netlify', 'hosting'],
  },
  hosting: {
    usedBySouls: ['DevOps', 'Engineer'],
    unlocks: ['infra access', 'storage', 'email and CDN operations'],
    exampleTasks: ['configure SES', 'manage an S3 bucket', 'handle Route 53 cutover'],
    relatedItemIds: ['cloudflare', 'sentry', 'datadog'],
  },
  launchdarkly: {
    usedBySouls: ['PM', 'Engineer', 'Growth'],
    unlocks: ['feature flags', 'guarded rollouts', 'experiments'],
    exampleTasks: ['roll out a feature gradually', 'gate a risky release', 'run a launch experiment'],
    relatedItemIds: ['posthog', 'vercel'],
  },
  posthog: {
    usedBySouls: ['Growth', 'PM', 'Analyst'],
    unlocks: ['product analytics', 'funnels', 'experiments'],
    exampleTasks: ['analyze product funnels', 'measure experiment impact', 'review feature adoption'],
    relatedItemIds: ['launchdarkly', 'google-analytics', 'sentry'],
  },
  sentry: {
    usedBySouls: ['Engineer', 'DevOps', 'QA'],
    unlocks: ['error triage', 'performance visibility', 'release issue tracking'],
    exampleTasks: ['triage a production error', 'inspect performance regressions', 'verify a release fix'],
    relatedItemIds: ['datadog', 'github', 'hosting'],
  },
  datadog: {
    usedBySouls: ['DevOps', 'Engineer', 'Security'],
    unlocks: ['logs', 'metrics', 'monitoring and alerts'],
    exampleTasks: ['investigate service latency', 'review infrastructure logs', 'configure monitors'],
    relatedItemIds: ['sentry', 'hosting', 'cloudflare'],
  },
  'resend-email': {
    usedBySouls: ['Marketer', 'PM', 'Support'],
    unlocks: ['transactional email', 'notifications', 'approval flows'],
    exampleTasks: ['send approval emails', 'dispatch notifications', 'wire transactional messaging'],
    relatedItemIds: ['crm', 'mailchimp', 'convertkit'],
  },
  crm: {
    usedBySouls: ['Sales', 'Marketer', 'PM'],
    unlocks: ['contact and deal management', 'pipeline workflows', 'revenue operations'],
    exampleTasks: ['update a deal stage', 'sync contacts', 'track a campaign lead lifecycle'],
    relatedItemIds: ['mailchimp', 'convertkit', 'payments'],
  },
  salesforce: {
    usedBySouls: ['Sales', 'RevOps', 'PM'],
    unlocks: ['enterprise CRM ownership', 'account and opportunity workflows', 'revenue reporting'],
    exampleTasks: ['update enterprise opportunities', 'sync account notes', 'review sales pipeline movement'],
    relatedItemIds: ['mailchimp', 'payments'],
  },
  pipedrive: {
    usedBySouls: ['Sales', 'RevOps'],
    unlocks: ['lean CRM ownership', 'deal pipeline control', 'contact workflows'],
    exampleTasks: ['move a deal through stages', 'update contact records', 'review outbound pipeline health'],
    relatedItemIds: ['mailchimp', 'payments'],
  },
  mailchimp: {
    usedBySouls: ['Marketer', 'Growth', 'Writer'],
    unlocks: ['audience campaigns', 'email automation', 'campaign reporting'],
    exampleTasks: ['send a newsletter campaign', 'segment an audience', 'review open and click performance'],
    relatedItemIds: ['crm', 'convertkit', 'google-analytics'],
  },
  convertkit: {
    usedBySouls: ['Writer', 'Growth', 'Creator'],
    unlocks: ['creator email funnels', 'broadcasts', 'audience automation'],
    exampleTasks: ['send a creator broadcast', 'build a lead funnel', 'manage subscriber automation'],
    relatedItemIds: ['mailchimp', 'crm'],
  },
  payments: {
    usedBySouls: ['Finance', 'PM', 'Sales'],
    unlocks: ['subscriptions', 'billing workflows', 'revenue operations'],
    exampleTasks: ['review subscription state', 'handle invoice operations', 'analyze payment issues'],
    relatedItemIds: ['crm', 'shopify'],
  },
  shopify: {
    usedBySouls: ['Marketer', 'Ops', 'Sales'],
    unlocks: ['storefront operations', 'product management', 'order workflows'],
    exampleTasks: ['update a product catalog', 'review order issues', 'manage ecommerce flows'],
    relatedItemIds: ['payments', 'mailchimp'],
  },
  figma: {
    usedBySouls: ['Designer', 'PM', 'Engineer'],
    unlocks: ['design references', 'asset review', 'handoff workflows'],
    exampleTasks: ['inspect a design file', 'review UI handoff', 'trace asset usage'],
    relatedItemIds: ['knowledge', 'cloudinary'],
  },
  knowledge: {
    usedBySouls: ['PM', 'Writer', 'Researcher'],
    unlocks: ['docs', 'briefs', 'SOPs', 'knowledge operations'],
    exampleTasks: ['update an SOP', 'maintain planning docs', 'organize research notes'],
    relatedItemIds: ['algolia', 'pinecone', 'figma'],
  },
  cloudinary: {
    usedBySouls: ['Designer', 'Marketer', 'Writer'],
    unlocks: ['media transformations', 'asset delivery', 'image-heavy pipelines'],
    exampleTasks: ['optimize marketing images', 'deliver transformed assets', 'manage CMS media flows'],
    relatedItemIds: ['figma', 'wordpress', 'mux'],
  },
  mux: {
    usedBySouls: ['Marketer', 'Creator', 'Designer'],
    unlocks: ['video ingestion', 'streaming', 'playback analytics'],
    exampleTasks: ['publish a video asset', 'inspect playback performance', 'support video-heavy content'],
    relatedItemIds: ['cloudinary', 'wordpress'],
  },
  // ── Wave 1 expansion ────────────────────────────────────────────────
  docker: {
    usedBySouls: ['Engineer', 'DevOps', 'QA'],
    unlocks: ['container builds and pushes', 'image inspection', 'reproducible local environments'],
    exampleTasks: ['build and tag the team image from the latest commit', 'push the release image to Docker Hub', 'run the test image in a sandbox to verify a fix'],
    relatedItemIds: ['kubernetes', 'github', 'fly-io'],
  },
  kubernetes: {
    usedBySouls: ['DevOps', 'Engineer', 'SRE'],
    unlocks: ['cluster control', 'pod inspection', 'guarded apply flows'],
    exampleTasks: ['investigate a pod crashloop and propose a fix', 'roll a restart on the API deployment', 'apply a manifest update with a plan-then-apply check'],
    relatedItemIds: ['docker', 'aws', 'cloudflare'],
  },
  'fly-io': {
    usedBySouls: ['Engineer', 'DevOps', 'Founder'],
    unlocks: ['edge VM deploys', 'branch previews', 'managed Postgres'],
    exampleTasks: ['deploy a feature branch to a preview app', 'scale a machine to a larger size during a launch', 'fork prod Postgres to a Fly volume for testing'],
    relatedItemIds: ['railway', 'render', 'docker'],
  },
  railway: {
    usedBySouls: ['Engineer', 'Founder', 'DevOps'],
    unlocks: ['git-push deploys', 'managed Postgres + Redis', 'env var management'],
    exampleTasks: ['provision a staging stack with Postgres and Redis', 'wire env vars for a new service', 'redeploy after a merge into main'],
    relatedItemIds: ['fly-io', 'render', 'supabase'],
  },
  render: {
    usedBySouls: ['Engineer', 'DevOps'],
    unlocks: ['web service deploys', 'cron jobs', 'managed databases'],
    exampleTasks: ['ship a fix and tail logs until traffic stabilizes', 'add a daily cron to clean up old data', 'rotate a database password without downtime'],
    relatedItemIds: ['fly-io', 'railway', 'aws'],
  },
  digitalocean: {
    usedBySouls: ['Engineer', 'DevOps', 'Founder'],
    unlocks: ['droplet management', 'managed databases', 'Spaces object storage'],
    exampleTasks: ['spin up a droplet, run a smoke test, and destroy it', 'snapshot a managed Postgres before a migration', 'upload a build artifact to Spaces'],
    relatedItemIds: ['aws', 'cloudflare', 'kubernetes'],
  },
  supabase: {
    usedBySouls: ['Engineer', 'AI Researcher', 'Founder'],
    unlocks: ['Postgres queries', 'RLS policy management', 'storage + realtime channels'],
    exampleTasks: ['run a SQL query to find the bug a user reported', 'tighten an RLS policy on the credentials table', 'audit storage bucket access patterns'],
    relatedItemIds: ['neon', 'pinecone', 'mongodb-atlas'],
  },
  neon: {
    usedBySouls: ['Engineer', 'DevOps'],
    unlocks: ['serverless Postgres', 'database branching', 'preview env DBs per PR'],
    exampleTasks: ['branch the prod DB for this PR', 'run a destructive migration on the branch and verify', 'merge the migration after CI green'],
    relatedItemIds: ['supabase', 'railway', 'github'],
  },
  'mongodb-atlas': {
    usedBySouls: ['Engineer', 'AI Researcher'],
    unlocks: ['MongoDB queries', 'index health checks', 'aggregation pipelines'],
    exampleTasks: ['query the users collection for a bug repro', 'check index health on the events collection', 'run an aggregation to compute weekly active users'],
    relatedItemIds: ['supabase', 'pinecone', 'qdrant'],
  },
  upstash: {
    usedBySouls: ['Engineer', 'DevOps', 'AI Researcher'],
    unlocks: ['Redis cache ops', 'Kafka topic ops', 'serverless vector queries'],
    exampleTasks: ['inspect cache hit ratio for the API', 'check the size of a Kafka topic', 'run a vector similarity query against agent memory'],
    relatedItemIds: ['supabase', 'qdrant', 'pinecone'],
  },
  'hugging-face': {
    usedBySouls: ['AI Researcher', 'ML Engineer', 'Engineer'],
    unlocks: ['model and dataset hub', 'inference endpoints', 'Spaces management'],
    exampleTasks: ['pull a fine-tuned model card', 'deploy a custom model to an Inference Endpoint', 'browse a dataset for a domain agent'],
    relatedItemIds: ['replicate', 'modal', 'openrouter'],
  },
  replicate: {
    usedBySouls: ['Creator', 'AI Researcher', 'Marketer'],
    unlocks: ['hosted generative inference', 'image / video generation', 'model versioning'],
    exampleTasks: ['generate hero images for a launch', 'turn a script into a narrated video', 'prototype a domain-specific model from a prompt'],
    relatedItemIds: ['hugging-face', 'modal', 'openrouter'],
  },
  modal: {
    usedBySouls: ['ML Engineer', 'AI Researcher', 'Engineer'],
    unlocks: ['serverless GPU jobs', 'web endpoints', 'scheduled functions'],
    exampleTasks: ['run a heavy embedding job on GPU', 'expose a Python function as a web endpoint for the agent', 'schedule a nightly batch summarizer'],
    relatedItemIds: ['hugging-face', 'replicate', 'openrouter'],
  },
  openrouter: {
    usedBySouls: ['AI Researcher', 'Engineer', 'PM'],
    unlocks: ['unified LLM router', 'multi-model A/B', 'cost-aware routing'],
    exampleTasks: ['A/B a prompt across Claude / GPT / Gemini in one call', 'fallback from Opus to Sonnet on rate limit', 'route a cheap step to an OSS model'],
    relatedItemIds: ['hugging-face', 'modal', 'replicate'],
  },
  linear: {
    usedBySouls: ['PM', 'Engineer', 'Founder'],
    unlocks: ['issue creation from chat', 'cycle tracking', 'auto-status on PR merge'],
    exampleTasks: ['file a bug from a Sentry alert into the right Linear team', 'pull active cycle progress and post the digest', 'auto-close a Linear issue when the PR merges'],
    relatedItemIds: ['github', 'jira', 'sentry'],
  },
  jira: {
    usedBySouls: ['PM', 'Engineer', 'Ops'],
    unlocks: ['sprint state surfacing', 'issue + board management', 'blocker triage'],
    exampleTasks: ['pull active sprint blockers', 'create a Jira ticket from a chat thread', 'transition an issue to Done after PR merge'],
    relatedItemIds: ['linear', 'github', 'slack'],
  },
  snyk: {
    usedBySouls: ['Engineer', 'Security', 'DevOps'],
    unlocks: ['vulnerability scanning', 'CVE triage', 'auto-remediation PRs'],
    exampleTasks: ['triage a CVE alert', 'open a fix PR with a bumped dep version', 'scan a container image before pushing'],
    relatedItemIds: ['github', 'docker', 'sentry'],
  },
  clerk: {
    usedBySouls: ['Engineer', 'Founder', 'PM'],
    unlocks: ['drop-in auth UI', 'test user provisioning', 'session + role inspection'],
    exampleTasks: ['provision a test user with admin role for E2E', 'audit a user session by id', 'rotate a session token after a security event'],
    relatedItemIds: ['descope', 'supabase', 'github'],
  },
  postmark: {
    usedBySouls: ['Engineer', 'Marketer', 'Support'],
    unlocks: ['transactional email sending', 'bounce inspection', 'template management'],
    exampleTasks: ['send a test welcome email', 'investigate a wave of bounces', 'roll a new transactional template'],
    relatedItemIds: ['resend', 'mailchimp', 'convertkit'],
  },
  'cloudflare-r2': {
    usedBySouls: ['Engineer', 'DevOps', 'Creator'],
    unlocks: ['S3-compatible storage', 'presigned URLs', 'lifecycle rules'],
    exampleTasks: ['archive old build artifacts to R2', 'presign a download URL for a teammate', 'apply a lifecycle rule to clean up branch previews'],
    relatedItemIds: ['cloudflare', 'aws', 'cloudinary'],
  },
  qdrant: {
    usedBySouls: ['AI Researcher', 'Engineer'],
    unlocks: ['vector storage', 'metadata filters', 'hybrid search'],
    exampleTasks: ['store agent memories with rich metadata', 'run a hybrid keyword + vector search', 'rebalance a collection after a model swap'],
    relatedItemIds: ['pinecone', 'upstash', 'supabase'],
  },
  ngrok: {
    usedBySouls: ['Engineer', 'DevOps'],
    unlocks: ['public tunnels', 'webhook intake', 'reserved domains'],
    exampleTasks: ['expose a local webhook receiver to a third party', 'reserve a domain for the team\'s shared dev tunnel', 'capture an inbound webhook payload for debugging'],
    relatedItemIds: ['cloudflare', 'trigger-dev', 'github'],
  },
  'trigger-dev': {
    usedBySouls: ['Engineer', 'AI Researcher', 'DevOps'],
    unlocks: ['durable background jobs', 'AI workflow orchestration', 'job chains'],
    exampleTasks: ['enqueue a long-running summarizer that survives restarts', 'chain a generation → review → publish workflow', 'schedule a daily content audit'],
    relatedItemIds: ['modal', 'ngrok', 'github'],
  },
};

export function getMarketplaceAppDetail(itemId: string): MarketplaceAppDetail | null {
  return MARKETPLACE_APP_DETAILS[itemId] || null;
}
