import { Platform, StyleSheet } from 'react-native';

export const SWAN_PURPLE = '#a855f7';
export const CARD_BG = '#0f172a';
export const CARD_BORDER = '#1e293b';
export const FIELD_BG = '#0a0f1c';
export const MUTED = '#64748b';
export const TEXT = '#e2e8f0';
export const TEXT_DIM = '#94a3b8';
export const DANGER = '#ef4444';
export const SUCCESS = '#22c55e';

export const styles = StyleSheet.create({
  anchor: {
    ...(Platform.OS === 'web' ? { position: 'fixed' as any } : StyleSheet.absoluteFillObject),
    top: 0, left: 0, right: 0, bottom: 0,
    zIndex: 1200,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  backdrop: {
    ...(Platform.OS === 'web' ? { position: 'fixed' as any } : StyleSheet.absoluteFillObject),
    top: 0, left: 0, right: 0, bottom: 0,
    ...(Platform.OS === 'web' ? ({
      backdropFilter: 'blur(14px) saturate(1.15)',
      WebkitBackdropFilter: 'blur(14px) saturate(1.15)',
    } as any) : {}),
  },
  card: {
    backgroundColor: `${CARD_BG}f2`,
    borderWidth: 1,
    borderRadius: 14,
    width: '94%' as any,
    maxWidth: 1180,
    maxHeight: '92vh' as any,
    padding: 22,
    gap: 14,
    ...(Platform.OS === 'web' ? ({
      boxShadow:
        '0 24px 70px rgba(0,0,0,0.55), 0 0 40px rgba(168,85,247,0.18), 0 0 0 1px rgba(255,255,255,0.02) inset',
    } as any) : {}),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    flex: 1,
  },
  headerGlyph: {
    width: 38,
    height: 38,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerGlyphText: {
    fontFamily: 'monospace',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  headerTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  headerSub: {
    color: TEXT_DIM,
    fontSize: 12,
    marginTop: 2,
    maxWidth: 520,
  },
  closeBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeText: { color: TEXT_DIM, fontSize: 18, fontWeight: '600' },
  launchReadinessPanel: {
    gap: 10,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: '#04111f',
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'radial-gradient(circle at 0% 0%, rgba(34,211,238,0.14), transparent 30%), linear-gradient(135deg, rgba(15,23,42,0.96), rgba(2,6,23,0.98))',
      boxShadow: '0 14px 36px rgba(0,0,0,0.32), 0 0 0 1px rgba(255,255,255,0.025) inset',
    } as any) : {}),
  },
  launchReadinessHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  launchReadinessOrb: {
    width: 42,
    height: 42,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  launchReadinessOrbText: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessKicker: {
    color: MUTED,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1.4,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 2,
  },
  launchReadinessSummary: {
    color: TEXT_DIM,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  launchReadinessActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 6,
    maxWidth: 210,
  },
  launchReadinessAction: {
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: '#020617',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  launchReadinessActionText: {
    color: TEXT_DIM,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  launchReadinessMetric: {
    flexGrow: 1,
    flexBasis: '30%' as any,
    minWidth: 150,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#020617aa',
    gap: 3,
  },
  launchReadinessMetricLabel: {
    color: MUTED,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessMetricValue: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '800',
  },
  launchReadinessIssueList: {
    gap: 5,
    paddingTop: 2,
  },
  launchReadinessIssueRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#020617c0',
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  launchReadinessIssueKind: {
    minWidth: 42,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessIssueText: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
    flex: 1,
  },
  launchReadinessFixMessage: {
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: '#020617c0',
  },
  launchReadinessFixMessageText: {
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '700',
  },
  launchReadinessApprovalBox: {
    gap: 3,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#f59e0b44',
    backgroundColor: '#451a031a',
  },
  launchReadinessApprovalLabel: {
    color: '#fbbf24',
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  launchReadinessApprovalText: {
    color: '#fde68a',
    fontSize: 10.5,
    lineHeight: 14,
  },
  helperHero: {
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#020617',
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'radial-gradient(circle at 10% 0%, rgba(56,189,248,0.16), transparent 34%), radial-gradient(circle at 90% 20%, rgba(168,85,247,0.18), transparent 32%)',
    } as any) : {}),
  },
  helperHeroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  helperEyebrow: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.4,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  helperHeroTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 3,
  },
  helperModeBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  helperModeBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  intentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  intentCard: {
    flexGrow: 1,
    flexBasis: '30%' as any,
    minWidth: 170,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    gap: 5,
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  intentCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  intentLabel: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  intentStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  intentTitle: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '800',
  },
  intentDesc: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
  },
  intentDetailPanel: {
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e3a5f',
    backgroundColor: '#07111f',
  },
  intentDetailHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  intentDetailKicker: {
    color: MUTED,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1.2,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  intentDetailTitle: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  intentDetailModePill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  intentDetailModeText: {
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  intentDetailBody: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 15,
  },
  intentCapabilityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  intentCapabilityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 4,
    backgroundColor: '#020617',
  },
  intentCapabilityDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  intentCapabilityText: {
    color: TEXT_DIM,
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  readinessMeta: {
    color: MUTED,
    fontSize: 10,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  readinessGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  readinessSubHeader: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  readinessSubTitle: {
    color: TEXT_DIM,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  automationReadinessPanel: {
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: '#04111f',
    gap: 10,
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'linear-gradient(135deg, rgba(34,197,94,0.08), rgba(15,23,42,0.9) 44%, rgba(2,6,23,0.92)), radial-gradient(circle at 92% 10%, rgba(56,189,248,0.15), transparent 34%)',
    } as any) : {}),
  },
  automationReadinessTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  automationScoreRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  automationScoreText: {
    fontSize: 15,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  automationReadinessCopy: {
    flex: 1,
    minWidth: 0,
  },
  automationReadinessStatus: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  automationReadinessSummary: {
    color: TEXT_DIM,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 3,
  },
  automationMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  automationMetric: {
    flexGrow: 1,
    flexBasis: '22%' as any,
    minWidth: 120,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
  },
  automationMetricValue: {
    fontSize: 16,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  automationMetricLabel: {
    color: TEXT,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  automationMetricDetail: {
    color: MUTED,
    fontSize: 9.5,
    marginTop: 2,
  },
  automationBlockerBox: {
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    backgroundColor: 'rgba(127, 29, 29, 0.18)',
    borderRadius: 12,
    padding: 9,
    gap: 4,
  },
  automationBlockerTitle: {
    color: '#fecaca',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  automationBlockerText: {
    color: '#fca5a5',
    fontSize: 10.5,
    lineHeight: 15,
  },
  automationRecommendationList: {
    borderWidth: 1,
    borderColor: '#1f2a44',
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    overflow: 'hidden',
  },
  automationRecommendationHeading: {
    color: TEXT,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1f2a44',
  },
  automationEmptyText: {
    color: MUTED,
    fontSize: 10.5,
    padding: 10,
  },
  automationRecommendationRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    padding: 9,
    borderTopWidth: 1,
    borderTopColor: 'rgba(31, 42, 68, 0.7)',
  },
  automationRecommendationRail: {
    width: 4,
    borderRadius: 999,
  },
  automationRecommendationCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  automationRecommendationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  automationRecommendationTitle: {
    flex: 1,
    color: TEXT,
    fontSize: 11,
    fontWeight: '900',
  },
  automationPriorityPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.6,
    overflow: 'hidden',
  },
  automationRecommendationDetail: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
  },
  readinessPill: {
    flexGrow: 1,
    flexBasis: '30%' as any,
    minWidth: 170,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: FIELD_BG,
    gap: 4,
  },
  readinessPillTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  readinessDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  readinessLabel: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '800',
    flex: 1,
  },
  readinessStatus: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  readinessDetail: {
    color: MUTED,
    fontSize: 10,
    lineHeight: 13,
  },
  controlRecommendation: {
    marginTop: 2,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: '#07111f',
    gap: 8,
  },
  controlRecommendationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  controlRecommendationDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  controlRecommendationLabel: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  controlRecommendationTitle: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '800',
    flex: 1,
    textAlign: 'right',
  },
  controlRecommendationSummary: {
    color: TEXT_DIM,
    fontSize: 11,
    lineHeight: 15,
  },
  controlStepsGrid: {
    gap: 6,
  },
  controlStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  controlStepNumber: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#020617',
    textAlign: 'center',
    lineHeight: 18,
    fontSize: 10,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  controlStepText: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 15,
    flex: 1,
  },
  bridgePanel: {
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#0e7490',
    backgroundColor: '#04111f',
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'linear-gradient(135deg, rgba(14,116,144,0.16), rgba(15,23,42,0.88) 42%, rgba(30,41,59,0.7)), radial-gradient(circle at 90% 10%, rgba(34,211,238,0.15), transparent 34%)',
    } as any) : {}),
  },
  bridgeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  bridgeTitle: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
  },
  bridgeDesc: {
    color: TEXT_DIM,
    fontSize: 11,
    lineHeight: 16,
  },
  bridgeEnvPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#020617',
  },
  bridgeEnvText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  bridgePrimaryBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#38bdf866',
    backgroundColor: '#083344',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  bridgePrimaryText: {
    color: '#67e8f9',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeSecondaryBtn: {
    minHeight: 34,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#f59e0b55',
    backgroundColor: '#451a0318',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  bridgeSecondaryText: {
    color: '#fbbf24',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeEnvHint: {
    color: MUTED,
    fontSize: 10.5,
    lineHeight: 14,
  },
  bridgeErrorText: {
    color: '#fca5a5',
    fontSize: 11,
    lineHeight: 15,
  },
  bridgeResultBox: {
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#164e63',
    backgroundColor: '#020617',
  },
  bridgeResultHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  bridgeResultSummary: {
    color: TEXT,
    fontSize: 11.5,
    lineHeight: 16,
    flex: 1,
  },
  bridgeResultMeta: {
    color: '#67e8f9',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeList: {
    gap: 6,
  },
  bridgeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 9,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  bridgeStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginTop: 4,
  },
  bridgeRowMain: {
    flex: 1,
    gap: 2,
  },
  bridgeRowTop: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  bridgeName: {
    color: TEXT,
    fontSize: 11.5,
    fontWeight: '800',
  },
  bridgeMeta: {
    color: MUTED,
    fontSize: 10,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeAgentCount: {
    color: '#67e8f9',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeDetail: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
  },
  bridgeHint: {
    color: MUTED,
    fontSize: 10,
    lineHeight: 14,
  },
  bridgeSmallCopyBtn: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#020617',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  bridgeSmallCopyText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgePairingNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  bridgePairingText: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 15,
    flex: 1,
  },
  tunnelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  bridgeCommandBox: {
    flexGrow: 1,
    flexBasis: '45%' as any,
    minWidth: 260,
    gap: 5,
  },
  bridgeCommandLabel: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeCommandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#164e63',
    backgroundColor: '#020617',
    overflow: 'hidden',
  },
  bridgeCommandText: {
    color: '#bae6fd',
    fontSize: 10.5,
    flex: 1,
    paddingHorizontal: 9,
    paddingVertical: 8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeCopyBtn: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderLeftWidth: 1,
    borderLeftColor: '#164e63',
    backgroundColor: '#082f49',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  bridgeCopyText: {
    color: '#67e8f9',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeTunnelNote: {
    gap: 3,
    padding: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#020617aa',
  },
  bridgeTunnelTitle: {
    color: '#67e8f9',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  bridgeTunnelText: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 15,
  },
  guardrailPanel: {
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1d4ed855',
    backgroundColor: '#07111f',
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'linear-gradient(135deg, rgba(29,78,216,0.18), rgba(2,6,23,0.9) 46%, rgba(8,47,73,0.64)), radial-gradient(circle at 12% 12%, rgba(103,232,249,0.13), transparent 30%)',
    } as any) : {}),
  },
  guardrailHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  guardrailTitle: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
  },
  guardrailBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#67e8f955',
    backgroundColor: '#020617',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  guardrailBadgeText: {
    color: '#67e8f9',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  guardrailDesc: {
    color: TEXT_DIM,
    fontSize: 11,
    lineHeight: 16,
  },
  guardrailModeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  guardrailModeCard: {
    flexGrow: 1,
    flexBasis: '30%' as any,
    minWidth: 170,
    gap: 5,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
    backgroundColor: '#020617cc',
  },
  guardrailModeCardActive: {
    borderColor: '#67e8f988',
    backgroundColor: '#08334488',
  },
  guardrailModeTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  guardrailModeLabel: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  guardrailModeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#334155',
  },
  guardrailModeTitle: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '800',
  },
  guardrailModeDesc: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
  },
  guardrailFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  guardrailField: {
    flexGrow: 1,
    flexBasis: '48%' as any,
    minWidth: 230,
    gap: 5,
  },
  guardrailFieldLabel: {
    color: '#bae6fd',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  guardrailInput: {
    minHeight: 54,
    maxHeight: 98,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1e3a8a66',
    backgroundColor: '#020617dd',
    color: TEXT,
    padding: 10,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: Platform.OS === 'web' ? 'inherit' : 'System',
  },
  guardrailToggleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  guardrailToggle: {
    flexGrow: 1,
    flexBasis: '48%' as any,
    minWidth: 230,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1e293b',
    backgroundColor: '#020617cc',
  },
  guardrailToggleActive: {
    borderColor: '#67e8f966',
    backgroundColor: '#082f4988',
  },
  guardrailSwitchTrack: {
    width: 38,
    height: 22,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#0f172a',
    padding: 2,
    justifyContent: 'center',
  },
  guardrailSwitchTrackActive: {
    borderColor: '#67e8f9',
    backgroundColor: '#155e75',
  },
  guardrailSwitchKnob: {
    width: 16,
    height: 16,
    borderRadius: 999,
    backgroundColor: '#64748b',
  },
  guardrailSwitchKnobActive: {
    alignSelf: 'flex-end',
    backgroundColor: '#ecfeff',
  },
  guardrailToggleTitle: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '800',
  },
  guardrailToggleDesc: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
    marginTop: 2,
  },
  guardrailLaunchNote: {
    gap: 4,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#020617aa',
  },
  guardrailLaunchTitle: {
    color: '#67e8f9',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  guardrailLaunchText: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 15,
  },
  section: { gap: 6 },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
    paddingTop: 6,
    paddingBottom: 2,
  },
  groupHeaderTick: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  groupHeaderLabel: {
    color: TEXT,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  groupHeaderHint: {
    color: TEXT_DIM,
    fontSize: 10,
    fontWeight: '700',
    flexShrink: 1,
  },
  groupHeaderRule: {
    flex: 1,
    height: 1,
    backgroundColor: CARD_BORDER,
  },
  accordionSection: {
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 16,
    backgroundColor: '#050914',
    overflow: 'hidden',
  },
  accordionHeader: {
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  accordionRail: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 999,
  },
  accordionHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  accordionTitle: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  accordionMeta: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  accordionChevron: {
    fontSize: 16,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  accordionBody: {
    paddingHorizontal: 10,
    paddingBottom: 12,
    gap: 10,
  },
  recentRunsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  recentRunsLiveChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: '#a78bfa18',
    borderWidth: 1,
    borderColor: '#a78bfa55',
  },
  recentRunsLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#a78bfa',
  },
  recentRunsLiveText: {
    color: '#a78bfa',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunStopBtn: {
    width: 26,
    height: 26,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ef444460',
    backgroundColor: '#7f1d1d10',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentRunStopText: {
    color: '#fca5a5',
    fontSize: 11,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunsChevron: {
    color: MUTED,
    fontSize: 11,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunsHint: {
    color: MUTED,
    fontSize: 10,
    fontStyle: 'italic',
    marginTop: 2,
  },
  templateSaveBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
  },
  templateSaveText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  templateChipWrap: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: FIELD_BG,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    overflow: 'hidden',
  },
  templateChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRightWidth: 1,
    borderRightColor: CARD_BORDER,
    maxWidth: 280,
  },
  templateChipMode: {
    backgroundColor: '#020617',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  templateChipModeText: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  templateChipLabel: {
    color: TEXT,
    fontSize: 11,
    fontWeight: '600',
    flexShrink: 1,
  },
  templateChipDelete: {
    paddingHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  templateChipDeleteText: {
    color: MUTED,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 14,
  },
  starterChip: {
    backgroundColor: FIELD_BG,
    borderRadius: 8,
    borderWidth: 1,
    borderRightWidth: 1,
    borderStyle: 'dashed',
  },
  spendRollup: {
    gap: 6,
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  spendRollupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  spendRollupLabel: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  spendBar: {
    flexDirection: 'row',
    height: 10,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: CARD_BORDER,
  },
  spendLegendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  spendLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  spendLegendSource: {
    color: TEXT_DIM,
    fontSize: 10.5,
    flex: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  spendLegendCost: {
    color: MUTED,
    fontSize: 10,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 8,
  },
  recentRunDot: { width: 8, height: 8, borderRadius: 999 },
  recentRunTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  recentRunMode: {
    color: TEXT_DIM,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
    textTransform: 'uppercase',
  },
  recentRunStatus: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunTitle: { color: TEXT, fontSize: 12, fontWeight: '600' },
  recentRunMeta: {
    color: MUTED,
    fontSize: 10,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunReceiptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  recentRunReceiptDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  recentRunReceiptText: {
    color: MUTED,
    fontSize: 10,
    flex: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  recentRunArrow: {
    color: TEXT_DIM,
    fontSize: 14,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  planPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  planKindChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  planKindText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.2,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  planSummary: {
    color: TEXT,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  planToolsBlock: { gap: 4, marginTop: 4 },
  planSubLabel: {
    color: MUTED,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  planToolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 1,
  },
  planToolDot: { width: 6, height: 6, borderRadius: 999 },
  planToolName: {
    color: TEXT_DIM,
    fontSize: 11,
    fontWeight: '700',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
    minWidth: 90,
  },
  planToolReason: {
    color: MUTED,
    fontSize: 11,
    flex: 1,
  },
  planMoreHint: {
    color: MUTED,
    fontSize: 10,
    fontStyle: 'italic',
    marginTop: 2,
  },
  planCostRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  planCostValue: {
    color: SUCCESS,
    fontSize: 13,
    fontWeight: '900',
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
    minWidth: 70,
  },
  planCostBreakdown: {
    color: MUTED,
    fontSize: 10,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
    flex: 1,
  },
  budgetWarning: {
    marginTop: 4,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ef444455',
    backgroundColor: '#7f1d1d18',
    gap: 3,
  },
  budgetWarningKicker: {
    color: '#fca5a5',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  budgetWarningBody: {
    color: '#fecaca',
    fontSize: 11,
    lineHeight: 16,
  },
  budgetWarningHint: {
    color: '#f87171',
    fontSize: 10,
    fontStyle: 'italic',
  },
  toolCatalogBody: {
    gap: 6,
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  toolCatalogFilter: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: TEXT,
    fontSize: 11,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  toolCatalogRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 6,
  },
  toolCatalogFamilyDot: { width: 6, height: 6, borderRadius: 999, marginTop: 6 },
  toolCatalogTitleRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  toolCatalogLabel: { color: TEXT, fontSize: 11, fontWeight: '700' },
  toolCatalogName: {
    color: MUTED,
    fontSize: 9,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  toolCatalogDesc: { color: TEXT_DIM, fontSize: 10.5, lineHeight: 14 },
  toolCatalogEmpty: {
    color: MUTED,
    fontSize: 11,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 10,
  },
  memInspectorBody: {
    gap: 6,
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  memInspectorRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 6,
  },
  memInspectorScopeChip: {
    backgroundColor: '#0c4a6e',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    minWidth: 50,
    alignItems: 'center',
  },
  memInspectorScopeText: {
    color: '#7dd3fc',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.6,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  memInspectorTitleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 6,
  },
  memInspectorTitle: { color: TEXT, fontSize: 11, fontWeight: '700', flex: 1 },
  memInspectorAge: {
    color: MUTED,
    fontSize: 9,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  memInspectorContent: { color: TEXT_DIM, fontSize: 10.5, lineHeight: 14 },
  memInspectorDeleteBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#334155',
    backgroundColor: '#0f172a',
    alignSelf: 'center',
  },
  memInspectorDeleteText: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.6,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  label: {
    color: TEXT_DIM,
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1.5,
  },
  input: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 10,
    padding: 12,
    color: TEXT,
    fontSize: 13,
    minHeight: 84,
    maxHeight: 180,
    fontFamily: Platform.OS === 'web' ? 'inherit' : 'System',
  },
  inputFooter: { flexDirection: 'row', justifyContent: 'space-between' },
  inputHint: { color: MUTED, fontSize: 11 },
  taskRecipePanel: {
    gap: 9,
    marginTop: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#22314f',
    backgroundColor: '#08111f',
  },
  taskRecipeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  taskRecipeKicker: {
    color: MUTED,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1.2,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  taskRecipeTitle: {
    color: TEXT,
    fontSize: 11.5,
    fontWeight: '800',
    marginTop: 2,
  },
  taskRecipeBtn: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: '#020617',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  taskRecipeBtnText: {
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 0.8,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  taskRecipeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  taskRecipeCard: {
    flexGrow: 1,
    flexBasis: '31%' as any,
    minWidth: 150,
    gap: 4,
    padding: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  taskRecipeLabel: {
    color: MUTED,
    fontSize: 8.5,
    fontWeight: '900',
    letterSpacing: 1,
    fontFamily: Platform.select({ web: 'ui-monospace, SFMono-Regular, Menlo, monospace', default: 'monospace' }) as string,
  },
  taskRecipeLine: {
    color: TEXT_DIM,
    fontSize: 10.5,
    lineHeight: 14,
  },
  modeBlock: {
    gap: 6,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  modeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  modeDot: { width: 6, height: 6, borderRadius: 999 },
  modeLabel: {
    fontFamily: 'monospace',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  modeDesc: {
    color: TEXT_DIM,
    fontSize: 11,
    marginTop: 2,
  },
  contractLabel: {
    color: MUTED,
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 1.2,
    marginTop: 2,
  },
  contractLine: {
    color: TEXT_DIM,
    fontSize: 11,
  },
  diagGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  diagCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor: FIELD_BG,
    minWidth: 110,
  },
  diagTitle: {
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  diagValue: {
    color: TEXT,
    fontSize: 22,
    fontWeight: '700',
    marginTop: 2,
  },
  diagHint: {
    color: TEXT_DIM,
    fontSize: 10,
    marginTop: 2,
  },
  maintRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  maintTitle: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
  },
  maintDesc: {
    color: TEXT_DIM,
    fontSize: 11,
    marginTop: 2,
  },
  maintenanceToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#060a14',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  pruneBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 68,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pruneBtnText: {
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  hiddenDrawer: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    borderRadius: 8,
    overflow: 'hidden',
  },
  hiddenHeader: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: FIELD_BG,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}),
  },
  hiddenHeaderText: {
    color: TEXT_DIM,
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1.1,
    fontWeight: '700',
  },
  hiddenHint: {
    color: MUTED,
    fontSize: 9,
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  hiddenList: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 3,
    backgroundColor: '#060a14',
  },
  hiddenItem: {
    color: TEXT_DIM,
    fontSize: 11,
  },
  hiddenItemCode: {
    color: MUTED,
    fontSize: 10,
    fontFamily: 'monospace',
  },
  memPreview: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
    gap: 3,
  },
  memPreviewLabel: {
    color: MUTED,
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  memPreviewItem: {
    color: TEXT_DIM,
    fontSize: 11,
  },
  memScope: {
    color: '#38bdf8',
    fontFamily: 'monospace',
    fontSize: 10,
  },
  budgetStrip: {
    marginTop: 6,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
    gap: 5,
  },
  budgetStripHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  budgetStripLabel: {
    color: MUTED,
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  budgetStripValue: {
    fontFamily: 'monospace',
    fontSize: 11,
    fontWeight: '700',
  },
  budgetStripPct: {
    color: TEXT_DIM,
    fontWeight: '600',
  },
  budgetBarTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1a202c',
    overflow: 'hidden',
  },
  budgetBarFill: {
    height: 4,
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 4,
  },
  modelInherit: {
    color: TEXT,
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  ghostBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  ghostBtnText: {
    color: TEXT_DIM,
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  primaryBtnText: {
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 1.4,
    fontWeight: '700',
  },
  primaryBtnKbd: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    opacity: 0.7,
  },

  // ── Automation section: quick actions ──────────────────────────────────
  automationQuickRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  automationQuickBtn: {
    flexGrow: 1,
    flexBasis: 150,
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  automationQuickText: {
    color: TEXT_DIM,
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '700',
  },

  // ── Automation section: readiness detail + trend ───────────────────────
  historyWrap: {
    marginTop: 4,
    gap: 6,
  },
  historyLabel: {
    color: TEXT_DIM,
    fontFamily: 'monospace',
    fontSize: 9,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  historyBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    height: 50,
  },
  historyBarSlot: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 3,
  },
  historyBar: {
    width: 16,
    borderRadius: 3,
  },
  historyBarValue: {
    color: TEXT_DIM,
    fontSize: 9,
    fontFamily: 'monospace',
  },

  // ── Automation section: saved automations list ─────────────────────────
  automationList: {
    gap: 6,
  },
  automationShowMore: {
    alignItems: 'center',
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: 'transparent',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } as any : {}),
  },
  automationShowMoreText: {
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '700',
  },
  automationNameInput: {
    borderRadius: 9,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
    color: TEXT,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    fontFamily: Platform.OS === 'web' ? 'inherit' : 'System',
  },
  scrollContent: {
    gap: 12,
    maxWidth: 1040,
    width: '100%',
    alignSelf: 'center',
  },
  automationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: FIELD_BG,
  },
  automationIcon: {
    fontSize: 16,
  },
  automationItemMain: {
    flex: 1,
    gap: 2,
  },
  automationItemName: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '700',
  },
  automationItemMeta: {
    color: TEXT_DIM,
    fontSize: 10,
    fontFamily: 'monospace',
  },
  automationRunBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 46,
  },
  automationRunText: {
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '800',
  },
  automationToggle: {
    width: 38,
    height: 22,
    borderRadius: 999,
    borderWidth: 1,
    padding: 2,
    justifyContent: 'center',
  },
  automationToggleKnob: {
    width: 16,
    height: 16,
    borderRadius: 999,
  },

  // ── Automation section: save current task ──────────────────────────────
  automationSaveWrap: {
    marginTop: 4,
  },
  automationSaveBtn: {
    alignItems: 'center',
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    backgroundColor: 'transparent',
  },
  automationSaveText: {
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '800',
  },
  automationSavePanel: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 10,
    backgroundColor: FIELD_BG,
  },
  automationSaveHeading: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
  },
  cadenceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  cadenceChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
  },
  cadenceChipText: {
    fontFamily: 'monospace',
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '700',
  },
  automationSaveActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
});
