import React, { useCallback, useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, RefreshControl, Alert, Linking } from 'react-native';
import {
  getResearchDocumentById,
  getResearchDocumentRelevantSpirits,
  getRelatedResearchDocuments,
  setResearchDocumentReviewStatus,
  type ResearchDocumentReference,
} from '../../lib/researchControl';
import type { ResearchDocument } from '../../lib/researchKnowledge';

const BG_PAGE = '#050508';
const BG_SURFACE = '#0a0a10';
const BG_RAISED = '#0f0f18';
const TEXT_PRI = '#f0f0f5';
const TEXT_SEC = '#a0a0b0';
const TEXT_TER = '#606075';
const BORDER_DEF = '#1a1a28';
const CYAN = '#06b6d4';
const GREEN = '#22c55e';

function metadataValue(value: unknown): string | null {
  if (value == null) return null;
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    const flat = value.filter((item) => typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean');
    return flat.length > 0 ? flat.join(', ') : null;
  }
  return null;
}

export default function ResearchDocumentDetailScreen({ navigation, route }: any) {
  const documentId = route?.params?.documentId as string;
  const [doc, setDoc] = useState<ResearchDocument | null>(null);
  const [relatedDocs, setRelatedDocs] = useState<ResearchDocumentReference[]>([]);
  const [refreshing, setRefreshing] = useState(false);
  const [reviewing, setReviewing] = useState<'draft' | 'reviewed' | 'validated' | null>(null);

  const load = useCallback(async () => {
    if (!documentId) return;
    setRefreshing(true);
    try {
      const next = await getResearchDocumentById(documentId);
      setDoc(next);
      if (next) {
        const related = await getRelatedResearchDocuments({ document: next, limit: 4 });
        setRelatedDocs(related);
      } else {
        setRelatedDocs([]);
      }
    } finally {
      setRefreshing(false);
    }
  }, [documentId]);

  useEffect(() => {
    void load();
  }, [load]);

  const updateReview = useCallback(async (reviewStatus: 'draft' | 'reviewed' | 'validated') => {
    if (!doc) return;
    setReviewing(reviewStatus);
    const result = await setResearchDocumentReviewStatus(doc.id, reviewStatus);
    setReviewing(null);
    if (!result.ok) {
      Alert.alert('Review Update Failed', result.error || 'Could not update review state.');
      return;
    }
    await load();
  }, [doc, load]);

  const relevantSpirits = doc ? getResearchDocumentRelevantSpirits(doc) : [];
  const metadata = (doc?.metadata || {}) as Record<string, unknown>;
  const lineageRows = [
    { label: 'Generated By', value: metadataValue(metadata.generated_by) },
    { label: 'Profile Key', value: metadataValue(metadata.profile_key) },
    { label: 'Source Kind', value: doc?.source_type || null },
    { label: 'Source Title', value: doc?.source_title || null },
    { label: 'Publication Date', value: doc?.publication_date || null },
    { label: 'Review Status', value: doc?.review_status || null },
  ].filter((row): row is { label: string; value: string } => !!row.value);
  const metadataRows = Object.entries(metadata)
    .map(([key, value]) => ({ key, value: metadataValue(value) }))
    .filter((entry): entry is { key: string; value: string } => !!entry.value)
    .slice(0, 10);

  return (
    <View style={styles.page}>
      <ScrollView
        contentContainerStyle={styles.scroll}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load()} tintColor={CYAN} />}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.header}>
          <Pressable onPress={() => navigation.goBack()} accessibilityRole="button">
            <Text style={styles.backText}>{'<-'} Back</Text>
          </Pressable>
          <View style={styles.headerCopy}>
            <Text style={styles.kicker}>Wiki Source Detail</Text>
            <Text style={styles.title}>{doc?.title || 'Loading research document...'}</Text>
            <Text style={styles.subtitle}>
              Full source context, provenance, affected SOULs, review controls, and Wiki integration metadata.
            </Text>
          </View>
        </View>

        {!doc ? (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Document unavailable</Text>
            <Text style={styles.cardBody}>This research document could not be loaded. It may have been removed or is not visible to this account.</Text>
          </View>
        ) : (
          <>
            <View style={styles.card}>
              <View style={styles.cardTop}>
                <View style={{ flex: 1 }}>
                  <Text style={styles.cardTitle}>{doc.title}</Text>
                  <Text style={styles.cardMeta}>
                    {doc.source_title || doc.source_type || 'Research'} • {doc.publication_date || 'No date'} • {(doc.review_status || 'draft').toUpperCase()}
                  </Text>
                </View>
                <View style={[styles.badge, { borderColor: CYAN + '40', backgroundColor: CYAN + '12' }]}>
                  <Text style={[styles.badgeText, { color: CYAN }]}>{(doc.source_type || 'note').toUpperCase()}</Text>
                </View>
              </View>

              {doc.summary ? (
                <>
                  <Text style={styles.sectionLabel}>Summary</Text>
                  <Text style={styles.cardBody}>{doc.summary}</Text>
                </>
              ) : null}

              {doc.content ? (
                <>
                  <Text style={styles.sectionLabel}>Full Body</Text>
                  <Text style={styles.longBody}>{doc.content}</Text>
                </>
              ) : null}

              <Text style={styles.sectionLabel}>Review State</Text>
              <View style={styles.actionRow}>
                {(['draft', 'reviewed', 'validated'] as const).map((status) => (
                  <Pressable
                    key={status}
                    onPress={() => void updateReview(status)}
                    style={[
                      styles.statusButton,
                      doc.review_status === status && styles.statusButtonActive,
                      reviewing === status && styles.statusButtonBusy,
                    ]}
                  >
                    <Text style={styles.statusButtonText}>{reviewing === status ? 'UPDATING…' : status.toUpperCase()}</Text>
                  </Pressable>
                ))}
              </View>
            </View>

            <View style={styles.metaGrid}>
              <View style={styles.metaCard}>
                <Text style={styles.sectionLabel}>Lineage</Text>
                {lineageRows.map((row) => (
                  <View key={row.label} style={styles.metaRow}>
                    <Text style={styles.metaKey}>{row.label}</Text>
                    <Text style={styles.metaValue}>{row.value}</Text>
                  </View>
                ))}
              </View>

              <View style={styles.metaCard}>
                <Text style={styles.sectionLabel}>SOULs Affected</Text>
                <View style={styles.chipWrap}>
                  {relevantSpirits.length > 0 ? relevantSpirits.map((spiritId) => (
                    <View key={spiritId} style={styles.chip}>
                      <Text style={styles.chipText}>{spiritId}</Text>
                    </View>
                  )) : <Text style={styles.metaValue}>No explicit spirit targeting recorded.</Text>}
                </View>
              </View>

              <View style={styles.metaCard}>
                <Text style={styles.sectionLabel}>Source Metadata</Text>
                <Text style={styles.metaValue}>Domain: {doc.domain_key || 'n/a'}</Text>
                <Text style={styles.metaValue}>Evidence: {doc.evidence_score ?? 'n/a'}</Text>
                <Text style={styles.metaValue}>Visibility: {doc.visibility || 'n/a'}</Text>
                {doc.authors && doc.authors.length > 0 ? (
                  <Text style={styles.metaValue}>Authors: {doc.authors.join(', ')}</Text>
                ) : null}
                {doc.source_url ? (
                  <Pressable onPress={() => void Linking.openURL(doc.source_url!)} style={styles.sourceLink}>
                    <Text style={styles.sourceLinkText}>OPEN SOURCE URL</Text>
                  </Pressable>
                ) : null}
              </View>
            </View>

            {doc.tags && doc.tags.length > 0 ? (
              <View style={styles.card}>
                <Text style={styles.sectionLabel}>Tags</Text>
                <View style={styles.chipWrap}>
                  {doc.tags.map((tag) => (
                    <View key={tag} style={styles.chip}>
                      <Text style={styles.chipText}>{tag}</Text>
                    </View>
                  ))}
                </View>
              </View>
            ) : null}

            {metadataRows.length > 0 ? (
              <View style={styles.card}>
                <Text style={styles.sectionLabel}>Automation Metadata</Text>
                {metadataRows.map((row) => (
                  <View key={row.key} style={styles.metaRow}>
                    <Text style={styles.metaKey}>{row.key}</Text>
                    <Text style={styles.metaValue}>{row.value}</Text>
                  </View>
                ))}
              </View>
            ) : null}

            {relatedDocs.length > 0 ? (
              <View style={styles.card}>
                <Text style={styles.sectionLabel}>Related Documents</Text>
                {relatedDocs.map((ref) => (
                  <Pressable
                    key={ref.id}
                    onPress={() => navigation.replace('ResearchDocumentDetail', { documentId: ref.id })}
                    style={[styles.relatedCard, { borderColor: `${ref.color}45`, backgroundColor: `${ref.color}12` }]}
                  >
                    <Text style={[styles.relatedTitle, { color: ref.color }]}>{ref.title}</Text>
                    <Text style={styles.relatedMeta}>
                      {(ref.profileKey || ref.sourceType || 'research').toUpperCase()} • {ref.reviewStatus.toUpperCase()}
                    </Text>
                    <Text style={styles.relatedSubtitle} numberOfLines={2}>{ref.subtitle}</Text>
                  </Pressable>
                ))}
              </View>
            ) : null}
          </>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: BG_PAGE },
  scroll: { padding: 20, paddingBottom: 48 },
  header: { marginBottom: 20 },
  backText: { color: CYAN, fontSize: 14, fontWeight: '600' },
  headerCopy: { marginTop: 14 },
  kicker: { color: CYAN, fontSize: 12, letterSpacing: 1.2, textTransform: 'uppercase' },
  title: { color: TEXT_PRI, fontSize: 28, fontWeight: '800', marginTop: 6 },
  subtitle: { color: TEXT_SEC, fontSize: 14, marginTop: 8, maxWidth: 760, lineHeight: 20 },
  card: { backgroundColor: BG_SURFACE, borderWidth: 1, borderColor: BORDER_DEF, borderRadius: 16, padding: 16, marginBottom: 14 },
  cardTop: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  cardTitle: { color: TEXT_PRI, fontSize: 16, fontWeight: '700' },
  cardMeta: { color: TEXT_TER, fontSize: 12, marginTop: 6 },
  cardBody: { color: TEXT_SEC, fontSize: 13, marginTop: 10, lineHeight: 19 },
  longBody: { color: TEXT_SEC, fontSize: 13, marginTop: 8, lineHeight: 20 },
  badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  badgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  sectionLabel: { color: TEXT_PRI, fontSize: 12, fontWeight: '800', letterSpacing: 0.8, marginTop: 14, marginBottom: 8, textTransform: 'uppercase' },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  statusButton: { backgroundColor: BG_RAISED, borderWidth: 1, borderColor: BORDER_DEF, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8 },
  statusButtonActive: { borderColor: GREEN + '50', backgroundColor: GREEN + '14' },
  statusButtonBusy: { opacity: 0.7 },
  statusButtonText: { color: TEXT_SEC, fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
  metaGrid: { gap: 14, marginBottom: 14 },
  metaCard: { backgroundColor: BG_SURFACE, borderWidth: 1, borderColor: BORDER_DEF, borderRadius: 16, padding: 16 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: BG_RAISED, borderWidth: 1, borderColor: BORDER_DEF, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  chipText: { color: TEXT_SEC, fontSize: 11, fontWeight: '700' },
  metaRow: { paddingVertical: 7, borderTopWidth: 1, borderTopColor: BORDER_DEF },
  metaKey: { color: CYAN, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  metaValue: { color: TEXT_SEC, fontSize: 13, lineHeight: 18, marginTop: 3 },
  relatedCard: { borderRadius: 12, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 9, marginTop: 10 },
  relatedTitle: { fontSize: 12, fontWeight: '800' },
  relatedMeta: { color: TEXT_TER, fontSize: 10, fontWeight: '700', marginTop: 4, letterSpacing: 0.4 },
  relatedSubtitle: { color: TEXT_SEC, fontSize: 12, lineHeight: 17, marginTop: 5 },
  sourceLink: { marginTop: 10, alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: CYAN + '40', backgroundColor: CYAN + '12' },
  sourceLinkText: { color: CYAN, fontSize: 11, fontWeight: '800', letterSpacing: 0.6 },
});
