/**
 * Integration provider registry — single source of truth.
 *
 * Adding a new integration is a 1-entry change here. The IntegrationsTab UI,
 * the schema validator, and the connector loader all consume from this list.
 *
 * Conventions:
 *   - id: snake_case, matches `circle_integrations.provider` value
 *   - icon: short glyph (1-2 chars) until we add real logos
 *   - color: brand color hex (used for card accent)
 *   - status: 'live' = end-to-end, 'beta' = partial, 'planned' = scaffolded,
 *             'coming_soon' = roadmap only
 *   - popular: surface on the "Popular" filter (top of marketplace)
 *
 * Categories (in display order):
 *   communication, code_dev, ai_llm, cloud_infra, productivity, crm_sales,
 *   marketing, analytics, ads, commerce, cms_site, storage, auth, finance,
 *   support, observability, search_db, crypto_web3, social
 */

import type { ProviderDefinition, IntegrationCategory } from './types';

export const INTEGRATIONS: ProviderDefinition[] = [
  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: 'slack', label: 'Slack', category: 'communication',
    description: 'Send messages, surface mentions, and trigger automations from Slack channels.',
    color: '#4a154b', icon: '💬',
    authModel: 'oauth2',
    capabilities: ['send_message', 'receive_webhook', 'automation_trigger', 'automation_action', 'agent_tool'],
    status: 'beta', popular: true,
    homepage: 'https://slack.com',
    oauthScopes: ['channels:read', 'chat:write', 'users:read'],
    tags: ['chat', 'team'],
  },
  {
    id: 'teams', label: 'Microsoft Teams', category: 'communication',
    description: 'Bridge Teams channels for cross-platform alerts and chats.',
    color: '#6264a7', icon: '👥',
    authModel: 'oauth2',
    capabilities: ['send_message', 'receive_webhook', 'automation_action'],
    status: 'beta',
    homepage: 'https://teams.microsoft.com',
    tags: ['chat', 'enterprise'],
  },
  {
    id: 'discord', label: 'Discord', category: 'communication',
    description: 'Connect Discord servers for community channels and bot commands.',
    color: '#5865f2', icon: '🎮',
    authModel: 'bot_token',
    capabilities: ['send_message', 'receive_webhook', 'automation_action'],
    status: 'beta', popular: true,
    homepage: 'https://discord.com',
    tags: ['chat', 'community'],
  },
  {
    id: 'telegram', label: 'Telegram', category: 'communication',
    description: 'Telegram bot integration for chats, channels, and command flows.',
    color: '#26a5e4', icon: '✈️',
    authModel: 'bot_token',
    capabilities: ['send_message', 'receive_webhook', 'automation_action'],
    status: 'planned',
    homepage: 'https://telegram.org',
    tags: ['chat', 'mobile'],
  },
  {
    id: 'twilio', label: 'Twilio', category: 'communication',
    description: 'SMS, voice, and WhatsApp messaging from your circle.',
    color: '#f22f46', icon: '☎️',
    authModel: 'api_key',
    capabilities: ['send_message', 'receive_webhook', 'automation_action'],
    status: 'planned',
    homepage: 'https://twilio.com',
    tags: ['sms', 'voice', 'whatsapp'],
  },
  {
    id: 'gmail', label: 'Gmail', category: 'communication',
    description: 'Send and receive email through your Google account.',
    color: '#ea4335', icon: '✉️',
    authModel: 'oauth2',
    capabilities: ['send_message', 'read_data', 'automation_trigger', 'automation_action'],
    status: 'beta', popular: true,
    homepage: 'https://gmail.com',
    oauthScopes: ['https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.readonly'],
    tags: ['email'],
  },
  {
    id: 'outlook', label: 'Outlook / Microsoft 365 Mail', category: 'communication',
    description: 'Send and receive email through Microsoft 365.',
    color: '#0078d4', icon: '✉️',
    authModel: 'oauth2',
    capabilities: ['send_message', 'read_data', 'automation_trigger', 'automation_action'],
    status: 'planned',
    homepage: 'https://outlook.com',
    tags: ['email', 'enterprise'],
  },
  {
    id: 'resend', label: 'Resend', category: 'communication',
    description: 'Developer-first transactional email API.',
    color: '#000000', icon: '✉️',
    authModel: 'api_key',
    capabilities: ['send_message', 'automation_action'],
    status: 'planned',
    homepage: 'https://resend.com',
    tags: ['email', 'transactional'],
  },
  {
    id: 'sendgrid', label: 'SendGrid', category: 'communication',
    description: 'Transactional email at scale with deliverability tools.',
    color: '#1a82e2', icon: '✉️',
    authModel: 'api_key',
    capabilities: ['send_message', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://sendgrid.com',
    tags: ['email', 'transactional'],
  },

  // ── Code & Dev ────────────────────────────────────────────────────────────
  {
    id: 'github', label: 'GitHub', category: 'code_dev',
    description: 'Watch commits, PRs, issues, and CI from your repos. The flagship integration.',
    color: '#181717', icon: '⚡',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger', 'automation_action', 'agent_tool'],
    status: 'live', popular: true,
    homepage: 'https://github.com',
    oauthScopes: ['repo', 'user', 'workflow'],
    tags: ['git', 'ci', 'code-review'],
  },
  {
    id: 'gitlab', label: 'GitLab', category: 'code_dev',
    description: 'GitLab repos, merge requests, and CI pipelines.',
    color: '#fc6d26', icon: '⚡',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger'],
    status: 'planned',
    homepage: 'https://gitlab.com',
    tags: ['git', 'ci'],
  },
  {
    id: 'bitbucket', label: 'Bitbucket', category: 'code_dev',
    description: 'Bitbucket repos and pipelines for Atlassian-shop teams.',
    color: '#0052cc', icon: '⚡',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://bitbucket.org',
    tags: ['git', 'atlassian'],
  },
  {
    id: 'linear', label: 'Linear', category: 'code_dev',
    description: 'Issues, projects, and cycles. Sync missions to/from Linear.',
    color: '#5e6ad2', icon: '📐',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger', 'automation_action'],
    status: 'planned', popular: true,
    homepage: 'https://linear.app',
    oauthScopes: ['read', 'write'],
    tags: ['issues', 'project-management'],
  },
  {
    id: 'jira', label: 'Jira', category: 'code_dev',
    description: 'Atlassian Jira issues, sprints, and boards.',
    color: '#0052cc', icon: '🟦',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger'],
    status: 'planned',
    homepage: 'https://atlassian.com/software/jira',
    tags: ['issues', 'project-management', 'enterprise'],
  },
  {
    id: 'sentry', label: 'Sentry', category: 'code_dev',
    description: 'Error tracking — surface new exceptions in your circle feed.',
    color: '#362d59', icon: '🐛',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger', 'agent_tool'],
    status: 'planned', popular: true,
    homepage: 'https://sentry.io',
    tags: ['errors', 'monitoring'],
  },
  {
    id: 'circleci', label: 'CircleCI', category: 'code_dev',
    description: 'Build and deploy pipelines.',
    color: '#161616', icon: '⚙️',
    authModel: 'api_key',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://circleci.com',
    tags: ['ci', 'cd'],
  },
  {
    id: 'launchdarkly', label: 'LaunchDarkly', category: 'code_dev',
    description: 'Feature flags and progressive delivery.',
    color: '#243340', icon: '🚦',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://launchdarkly.com',
    tags: ['feature-flags'],
  },

  // ── AI / LLM ──────────────────────────────────────────────────────────────
  {
    id: 'openai', label: 'OpenAI', category: 'ai_llm',
    description: 'GPT models and embeddings. Use as a BYOA agent provider.',
    color: '#10a37f', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'beta', popular: true,
    homepage: 'https://openai.com',
    tags: ['llm', 'chat', 'embeddings'],
  },
  {
    id: 'anthropic', label: 'Anthropic', category: 'ai_llm',
    description: 'Claude models — the family powering BlackSwan.',
    color: '#d97757', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'live', popular: true,
    homepage: 'https://anthropic.com',
    tags: ['llm', 'claude'],
  },
  {
    id: 'google_ai', label: 'Google AI (Gemini)', category: 'ai_llm',
    description: 'Gemini models for text, vision, and multimodal.',
    color: '#4285f4', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'beta',
    homepage: 'https://ai.google.dev',
    tags: ['llm', 'gemini', 'multimodal'],
  },
  {
    id: 'openrouter', label: 'OpenRouter', category: 'ai_llm',
    description: 'One API, every model. Route across 200+ providers.',
    color: '#6464f0', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'planned',
    homepage: 'https://openrouter.ai',
    tags: ['llm', 'router'],
  },
  {
    id: 'replicate', label: 'Replicate', category: 'ai_llm',
    description: 'Run open-source models in the cloud — image, audio, LLM.',
    color: '#000000', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'planned',
    homepage: 'https://replicate.com',
    tags: ['llm', 'image', 'open-source'],
  },
  {
    id: 'groq', label: 'Groq', category: 'ai_llm',
    description: 'Ultra-fast inference for Llama, Mixtral, and friends.',
    color: '#f55036', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'planned',
    homepage: 'https://groq.com',
    tags: ['llm', 'fast'],
  },
  {
    id: 'huggingface', label: 'HuggingFace', category: 'ai_llm',
    description: 'Inference Endpoints + the open-source model hub.',
    color: '#ffd21e', icon: '🤗',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'planned',
    homepage: 'https://huggingface.co',
    tags: ['llm', 'open-source'],
  },
  {
    id: 'mistral', label: 'Mistral AI', category: 'ai_llm',
    description: 'European LLMs with strong code & reasoning models.',
    color: '#fa520f', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://mistral.ai',
    tags: ['llm', 'eu'],
  },
  {
    id: 'cohere', label: 'Cohere', category: 'ai_llm',
    description: 'Enterprise LLMs, embeddings, and reranking.',
    color: '#39594d', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://cohere.com',
    tags: ['llm', 'embeddings'],
  },
  {
    id: 'together_ai', label: 'Together AI', category: 'ai_llm',
    description: 'Hosted open-source inference (Llama, Qwen, DeepSeek).',
    color: '#1c1c1c', icon: '🧠',
    authModel: 'api_key',
    capabilities: ['ai_inference', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://together.ai',
    tags: ['llm', 'open-source'],
  },

  // ── Cloud Infra ───────────────────────────────────────────────────────────
  {
    id: 'aws', label: 'Amazon Web Services', category: 'cloud_infra',
    description: 'EC2, S3, Lambda, RDS — connect via cross-account IAM role with external ID.',
    color: '#ff9900', icon: '☁️',
    authModel: 'iam_role',
    capabilities: ['read_data', 'write_data', 'storage', 'agent_tool', 'automation_action'],
    status: 'planned', popular: true,
    homepage: 'https://aws.amazon.com',
    tags: ['cloud', 'enterprise'],
  },
  {
    id: 'gcp', label: 'Google Cloud Platform', category: 'cloud_infra',
    description: 'GCS, Cloud Run, BigQuery — connect via service account.',
    color: '#4285f4', icon: '☁️',
    authModel: 'service_account',
    capabilities: ['read_data', 'write_data', 'storage', 'agent_tool'],
    status: 'planned',
    homepage: 'https://cloud.google.com',
    tags: ['cloud'],
  },
  {
    id: 'azure', label: 'Microsoft Azure', category: 'cloud_infra',
    description: 'Azure resources — VMs, Blob Storage, Functions.',
    color: '#0078d4', icon: '☁️',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'storage'],
    status: 'coming_soon',
    homepage: 'https://azure.microsoft.com',
    tags: ['cloud', 'enterprise'],
  },
  {
    id: 'cloudflare', label: 'Cloudflare', category: 'cloud_infra',
    description: 'DNS, Workers, R2, Pages, KV.',
    color: '#f38020', icon: '☁️',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned',
    homepage: 'https://cloudflare.com',
    tags: ['cdn', 'edge', 'dns'],
  },
  {
    id: 'vercel', label: 'Vercel', category: 'cloud_infra',
    description: 'Deploy previews, Edge Functions, build status.',
    color: '#000000', icon: '▲',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger'],
    status: 'planned', popular: true,
    homepage: 'https://vercel.com',
    tags: ['hosting', 'next.js'],
  },
  {
    id: 'netlify', label: 'Netlify', category: 'cloud_infra',
    description: 'JAMstack hosting + serverless functions.',
    color: '#00c7b7', icon: '🌐',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger'],
    status: 'planned',
    homepage: 'https://netlify.com',
    tags: ['hosting', 'jamstack'],
  },
  {
    id: 'fly', label: 'Fly.io', category: 'cloud_infra',
    description: 'Run apps close to users on a global edge network.',
    color: '#7c3aed', icon: '🪂',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://fly.io',
    tags: ['hosting', 'edge'],
  },
  {
    id: 'railway', label: 'Railway', category: 'cloud_infra',
    description: 'Deploy services and databases from GitHub.',
    color: '#0b0d0e', icon: '🚂',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://railway.app',
    tags: ['hosting'],
  },
  {
    id: 'render', label: 'Render', category: 'cloud_infra',
    description: 'Web services, Postgres, and cron jobs.',
    color: '#46e3b7', icon: '🟢',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://render.com',
    tags: ['hosting'],
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: 'notion', label: 'Notion', category: 'productivity',
    description: 'Pages, databases, and shared docs.',
    color: '#000000', icon: '📓',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action', 'agent_tool'],
    status: 'planned', popular: true,
    homepage: 'https://notion.so',
    tags: ['docs', 'wiki'],
  },
  {
    id: 'asana', label: 'Asana', category: 'productivity',
    description: 'Tasks, projects, and team coordination.',
    color: '#f06a6a', icon: '✓',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_trigger'],
    status: 'planned',
    homepage: 'https://asana.com',
    tags: ['tasks', 'project-management'],
  },
  {
    id: 'trello', label: 'Trello', category: 'productivity',
    description: 'Boards, lists, and cards.',
    color: '#0079bf', icon: '📋',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://trello.com',
    tags: ['kanban'],
  },
  {
    id: 'airtable', label: 'Airtable', category: 'productivity',
    description: 'Spreadsheet-database hybrid for structured data.',
    color: '#fcb400', icon: '🗂',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned', popular: true,
    homepage: 'https://airtable.com',
    tags: ['database', 'no-code'],
  },
  {
    id: 'figma', label: 'Figma', category: 'productivity',
    description: 'Design files, comments, and dev mode.',
    color: '#f24e1e', icon: '🎨',
    authModel: 'oauth2',
    capabilities: ['read_data', 'receive_webhook'],
    status: 'beta',
    homepage: 'https://figma.com',
    tags: ['design'],
  },
  {
    id: 'google_sheets', label: 'Google Sheets', category: 'productivity',
    description: 'Read/write spreadsheets — the universal data exchange.',
    color: '#0f9d58', icon: '📊',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned', popular: true,
    homepage: 'https://sheets.google.com',
    tags: ['spreadsheet', 'data'],
  },
  {
    id: 'google_drive', label: 'Google Drive', category: 'productivity',
    description: 'Files in Drive — read, list, share.',
    color: '#0f9d58', icon: '📁',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'storage'],
    status: 'beta',
    homepage: 'https://drive.google.com',
    tags: ['files', 'storage'],
  },
  {
    id: 'monday', label: 'Monday.com', category: 'productivity',
    description: 'Work OS for teams — boards, automations, workflows.',
    color: '#ff3d57', icon: '🗓',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://monday.com',
    tags: ['project-management'],
  },
  {
    id: 'miro', label: 'Miro', category: 'productivity',
    description: 'Collaborative whiteboards.',
    color: '#ffd02f', icon: '🖼',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://miro.com',
    tags: ['whiteboard'],
  },
  {
    id: 'clickup', label: 'ClickUp', category: 'productivity',
    description: 'Tasks, docs, goals, and time tracking.',
    color: '#7b68ee', icon: '⬆️',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://clickup.com',
    tags: ['project-management'],
  },

  // ── CRM / Sales ───────────────────────────────────────────────────────────
  {
    id: 'salesforce', label: 'Salesforce', category: 'crm_sales',
    description: 'Leads, accounts, opportunities — the enterprise CRM.',
    color: '#00a1e0', icon: '☁️',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned',
    homepage: 'https://salesforce.com',
    requiredPlan: 'business',
    tags: ['crm', 'enterprise'],
  },
  {
    id: 'hubspot', label: 'HubSpot', category: 'crm_sales',
    description: 'CRM, marketing, sales, and service hub.',
    color: '#ff7a59', icon: '🧲',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned', popular: true,
    homepage: 'https://hubspot.com',
    tags: ['crm', 'marketing'],
  },
  {
    id: 'pipedrive', label: 'Pipedrive', category: 'crm_sales',
    description: 'Sales-focused CRM with strong automation.',
    color: '#017737', icon: '📈',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned',
    homepage: 'https://pipedrive.com',
    tags: ['crm', 'sales'],
  },
  {
    id: 'attio', label: 'Attio', category: 'crm_sales',
    description: 'Modern, flexible CRM for teams that customize.',
    color: '#000000', icon: '📇',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://attio.com',
    tags: ['crm'],
  },

  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    id: 'mailchimp', label: 'Mailchimp', category: 'marketing',
    description: 'Email campaigns and audiences.',
    color: '#ffe01b', icon: '🐵',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned',
    homepage: 'https://mailchimp.com',
    tags: ['email-marketing'],
  },
  {
    id: 'convertkit', label: 'Kit (ConvertKit)', category: 'marketing',
    description: 'Email marketing for creators.',
    color: '#fb6970', icon: '✉️',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'planned',
    homepage: 'https://kit.com',
    tags: ['email-marketing', 'creators'],
  },
  {
    id: 'klaviyo', label: 'Klaviyo', category: 'marketing',
    description: 'E-commerce email + SMS marketing.',
    color: '#1a1a1a', icon: '💌',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://klaviyo.com',
    tags: ['email-marketing', 'ecommerce'],
  },
  {
    id: 'brevo', label: 'Brevo (Sendinblue)', category: 'marketing',
    description: 'All-in-one email, SMS, and chat marketing.',
    color: '#0b996e', icon: '📨',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://brevo.com',
    tags: ['email-marketing', 'sms'],
  },
  {
    id: 'buffer', label: 'Buffer', category: 'marketing',
    description: 'Schedule social posts across networks.',
    color: '#168eea', icon: '📅',
    authModel: 'oauth2',
    capabilities: ['write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://buffer.com',
    tags: ['social', 'scheduling'],
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: 'google_analytics', label: 'Google Analytics 4', category: 'analytics',
    description: 'Web + app analytics. Pull metrics into your circle dashboard.',
    color: '#ff9900', icon: '📊',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'planned',
    homepage: 'https://analytics.google.com',
    tags: ['web-analytics'],
  },
  {
    id: 'google_search_console', label: 'Google Search Console', category: 'analytics',
    description: 'SEO performance, indexing, and search queries.',
    color: '#458cf5', icon: '🔍',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'planned',
    homepage: 'https://search.google.com/search-console',
    tags: ['seo'],
  },
  {
    id: 'mixpanel', label: 'Mixpanel', category: 'analytics',
    description: 'Product analytics — funnels, cohorts, retention.',
    color: '#7856ff', icon: '📈',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source'],
    status: 'planned',
    homepage: 'https://mixpanel.com',
    tags: ['product-analytics'],
  },
  {
    id: 'amplitude', label: 'Amplitude', category: 'analytics',
    description: 'Digital analytics for product teams.',
    color: '#1d4ed8', icon: '📊',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://amplitude.com',
    tags: ['product-analytics'],
  },
  {
    id: 'posthog', label: 'PostHog', category: 'analytics',
    description: 'Open-source product analytics + session replays.',
    color: '#1d4aff', icon: '🦔',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'analytics_source'],
    status: 'planned', popular: true,
    homepage: 'https://posthog.com',
    tags: ['product-analytics', 'open-source'],
  },
  {
    id: 'plausible', label: 'Plausible', category: 'analytics',
    description: 'Privacy-friendly web analytics.',
    color: '#5850ec', icon: '📊',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://plausible.io',
    tags: ['web-analytics', 'privacy'],
  },

  // ── Ads ───────────────────────────────────────────────────────────────────
  {
    id: 'google_ads', label: 'Google Ads', category: 'ads',
    description: 'Campaign performance, spend, and conversion data.',
    color: '#4285f4', icon: '🅰️',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'planned',
    homepage: 'https://ads.google.com',
    tags: ['ppc', 'paid'],
  },
  {
    id: 'meta_ads', label: 'Meta Ads', category: 'ads',
    description: 'Facebook + Instagram ads — performance and audiences.',
    color: '#1877f2', icon: '🅵',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'planned',
    homepage: 'https://business.facebook.com',
    tags: ['paid', 'social'],
  },
  {
    id: 'linkedin_ads', label: 'LinkedIn Ads', category: 'ads',
    description: 'B2B campaign performance.',
    color: '#0a66c2', icon: '💼',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://business.linkedin.com',
    tags: ['paid', 'b2b'],
  },
  {
    id: 'x_ads', label: 'X Ads', category: 'ads',
    description: 'X (Twitter) advertising performance.',
    color: '#000000', icon: '𝕏',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://ads.x.com',
    tags: ['paid', 'social'],
  },
  {
    id: 'tiktok_ads', label: 'TikTok Ads', category: 'ads',
    description: 'TikTok for Business campaign data.',
    color: '#000000', icon: '🎵',
    authModel: 'oauth2',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://ads.tiktok.com',
    tags: ['paid', 'social'],
  },

  // ── Commerce ──────────────────────────────────────────────────────────────
  {
    id: 'stripe', label: 'Stripe', category: 'commerce',
    description: 'Payments, subscriptions, and billing — already powering UC checkout.',
    color: '#635bff', icon: '💳',
    authModel: 'api_key',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger'],
    status: 'beta', popular: true,
    homepage: 'https://stripe.com',
    tags: ['payments', 'billing'],
  },
  {
    id: 'shopify', label: 'Shopify', category: 'commerce',
    description: 'Storefront — orders, products, customers.',
    color: '#7ab55c', icon: '🛒',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data', 'write_data', 'automation_trigger'],
    status: 'planned', popular: true,
    homepage: 'https://shopify.com',
    tags: ['ecommerce'],
  },
  {
    id: 'lemonsqueezy', label: 'Lemon Squeezy', category: 'commerce',
    description: 'Merchant of record for digital products.',
    color: '#ffc233', icon: '🍋',
    authModel: 'api_key',
    capabilities: ['receive_webhook', 'read_data', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://lemonsqueezy.com',
    tags: ['payments', 'digital-products'],
  },
  {
    id: 'paddle', label: 'Paddle', category: 'commerce',
    description: 'Payments + tax + sub-management for SaaS.',
    color: '#fdd000', icon: '🪧',
    authModel: 'api_key',
    capabilities: ['receive_webhook', 'read_data'],
    status: 'coming_soon',
    homepage: 'https://paddle.com',
    tags: ['payments', 'saas'],
  },
  {
    id: 'square', label: 'Square', category: 'commerce',
    description: 'POS, payments, and inventory.',
    color: '#000000', icon: '⬜',
    authModel: 'oauth2',
    capabilities: ['receive_webhook', 'read_data'],
    status: 'coming_soon',
    homepage: 'https://squareup.com',
    tags: ['payments', 'pos'],
  },
  {
    id: 'woocommerce', label: 'WooCommerce', category: 'commerce',
    description: 'WordPress storefront — orders + products.',
    color: '#7f54b3', icon: '🛍',
    authModel: 'api_key',
    capabilities: ['receive_webhook', 'read_data'],
    status: 'coming_soon',
    homepage: 'https://woocommerce.com',
    tags: ['ecommerce', 'wordpress'],
  },

  // ── CMS / Site ────────────────────────────────────────────────────────────
  {
    id: 'wordpress', label: 'WordPress', category: 'cms_site',
    description: 'Publish posts and manage content from your circle.',
    color: '#21759b', icon: '📝',
    authModel: 'basic',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'beta',
    homepage: 'https://wordpress.org',
    tags: ['cms'],
  },
  {
    id: 'webflow', label: 'Webflow', category: 'cms_site',
    description: 'Visual web design + CMS.',
    color: '#4353ff', icon: '🌊',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://webflow.com',
    tags: ['cms', 'no-code'],
  },
  {
    id: 'ghost', label: 'Ghost', category: 'cms_site',
    description: 'Modern publishing platform with native subscriptions.',
    color: '#15171a', icon: '👻',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://ghost.org',
    tags: ['cms', 'newsletter'],
  },
  {
    id: 'sanity', label: 'Sanity', category: 'cms_site',
    description: 'Headless CMS with structured content.',
    color: '#f03e2f', icon: '🧱',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://sanity.io',
    tags: ['headless-cms'],
  },
  {
    id: 'contentful', label: 'Contentful', category: 'cms_site',
    description: 'Headless CMS for enterprise teams.',
    color: '#fcd000', icon: '🧱',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://contentful.com',
    tags: ['headless-cms', 'enterprise'],
  },
  {
    id: 'squarespace', label: 'Squarespace', category: 'cms_site',
    description: 'All-in-one website builder.',
    color: '#000000', icon: '⬛',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://squarespace.com',
    tags: ['website-builder'],
  },

  // ── Storage ───────────────────────────────────────────────────────────────
  {
    id: 'aws_s3', label: 'AWS S3', category: 'storage',
    description: 'Object storage. Connects via the AWS integration.',
    color: '#ff9900', icon: '🪣',
    authModel: 'iam_role',
    capabilities: ['storage', 'read_data', 'write_data'],
    status: 'planned',
    homepage: 'https://aws.amazon.com/s3',
    tags: ['storage', 'object'],
  },
  {
    id: 'dropbox', label: 'Dropbox', category: 'storage',
    description: 'Files and folders in Dropbox.',
    color: '#0061ff', icon: '📦',
    authModel: 'oauth2',
    capabilities: ['storage', 'read_data', 'write_data'],
    status: 'planned',
    homepage: 'https://dropbox.com',
    tags: ['storage', 'files'],
  },
  {
    id: 'onedrive', label: 'OneDrive', category: 'storage',
    description: 'Microsoft files — personal and SharePoint.',
    color: '#0078d4', icon: '☁️',
    authModel: 'oauth2',
    capabilities: ['storage', 'read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://onedrive.live.com',
    tags: ['storage', 'enterprise'],
  },
  {
    id: 'cloudflare_r2', label: 'Cloudflare R2', category: 'storage',
    description: 'S3-compatible storage with no egress fees.',
    color: '#f38020', icon: '🪣',
    authModel: 'api_key',
    capabilities: ['storage', 'read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://cloudflare.com/products/r2',
    tags: ['storage', 'object'],
  },

  // ── Auth ──────────────────────────────────────────────────────────────────
  {
    id: 'auth0', label: 'Auth0', category: 'auth',
    description: 'Universal login and SSO.',
    color: '#eb5424', icon: '🔐',
    authModel: 'oauth2',
    capabilities: ['auth_provider', 'read_data'],
    status: 'coming_soon',
    homepage: 'https://auth0.com',
    requiredPlan: 'enterprise',
    tags: ['sso', 'identity'],
  },
  {
    id: 'clerk', label: 'Clerk', category: 'auth',
    description: 'Developer-first auth + user management.',
    color: '#6c47ff', icon: '🔐',
    authModel: 'api_key',
    capabilities: ['auth_provider', 'read_data'],
    status: 'coming_soon',
    homepage: 'https://clerk.com',
    requiredPlan: 'business',
    tags: ['sso', 'identity'],
  },
  {
    id: 'workos', label: 'WorkOS', category: 'auth',
    description: 'Enterprise SSO, SCIM, and audit logs.',
    color: '#6363f1', icon: '🔐',
    authModel: 'api_key',
    capabilities: ['auth_provider', 'read_data'],
    status: 'planned',
    homepage: 'https://workos.com',
    requiredPlan: 'enterprise',
    tags: ['sso', 'enterprise'],
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: 'quickbooks', label: 'QuickBooks', category: 'finance',
    description: 'Accounting — invoices, expenses, reports.',
    color: '#2ca01c', icon: '💰',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://quickbooks.intuit.com',
    tags: ['accounting'],
  },
  {
    id: 'plaid', label: 'Plaid', category: 'finance',
    description: 'Bank account connections + transaction data.',
    color: '#000000', icon: '🏦',
    authModel: 'api_key',
    capabilities: ['read_data'],
    status: 'coming_soon',
    homepage: 'https://plaid.com',
    tags: ['banking', 'fintech'],
  },
  {
    id: 'mercury', label: 'Mercury', category: 'finance',
    description: 'Banking for startups — balances, transactions, transfers.',
    color: '#5436da', icon: '🏦',
    authModel: 'api_key',
    capabilities: ['read_data'],
    status: 'coming_soon',
    homepage: 'https://mercury.com',
    tags: ['banking', 'startup'],
  },

  // ── Support ───────────────────────────────────────────────────────────────
  {
    id: 'zendesk', label: 'Zendesk', category: 'support',
    description: 'Tickets, customers, and help center.',
    color: '#03363d', icon: '🎫',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://zendesk.com',
    tags: ['support', 'tickets'],
  },
  {
    id: 'intercom', label: 'Intercom', category: 'support',
    description: 'Customer messaging + AI chatbot.',
    color: '#1f8ded', icon: '💬',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://intercom.com',
    tags: ['support', 'messaging'],
  },
  {
    id: 'help_scout', label: 'Help Scout', category: 'support',
    description: 'Email-first help desk for small teams.',
    color: '#1292ee', icon: '🎫',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://helpscout.com',
    tags: ['support'],
  },

  // ── Observability ─────────────────────────────────────────────────────────
  {
    id: 'datadog', label: 'Datadog', category: 'observability',
    description: 'Monitoring, APM, logs, and synthetic tests.',
    color: '#632ca6', icon: '🐶',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source', 'receive_webhook', 'automation_trigger'],
    status: 'coming_soon',
    homepage: 'https://datadoghq.com',
    requiredPlan: 'business',
    tags: ['monitoring', 'apm'],
  },
  {
    id: 'new_relic', label: 'New Relic', category: 'observability',
    description: 'Full-stack observability platform.',
    color: '#1ce783', icon: '🔭',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://newrelic.com',
    tags: ['monitoring', 'apm'],
  },
  {
    id: 'grafana', label: 'Grafana', category: 'observability',
    description: 'Dashboards + alerting on top of metrics.',
    color: '#f46800', icon: '📊',
    authModel: 'api_key',
    capabilities: ['read_data', 'analytics_source', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://grafana.com',
    tags: ['monitoring', 'dashboards', 'open-source'],
  },

  // ── Search / DB ───────────────────────────────────────────────────────────
  {
    id: 'algolia', label: 'Algolia', category: 'search_db',
    description: 'Hosted search-as-you-type.',
    color: '#003dff', icon: '🔍',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://algolia.com',
    tags: ['search'],
  },
  {
    id: 'pinecone', label: 'Pinecone', category: 'search_db',
    description: 'Vector database for embeddings + RAG.',
    color: '#000000', icon: '🌲',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://pinecone.io',
    tags: ['vector-db', 'rag'],
  },
  {
    id: 'meilisearch', label: 'Meilisearch', category: 'search_db',
    description: 'Open-source search — fast, typo-tolerant.',
    color: '#ff5caa', icon: '🔍',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data', 'agent_tool'],
    status: 'coming_soon',
    homepage: 'https://meilisearch.com',
    tags: ['search', 'open-source'],
  },

  // ── Crypto / Web3 ─────────────────────────────────────────────────────────
  {
    id: 'helius', label: 'Helius', category: 'crypto_web3',
    description: 'Solana RPC + webhooks for transaction events.',
    color: '#9945ff', icon: '☀️',
    authModel: 'api_key',
    capabilities: ['read_data', 'receive_webhook', 'automation_trigger'],
    status: 'planned',
    homepage: 'https://helius.dev',
    tags: ['solana', 'rpc'],
  },
  {
    id: 'coinbase', label: 'Coinbase', category: 'crypto_web3',
    description: 'Account balances, prices, and Coinbase Commerce.',
    color: '#0052ff', icon: '🪙',
    authModel: 'oauth2',
    capabilities: ['read_data', 'receive_webhook'],
    status: 'coming_soon',
    homepage: 'https://coinbase.com',
    tags: ['crypto'],
  },
  {
    id: 'phantom', label: 'Phantom', category: 'crypto_web3',
    description: 'Solana + Ethereum wallet connection.',
    color: '#ab9ff2', icon: '👻',
    authModel: 'oauth2',
    capabilities: ['read_data'],
    status: 'beta',
    homepage: 'https://phantom.app',
    tags: ['wallet', 'solana'],
  },

  // ── Social ────────────────────────────────────────────────────────────────
  {
    id: 'x_twitter', label: 'X (Twitter)', category: 'social',
    description: 'Post tweets, read mentions, manage threads.',
    color: '#000000', icon: '𝕏',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://x.com',
    tags: ['social'],
  },
  {
    id: 'linkedin', label: 'LinkedIn', category: 'social',
    description: 'Personal + Company page posts.',
    color: '#0a66c2', icon: '💼',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'automation_action'],
    status: 'coming_soon',
    homepage: 'https://linkedin.com',
    tags: ['social', 'b2b'],
  },
  {
    id: 'instagram', label: 'Instagram', category: 'social',
    description: 'Post media + read insights via Meta Graph API.',
    color: '#e4405f', icon: '📷',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://instagram.com',
    tags: ['social'],
  },
  {
    id: 'youtube', label: 'YouTube', category: 'social',
    description: 'Channel analytics, video uploads, comments.',
    color: '#ff0000', icon: '▶️',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data', 'analytics_source'],
    status: 'coming_soon',
    homepage: 'https://youtube.com',
    tags: ['social', 'video'],
  },
  {
    id: 'reddit', label: 'Reddit', category: 'social',
    description: 'Subreddit posts and comment monitoring.',
    color: '#ff4500', icon: '👽',
    authModel: 'oauth2',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://reddit.com',
    tags: ['social', 'community'],
  },
  {
    id: 'bluesky', label: 'Bluesky', category: 'social',
    description: 'AT Protocol — post and read on the open social network.',
    color: '#0085ff', icon: '🦋',
    authModel: 'api_key',
    capabilities: ['read_data', 'write_data'],
    status: 'coming_soon',
    homepage: 'https://bsky.app',
    tags: ['social', 'open-protocol'],
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

const REGISTRY_INDEX: Map<string, ProviderDefinition> = new Map(
  INTEGRATIONS.map(provider => [provider.id, provider]),
);

/**
 * Look up a provider by id. Returns undefined for unknown ids.
 */
export function getIntegration(id: string): ProviderDefinition | undefined {
  return REGISTRY_INDEX.get(id);
}

/**
 * True when the given id is a known provider in the registry. Use for schema
 * validation in lieu of a SQL CHECK constraint.
 */
export function isValidProvider(id: string): boolean {
  return REGISTRY_INDEX.has(id);
}

/**
 * All providers in a single category, in registry order.
 */
export function getIntegrationsByCategory(category: IntegrationCategory): ProviderDefinition[] {
  return INTEGRATIONS.filter(p => p.category === category);
}

/**
 * Live + beta providers only — what users can actually use today.
 */
export function getActiveIntegrations(): ProviderDefinition[] {
  return INTEGRATIONS.filter(p => p.status === 'live' || p.status === 'beta');
}

/**
 * Providers flagged as `popular` — surfaces in the default Marketplace view.
 */
export function getPopularIntegrations(): ProviderDefinition[] {
  return INTEGRATIONS.filter(p => p.popular);
}

/**
 * All distinct categories present in the registry, in display order.
 */
export const CATEGORIES_IN_ORDER: IntegrationCategory[] = [
  'communication', 'code_dev', 'ai_llm', 'cloud_infra', 'productivity',
  'crm_sales', 'marketing', 'analytics', 'ads', 'commerce', 'cms_site',
  'storage', 'auth', 'finance', 'support', 'observability', 'search_db',
  'crypto_web3', 'social',
];

export const CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  communication: 'Communication',
  code_dev: 'Code & Dev',
  ai_llm: 'AI & LLM',
  cloud_infra: 'Cloud Infra',
  productivity: 'Productivity',
  crm_sales: 'CRM & Sales',
  marketing: 'Marketing',
  analytics: 'Analytics',
  ads: 'Ads',
  commerce: 'Commerce',
  cms_site: 'CMS & Site',
  storage: 'Storage',
  auth: 'Auth & SSO',
  finance: 'Finance',
  support: 'Support',
  observability: 'Observability',
  search_db: 'Search & Vector DB',
  crypto_web3: 'Crypto & Web3',
  social: 'Social',
};
